# detective-content-sha256: 4755eab803149b52ec662fb12e31a1ac246fb2628b9b9c005daf2d889adda44c
"""Auto-generated by Detective — warrant-classed tests for Detective/purity.py::_SideEffectVisitor.visit_Call.
Function digest: c47597908cebe385.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import ast

import pytest
from detective_receivers import make_side_effect_visitor


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = make_side_effect_visitor().visit_Call(ast.parse("f()(x)").body[0].value)
    assert result is None
