# detective-content-sha256: d9cd84edde6e4ae8791ba970f0c9b943f8176c91178683b56ea9b01d1266533b
"""Auto-generated by Detective — warrant-classed tests for Detective/purity.py::_SideEffectVisitor.visit_Call.
Function digest: c47597908cebe385.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import ast

import pytest
from detective_receivers import make_side_effect_visitor


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = make_side_effect_visitor().visit_Call(ast.parse("f()(x)").body[0].value)
    assert result is None


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_1():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("f(x)").body[0].value)
    assert recv.reasons == []


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_2():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("print.__call__(x)").body[0].value)
    assert recv.reasons == ["calls impure builtin print.__call__"]


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_3():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("items.append(x)").body[0].value)
    assert recv.reasons == ["mutates external via .append()"]


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_4():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("path.write_text('x')").body[0].value)
    assert recv.reasons == ["filesystem write via .write_text()"]


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_5():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("s.replace('.', '_')").body[0].value)
    assert recv.reasons == []


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_6():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("path.mkdir()").body[0].value)
    assert recv.reasons == ["filesystem write via .mkdir()"]


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_7():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("path.replace(q)").body[0].value)
    assert recv.reasons == ["filesystem write via .replace()"]


@pytest.mark.detective
def test__SideEffectVisitor_visit_Call_state_8():
    """STATE survivor — receiver-state witness (equivalence search, fallback) (confidence 0.95)."""
    recv = make_side_effect_visitor()
    recv.visit_Call(ast.parse("self.append(x)").body[0].value)
    assert recv.reasons == []
