"""Auto-generated by Detective — warrant-classed tests for Detective/reachability.py::reach_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.reachability import reach_disposition


@pytest.mark.detective
def test_reach_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = reach_disposition(module_reaches=True, fixture_reaches=True)
    assert result == "direct"


@pytest.mark.detective
def test_reach_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reach_disposition(module_reaches=False, fixture_reaches=True)
    assert result == "fixture"


@pytest.mark.detective
def test_reach_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reach_disposition(module_reaches=False, fixture_reaches=False)
    assert result == "unreached"
