# detective-content-sha256: ae59c37a8e17d681f849a8b6c32e26956106ea2721edb1395cc52762f364b202
"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::deviation_depth.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import deviation_depth


@pytest.mark.detective
def test_deviation_depth_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = deviation_depth(value=1.0625, zero=1.0625)
    assert result == 0.0
