"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::render_clock_freeze.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.capabilities import render_clock_freeze


@pytest.mark.detective
def test_render_clock_freeze_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = render_clock_freeze(clock=1.0625, body_indented="abc")
    assert (
        result
        == "import time as _dtv_clock\n_dtv_clock_saved = (_dtv_clock.time, _dtv_clock.monotonic, _dtv_clock.perf_counter, _dtv_clock.time_ns, _dtv_clock.monotonic_ns)\n_dtv_clock.time = lambda: 1.0625\n_dtv_clock.monotonic = lambda: 1.0625\n_dtv_clock.perf_counter = lambda: 1.0625\n_dtv_clock.time_ns = lambda: 1062500000\n_dtv_clock.monotonic_ns = lambda: 1062500000\ntry:\nabc\nfinally:\n    (_dtv_clock.time, _dtv_clock.monotonic, _dtv_clock.perf_counter, _dtv_clock.time_ns, _dtv_clock.monotonic_ns) = _dtv_clock_saved"
    )
