# detective-content-sha256: 66919bfd52b11ac4955e4a0fb2a8a03b26ee28b4c9d5f8abb4d7d53a701606c7
"""Auto-generated by Detective — warrant-classed tests for Detective/consumption.py::declares_pinned_decision.
Function digest: 375087ce69a6ccf1.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.consumption import declares_pinned_decision


@pytest.mark.detective
def test_declares_pinned_decision_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = declares_pinned_decision(docstring="abc")
    assert result is False
