# detective-content-sha256: 0d9ef4fd4ccdb05183ce142751e08c58144703464108f42e4c71fab1ae42ece5
"""Auto-generated by Detective — warrant-classed tests for Detective/promotion_ledger.py::fixpoint_reached.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.promotion_ledger import fixpoint_reached


@pytest.mark.detective
def test_fixpoint_reached_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = fixpoint_reached(fresh_promotions=0, pending_demotions=0)
    assert result is True


@pytest.mark.detective
def test_fixpoint_reached_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = fixpoint_reached(fresh_promotions=1, pending_demotions=0)
    assert result is False


@pytest.mark.detective
def test_fixpoint_reached_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = fixpoint_reached(fresh_promotions=0, pending_demotions=1)
    assert result is False
