# detective-content-sha256: 5539290fbec1e76743791f814352ae04cf0f7dc695247919cbb3a09b7abda941
"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::verify_rewrite_note_shown.
Function digest: 603bc0092a30df7f.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import verify_rewrite_note_shown


@pytest.mark.detective
def test_verify_rewrite_note_shown_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = verify_rewrite_note_shown(verdict="abc")
    assert result == "show"


@pytest.mark.detective
def test_verify_rewrite_note_shown_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = verify_rewrite_note_shown(verdict="STALE_RECEIPT")
    assert result == "redundant"
