# detective-content-sha256: 3b48a90c0f4c77793a3f3791553d79b6dfab6b65475f82b2c0cc3f963cd029b5
"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::observation_stamp.
Function digest: 41d56a490508c84f.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import observation_stamp


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("darwin-arm64", "numpy 2.4.6"),
            "Float goldens below were OBSERVED on darwin-arm64 with numpy 2.4.6. A float produced through a platform-dependent numeric backend is an observation of that stack, not a platform-independent claim: the same call can differ in the last unit in the last place elsewhere. A mismatch on another platform is a DIFFERENT PLATFORM before it is a regression — re-generate there and compare the two, rather than treating this as red.",
        ),
        (("", "numpy 2.4.6"), ""),
    ],
)
def test_observation_stamp_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert observation_stamp(*args) == expected
