"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::execution_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import execution_disposition


@pytest.mark.detective
def test_execution_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = execution_disposition(active_environment="abc", interpreter_prefix="abc")
    assert result == "ready"
