"""Auto-generated by Detective — warrant-classed tests for Detective/suite_edit.py::removal_function_name.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.suite_edit import removal_function_name


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), "abc"),
        (("a.py::t_one",), "t_one"),
        (("legacy:a.py::t_two[x]",), "t_two"),
        (("bare",), "bare"),
    ],
)
def test_removal_function_name_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert removal_function_name(*args) == expected
