# detective-content-sha256: baf26e8d51d94f58c859c69d666c164c281cb7fc84b0b7d87d37be298edb95a5
"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::boundary_probe_values.
Function digest: b0152dfcb730a06a.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.equivalence import boundary_probe_values


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("float", False, [0], []), [-1.0, -0.5, 0.0, 0.5, 1.0]),
        (("str", False, ["pro"], []), ["pro", "", " ", "x"]),
        (
            ("dict", False, [], ["suite", "suite_exact"]),
            [
                {},
                {"suite": "x"},
                {"suite": "y"},
                {"suite": ""},
                {"suite_exact": "x"},
                {"suite_exact": "y"},
                {"suite_exact": ""},
                {"suite": "x", "suite_exact": "x"},
                {"_unread": "x"},
            ],
        ),
        (("dict", True, [], ["k"]), [None, {}, {"k": "x"}, {"k": "y"}, {"k": ""}, {"_unread": "x"}]),
        (("int", False, [2.5], []), [1, 2, 3, 0, -1]),
        (("", False, [0.5], []), [-0.5, 0.0, 0.5, 1.0, 1.5, -1.0]),
        (("", False, [1, 0.5], []), [0.0, 0.5, 1.0, 1.5, 2.0, -0.5, -1.0]),
        (("int", False, [True], []), [0, 1, -1]),
        (("float", False, [1e300], []), [0.0, 0.5, -0.5, 1.0, -1.0]),
        (("str", False, ["a", "a"], []), ["a", "", " ", "x"]),
        (("dict", False, [], ["k", "k"]), [{}, {"k": "x"}, {"k": "y"}, {"k": ""}, {"_unread": "x"}]),
        (("int", False, [-1e301], []), [0, 1, -1]),
    ],
)
def test_boundary_probe_values_golden(args, expected):
    """VALUE golden captures — pure + deterministic (12 inputs)."""
    assert boundary_probe_values(*args) == expected


@pytest.mark.detective
def test_boundary_probe_values_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = boundary_probe_values(type_name="abc", optional=True, constants=[1], keys=[1], value_type="abc")
    assert result is None


@pytest.mark.detective
def test_boundary_probe_values_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(type_name="bool", optional=False, constants=[1], keys=[1], value_type="")
    assert result == [False, True]


@pytest.mark.detective
def test_boundary_probe_values_value_2():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(type_name="", optional=False, constants=[1], keys=[1], value_type="abc")
    assert result == [0, 1, 2, -1]


@pytest.mark.detective
def test_boundary_probe_values_value_3():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(type_name="None", optional=True, constants=[1], keys=[1], value_type="abc")
    assert result == [None]


@pytest.mark.detective
def test_boundary_probe_values_value_4():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(type_name="str", optional=True, constants=[1], keys=[1], value_type="a")
    assert result == [None, "", " ", "x"]


@pytest.mark.detective
def test_boundary_probe_values_value_5():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(
        type_name="dict", optional=False, constants=[1], keys=[1], value_type="abc"
    )
    assert result == [{}, {"_unread": "x"}]


@pytest.mark.detective
def test_boundary_probe_values_value_6():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(type_name="Dict", optional=True, constants=[1], keys=[1], value_type="")
    assert result == [None, {}, {"_unread": "x"}]


@pytest.mark.detective
def test_boundary_probe_values_value_7():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_values(
        type_name="Mapping", optional=False, constants=[1], keys=[1], value_type="a"
    )
    assert result == [{}, {"_unread": "x"}]
