# detective-content-sha256: 21908fee688bbf64d8279a9107049bd29937c8109699b1e79828002486f7feea
"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::float_spelling.
Function digest: aa1e47172cea628c.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.equivalence import float_spelling


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((float("nan"),), "nan"),
        ((float("-inf"),), "-inf"),
        ((float("inf"),), "inf"),
        ((1.0625,), "finite"),
    ],
)
def test_float_spelling_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert float_spelling(*args) == expected
