# detective-content-sha256: 0cf1370fa5e93a5208aab9a1376b656ae2ce7098495c52a0e2a04d617228cf6e
"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::policy_identity.
Function digest: 5df73c97152b7cc8.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import policy_identity


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", None), "unversioned"),
        ((None, "abc"), "unrecorded"),
        (("abc", "xyz"), "moved"),
        (("abc", "abc"), "match"),
    ],
)
def test_policy_identity_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert policy_identity(*args) == expected
