"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::_worth_extracting.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose_apply import _worth_extracting


@pytest.mark.detective
def test__worth_extracting_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _worth_extracting(block_lines=18, parent_lines=20, is_wrapper=True)
    assert result is False


@pytest.mark.detective
def test__worth_extracting_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _worth_extracting(block_lines=10, parent_lines=20, is_wrapper=False)
    assert result is True


@pytest.mark.detective
def test__worth_extracting_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _worth_extracting(block_lines=20, parent_lines=20, is_wrapper=False)
    assert result is False


@pytest.mark.detective
def test__worth_extracting_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _worth_extracting(block_lines=5, parent_lines=0, is_wrapper=False)
    assert result is False


@pytest.mark.detective
def test__worth_extracting_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _worth_extracting(block_lines=5, parent_lines=-1, is_wrapper=False)
    assert result is False


@pytest.mark.detective
def test__worth_extracting_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _worth_extracting(block_lines=19, parent_lines=20, is_wrapper=False)
    assert result is True
