"""Auto-generated by Detective — warrant-classed tests for Detective/purity.py::uncovered_env_reads.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.purity import uncovered_env_reads


@pytest.mark.detective
def test_uncovered_env_reads_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = uncovered_env_reads(env_reads=("x",), clock_supplied=True)
    assert result == ("x",)
