"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::audit_headline_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import audit_headline_verdict


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, True, 1, 2), "inconsistent"),
        ((True, True, 3, 0), "complete_modulo_unproven"),
    ],
)
def test_audit_headline_verdict_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert audit_headline_verdict(*args) == expected


@pytest.mark.detective
def test_audit_headline_verdict_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_headline_verdict(
        complete=True, complete_modulo_equivalent=True, candidate_equivalent=0, crash_only_equivalent=0
    )
    assert result == "complete"


@pytest.mark.detective
def test_audit_headline_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_headline_verdict(
        complete=False, complete_modulo_equivalent=True, candidate_equivalent=1, crash_only_equivalent=2
    )
    assert result == "inconsistent"


@pytest.mark.detective
def test_audit_headline_verdict_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_headline_verdict(
        complete=True, complete_modulo_equivalent=True, candidate_equivalent=2, crash_only_equivalent=2
    )
    assert result == "complete_modulo_crash_only"


@pytest.mark.detective
def test_audit_headline_verdict_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_headline_verdict(
        complete=False, complete_modulo_equivalent=False, candidate_equivalent=-1, crash_only_equivalent=-1
    )
    assert result == "incomplete"


@pytest.mark.detective
def test_audit_headline_verdict_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_headline_verdict(
        complete=False, complete_modulo_equivalent=True, candidate_equivalent=3, crash_only_equivalent=-1
    )
    assert result == "complete_modulo_both"
