# detective-content-sha256: a3e85adcfd9947ed9143c3080133990ee734f6beb62385cd2d9acc09f91d25be
"""Auto-generated by Detective — warrant-classed tests for Detective/doctor.py::signpost_disposition.
Function digest: 8946e7cbf21b9dad.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.doctor import signpost_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", True, True, True), "unknown_herb"),
        (("yellow", False, True, False), "preempted_by_process"),
    ],
)
def test_signpost_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert signpost_disposition(*args) == expected


@pytest.mark.detective
def test_signpost_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = signpost_disposition(
        command_herb="yellow", green_finding=False, red_finding=False, yellow_finding=False
    )
    assert result == "emit"


@pytest.mark.detective
def test_signpost_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = signpost_disposition(
        command_herb="red", green_finding=True, red_finding=True, yellow_finding=True
    )
    assert result == "preempted_by_setup"


@pytest.mark.detective
def test_signpost_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = signpost_disposition(
        command_herb="yellow", green_finding=True, red_finding=False, yellow_finding=True
    )
    assert result == "preempted_by_setup"


@pytest.mark.detective
def test_signpost_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = signpost_disposition(
        command_herb="red", green_finding=False, red_finding=True, yellow_finding=False
    )
    assert result == "emit"
