"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::golden_capture_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import golden_capture_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((("x",), ("x",), ("x",), "abc", True, True), "refuse_writes"),
        (((), (), ("APP_MODE",), "", False, True), "refuse_environment_read"),
        (((), (), (), "/Users/me", False, True), "refuse_machine_path"),
        (((), (), (), "", True, True), "refuse_clock_dependent"),
        (((), (), (), "", False, False), "drop_nondeterministic"),
    ],
)
def test_golden_capture_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert golden_capture_disposition(*args) == expected
