# detective-content-sha256: 2cf1198d9bbf37be68f970af6ccc777c4ac4acd6391ac835ec47d95279bbb3e5
"""Auto-generated by Detective — warrant-classed tests for Detective/doctor.py::same_recorded_state.
Function digest: 85bdb0db7df0ecea.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.doctor import same_recorded_state


@pytest.mark.detective
def test_same_recorded_state_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={}, b={})
    assert result is True


@pytest.mark.detective
def test_same_recorded_state_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={"target_src": "x", "suite": "s"}, b={"target_src": "x", "suite": "s"})
    assert result is True


@pytest.mark.detective
def test_same_recorded_state_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={"target_src": "x", "suite": "s"}, b={"target_src": "y", "suite": "s"})
    assert result is False


@pytest.mark.detective
def test_same_recorded_state_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={"suite": "a", "suite_exact": "e"}, b={"suite": "b", "suite_exact": "e"})
    assert result is True


@pytest.mark.detective
def test_same_recorded_state_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={"suite": "a", "suite_exact": "e1"}, b={"suite": "b", "suite_exact": "e2"})
    assert result is False


@pytest.mark.detective
def test_same_recorded_state_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={"suite": "a"}, b={"suite": "b"})
    assert result is False


@pytest.mark.detective
def test_same_recorded_state_value_6():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a={"suite": "a", "suite_exact": "e"}, b={"suite": "a"})
    assert result is True


@pytest.mark.detective
def test_same_recorded_state_value_7():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = same_recorded_state(a=None, b=None)
    assert result is True
