# detective-content-sha256: d696ec7369a231578656f4e7a56c06e12867f7082eed27fc9c5919391e00ac45
"""Auto-generated by Detective — warrant-classed tests for Detective/absorption.py::absorption_disposition.
Function digest: 894ca1612ebd598d.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.absorption import absorption_disposition


@pytest.mark.detective
def test_absorption_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = absorption_disposition(declared=True, dunder=True, external_reason="abc")
    assert result == "external_stale"


@pytest.mark.detective
def test_absorption_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = absorption_disposition(declared=False, dunder=True, external_reason="")
    assert result == "data_model"


@pytest.mark.detective
def test_absorption_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = absorption_disposition(declared=False, dunder=False, external_reason="a")
    assert result == "external_declared"


@pytest.mark.detective
def test_absorption_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = absorption_disposition(declared=False, dunder=False, external_reason="")
    assert result == "undeclared"
