"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::converge_next_action.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import converge_next_action


@pytest.mark.detective
def test_converge_next_action_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = converge_next_action(session_reason="abc", has_killable=True, has_line_gap=True)
    assert result == "fix_collection"


@pytest.mark.detective
def test_converge_next_action_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = converge_next_action(session_reason="pytest_missing", has_killable=False, has_line_gap=True)
    assert result == "install_pytest"


@pytest.mark.detective
def test_converge_next_action_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = converge_next_action(session_reason="pytest_missing", has_killable=False, has_line_gap=False)
    assert result == "settled"


@pytest.mark.detective
def test_converge_next_action_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = converge_next_action(session_reason="", has_killable=False, has_line_gap=True)
    assert result == "close_the_gap"
