"""Auto-generated by Detective — warrant-classed tests for Detective/converge.py::regressed_obligations.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.converge import regressed_obligations


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["A", "B"], ["B", "C"]), ["A"]),
        ((["x"], ["x"]), []),
        ((["x", "x"], ["x"]), []),
        ((["x"], ["x", "x"]), []),
    ],
)
def test_regressed_obligations_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert regressed_obligations(*args) == expected
