"""Auto-generated by Detective — warrant-classed tests for Detective/suite_edit.py::removal_kind.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.suite_edit import removal_kind


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), "bare"),
        (("a.py::t",), "qualified"),
    ],
)
def test_removal_kind_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert removal_kind(*args) == expected


@pytest.mark.detective
def test_removal_kind_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = removal_kind(identifier="")
    assert result == "empty"
