# detective-content-sha256: 186c71d9de213855254e9e9d4361bd24a7327d615cf63f3e585d041b20d42f39
"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::nonfinite_float_spelling.
Function digest: 78ef4192f4d7867c.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.equivalence import nonfinite_float_spelling


@pytest.mark.detective
def test_nonfinite_float_spelling_value_0():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = nonfinite_float_spelling(token="nan", via_float_call=True)
    assert result == "nan"
