"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::rewrite_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import rewrite_verdict


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, 1, 2, 3), "CHANGED"),
        ((False, 0, 0, 0), "CHANGED"),
        ((True, 0, 1, 0), "CHANGED"),
        ((True, 2, 0, 0), "UNREVIEWED"),
        ((True, 0, 0, 1), "ABSTAIN"),
    ],
)
def test_rewrite_verdict_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert rewrite_verdict(*args) == expected


@pytest.mark.detective
def test_rewrite_verdict_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rewrite_verdict(proof_replayed_ok=True, new_dimensions=0, differences=0, abstentions=0)
    assert result == "PRESERVED"


@pytest.mark.detective
def test_rewrite_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rewrite_verdict(proof_replayed_ok=True, new_dimensions=1, differences=0, abstentions=0)
    assert result == "UNREVIEWED"
