# detective-content-sha256: a9c71f080bd43b9f4bb6596b4bedcb1576d9a3413d8cd1c65c1a15459f9d30e9
"""Auto-generated by Detective — warrant-classed tests for Detective/promotion_ledger.py::self_teaching_fraction.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.promotion_ledger import self_teaching_fraction


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([], []), 0.0),
        (([5], [True]), 1.0),
        (([1], [True]), 1.0),
    ],
)
def test_self_teaching_fraction_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert self_teaching_fraction(*args) == expected
