# detective-content-sha256: 9be9605ba672f5736426e5d416b6c2d5e5fe0318de6b3616f0de59f7d7c3e500
"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::decompose_outcome.
Function digest: e9f305f177507d5c.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose_apply import decompose_outcome


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, 1, True, True, 2), "proof_cut"),
        ((True, 1, True, False, 0), "applied"),
        ((False, 0, True, False, 0), "proposed"),
        ((True, 0, False, False, 0), "preservation_unproven"),
        ((True, 0, True, False, 1), "blocked_unsafe"),
        ((True, 0, True, False, 0), "already_atomic"),
    ],
)
def test_decompose_outcome_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert decompose_outcome(*args) == expected
