"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::_environment_paths.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import _environment_paths


@pytest.mark.detective
def test__environment_paths_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _environment_paths(opened=["x", "x"], args=(None,), kwargs={"x": None})
    assert result == ("x",)
