"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::hang_watchdog_seconds.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import hang_watchdog_seconds


@pytest.mark.detective
def test_hang_watchdog_seconds_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = hang_watchdog_seconds(session_budget_s=1.0625)
    assert result == 602.125


@pytest.mark.detective
def test_hang_watchdog_seconds_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = hang_watchdog_seconds(session_budget_s=-1)
    assert result == 3600.0


@pytest.mark.detective
def test_hang_watchdog_seconds_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = hang_watchdog_seconds(session_budget_s=1)
    assert result == 602.0
