# detective-content-sha256: dcb6b911b9b3b4f2ceda1d581e5b55165ca5af6114e6412d3f4dcde8e7c27d92
"""Auto-generated by Detective — warrant-classed tests for Detective/norms.py::split_of.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.norms import split_of


@pytest.mark.detective
def test_split_of_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = split_of(qualname="abc")
    assert result == "B"
