"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_flagged.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _flagged


@pytest.mark.detective
def test__flagged_boundary_0():
    """BOUNDARY survivor [BOUNDARY_90898393] — boundary at agreement=2 (>=) (confidence 0.85)."""
    result_at = _flagged(2)
    result_before = _flagged(1)
    assert result_at != result_before, "BOUNDARY at agreement=2: >= should discriminate"


@pytest.mark.detective
def test__flagged_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _flagged(agreement=3)
    assert result is True
