# detective-content-sha256: 3c901c1db106db1f2bcdd671bf6a846f929d23eeffc3df35b354d53be2a20aa0
"""Auto-generated by Detective — warrant-classed tests for Detective/validity.py::measurement_cut_reasons.
Function digest: 04b9112787657331.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.validity import measurement_cut_reasons


@pytest.mark.detective
def test_measurement_cut_reasons_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = measurement_cut_reasons(
        reported_gateable=True,
        gateable=True,
        budget_exhausted=True,
        coverage_depth="abc",
        containment="abc",
        identity_ambiguous=True,
        collection_incomplete=True,
        evaluation_failed=True,
        target_load_failed=True,
    )
    assert result == (
        "target_load_failed",
        "budget_exhausted",
        "collection_incomplete",
        "ambiguous_module_identity",
        "mutant_evaluation_failed",
    )
