"""Auto-generated by Detective — warrant-classed tests for Detective/_contain.py::remaining_budget_ms.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective._contain import remaining_budget_ms


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1.0625, 1.0625), 0.0),
        ((10.0, 20.0), 0.0),
        ((20.0, 5.0), 15.0),
    ],
)
def test_remaining_budget_ms_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert remaining_budget_ms(*args) == expected


@pytest.mark.detective
def test_remaining_budget_ms_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = remaining_budget_ms(deadline_ms=None, elapsed_ms=5.0)
    assert result is None
