# detective-content-sha256: 61fb81dd6c1a4ab7fe53baebfd430a79aeee89aa8d387aa9b98a02861532c6dc
"""Auto-generated by Detective — warrant-classed tests for Detective/promotion_ledger.py::ledger_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.promotion_ledger import ledger_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("propose", False, False), "promote"),
        (("refuse_inadmissible", False, False), "refuse"),
        (("abstain_low_kappa", False, False), "hold_low_kappa"),
        (("propose", True, False), "skip_demoted"),
        (("propose", False, True), "skip_promoted"),
    ],
)
def test_ledger_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert ledger_disposition(*args) == expected
