"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::preservation_admissible.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose_apply import preservation_admissible


@pytest.mark.detective
def test_preservation_admissible_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = preservation_admissible(functionally_complete=True, stale=True, candidate_equivalents=1)
    assert result is False


@pytest.mark.detective
def test_preservation_admissible_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = preservation_admissible(functionally_complete=True, stale=False, candidate_equivalents=0)
    assert result is True


@pytest.mark.detective
def test_preservation_admissible_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = preservation_admissible(functionally_complete=True, stale=False, candidate_equivalents=-1)
    assert result is False
