"""Auto-generated by Detective — warrant-classed tests for Detective/_contain.py::budget_is_exhausted.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective._contain import budget_is_exhausted


@pytest.mark.detective
def test_budget_is_exhausted_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = budget_is_exhausted(remaining_ms=1.0625)
    assert result is False


@pytest.mark.detective
def test_budget_is_exhausted_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = budget_is_exhausted(remaining_ms=0.0)
    assert result is True


@pytest.mark.detective
def test_budget_is_exhausted_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = budget_is_exhausted(remaining_ms=-1.0)
    assert result is True


@pytest.mark.detective
def test_budget_is_exhausted_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = budget_is_exhausted(remaining_ms=1.0)
    assert result is False
