"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_final_banner.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.certify import PytestWiring
from Detective.cli import _final_banner
from Detective.converge import ConvergeIteration, ConvergeResult
from Detective.equivalence import MutantVerdict, SurvivorReport, Witness


@pytest.mark.detective
def test__final_banner_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="m.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=4,
            final_survivors=0,
            iterations=(),
            written_path="tests/test_f_synth.py",
            total_mutants=10,
            killed=10,
            value_killed=0,
            remaining=(),
            wiring=PytestWiring(conftest_wired=None, collects=True, passed=1, message="", verification=None),
            survivor_report=None,
            functionally_complete=True,
            line_complete=True,
            missing_lines=(),
            line_basis="observed",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=3,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
            synthesized_only=False,
            policy_id=None,
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert (
        result
        == "FINAL m.py::f: ✓ COMPLETE (operator universe) · line axis unqualified (engine reports no admissible coverage) · 10/10 killed · 1 test(s) → tests/test_f_synth.py"
    )


@pytest.mark.detective
def test__final_banner_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="m.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=4,
            final_survivors=1,
            iterations=(),
            written_path="tests/test_f_synth.py",
            total_mutants=10,
            killed=8,
            value_killed=0,
            remaining=(),
            wiring=PytestWiring(conftest_wired=None, collects=True, passed=1, message="", verification=None),
            survivor_report=SurvivorReport(
                verdicts=(
                    MutantVerdict(
                        mutant_id="K1",
                        category="VALUE",
                        diff_summary="- x\n+ x+1",
                        killable=True,
                        witness=Witness(args=(1,), original="1", mutant="2", original_value=None),
                        searched=5,
                        crash_only=False,
                        crash_witness=None,
                        suite_detected=False,
                        blocked=False,
                    ),
                ),
                unclassified=(),
                note=None,
                manual_equivalent=(),
                inputs_expressible=None,
            ),
            functionally_complete=False,
            line_complete=True,
            missing_lines=(),
            line_basis="observed",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=3,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
            synthesized_only=False,
            policy_id=None,
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert result == "FINAL m.py::f: Incomplete: 1 killable · 8/10 killed · 1 test(s) → tests/test_f_synth.py"


@pytest.mark.detective
def test__final_banner_value_2():
    """VALUE survivor — distinguishing witness (original raises AttributeError: 'int' object has no attribute 'total_mutants') (confidence 0.95)."""
    try:
        _result = _final_banner(result=-1)
    except AttributeError as _exc:
        assert str(_exc) == "'int' object has no attribute 'total_mutants'"
    except BaseException as _exc:
        pytest.fail(f"expected AttributeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected AttributeError, but the call returned {_result!r}")


@pytest.mark.detective
def test__final_banner_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="calc.py::add",
            converged=True,
            at_ceiling=False,
            initial_survivors=2,
            final_survivors=2,
            iterations=(ConvergeIteration(survivors=2, written=0),),
            written_path=None,
            total_mutants=2,
            killed=0,
            value_killed=0,
            remaining=("1 ARITHMETIC", "1 STATE"),
            wiring=None,
            survivor_report=SurvivorReport(
                verdicts=(
                    MutantVerdict(
                        mutant_id="ARITHMETIC_6301ffbb",
                        category="ARITHMETIC",
                        diff_summary="- def add(a, b):\n    return a + b\n+ def add(a, b):\n    return a - b",
                        killable=True,
                        witness=Witness(args=(-1, -1), original="-2", mutant="0", original_value=-2),
                        searched=25,
                        crash_only=False,
                        crash_witness=None,
                        suite_detected=False,
                        blocked=False,
                    ),
                    MutantVerdict(
                        mutant_id="STATE_9440a774",
                        category="STATE",
                        diff_summary="- def add(a, b):\n    return a + b\n+ def add(a, b):\n    return None",
                        killable=True,
                        witness=Witness(args=(-1, -1), original="-2", mutant="None", original_value=-2),
                        searched=25,
                        crash_only=False,
                        crash_witness=None,
                        suite_detected=False,
                        blocked=False,
                    ),
                ),
                unclassified=(),
                note=None,
                manual_equivalent=(),
                inputs_expressible=True,
            ),
            functionally_complete=False,
            line_complete=False,
            missing_lines=(3,),
            line_basis="admissible",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=0,
            universe_size=2,
            fast=False,
            coverage_guarantee=1.0,
            signature="add(a, b)",
            param_names=("a", "b"),
            synthesized_only=True,
            policy_id="5.751e8e9f4f11",
            environment_coupled=(),
            stale_target=True,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert (
        result
        == "FINAL calc.py::add: ⚠ STALE — target changed during run; measurement invalid, re-run required"
    )


@pytest.mark.detective
def test__final_banner_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="m.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=4,
            final_survivors=0,
            iterations=(),
            written_path="tests/test_f_synth.py",
            total_mutants=10,
            killed=8,
            value_killed=0,
            remaining=(),
            wiring=PytestWiring(conftest_wired=None, collects=True, passed=1, message="", verification=None),
            survivor_report=None,
            functionally_complete=True,
            line_complete=False,
            missing_lines=(8, 10),
            line_basis="observed",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=3,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
            synthesized_only=False,
            policy_id=None,
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert result == "FINAL m.py::f: Incomplete: 2-line gap · 8/10 killed · 1 test(s) → tests/test_f_synth.py"


@pytest.mark.detective
def test__final_banner_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="calc.py::add",
            converged=True,
            at_ceiling=False,
            initial_survivors=2,
            final_survivors=2,
            iterations=(ConvergeIteration(survivors=2, written=0),),
            written_path=None,
            total_mutants=2,
            killed=0,
            value_killed=0,
            remaining=("1 ARITHMETIC", "1 STATE"),
            wiring=None,
            survivor_report=SurvivorReport(
                verdicts=(
                    MutantVerdict(
                        mutant_id="ARITHMETIC_6301ffbb",
                        category="ARITHMETIC",
                        diff_summary="- def add(a, b):\n    return a + b\n+ def add(a, b):\n    return a - b",
                        killable=True,
                        witness=Witness(args=(-1, -1), original="-2", mutant="0", original_value=-2),
                        searched=25,
                        crash_only=False,
                        crash_witness=None,
                        suite_detected=False,
                        blocked=False,
                    ),
                    MutantVerdict(
                        mutant_id="STATE_9440a774",
                        category="STATE",
                        diff_summary="- def add(a, b):\n    return a + b\n+ def add(a, b):\n    return None",
                        killable=True,
                        witness=Witness(args=(-1, -1), original="-2", mutant="None", original_value=-2),
                        searched=25,
                        crash_only=False,
                        crash_witness=None,
                        suite_detected=False,
                        blocked=False,
                    ),
                ),
                unclassified=(),
                note=None,
                manual_equivalent=(),
                inputs_expressible=True,
            ),
            functionally_complete=False,
            line_complete=False,
            missing_lines=(3,),
            line_basis="admissible",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=0,
            universe_size=2,
            fast=False,
            coverage_guarantee=1.0,
            signature="add(a, b)",
            param_names=("a", "b"),
            synthesized_only=True,
            policy_id="5.751e8e9f4f11",
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert (
        result
        == "FINAL calc.py::add: Incomplete: 2 killable · 1-line gap · synthesized — no pre-existing test reached it · 0/2 killed"
    )


@pytest.mark.detective
def test__final_banner_value_6():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="x.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=0,
            final_survivors=0,
            iterations=(),
            written_path="",
            total_mutants=4,
            killed=2,
            value_killed=0,
            remaining=(),
            wiring=None,
            survivor_report=None,
            functionally_complete=False,
            line_complete=True,
            missing_lines=(),
            line_basis="observed",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=0,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
            synthesized_only=False,
            policy_id=None,
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert result == "FINAL x.py::f: Incomplete · 2/4 killed"


@pytest.mark.detective
def test__final_banner_value_7():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="m.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=4,
            final_survivors=0,
            iterations=(),
            written_path=None,
            total_mutants=10,
            killed=10,
            value_killed=0,
            remaining=(),
            wiring=PytestWiring(conftest_wired=None, collects=True, passed=1, message="", verification=None),
            survivor_report=None,
            functionally_complete=True,
            line_complete=True,
            missing_lines=(),
            line_basis="observed",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=3,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
            synthesized_only=False,
            policy_id=None,
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert (
        result
        == "FINAL m.py::f: ✓ COMPLETE (operator universe) · line axis unqualified (engine reports no admissible coverage) · 10/10 killed · minimal cover 3 test(s)"
    )


@pytest.mark.detective
def test__final_banner_value_8():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        result=ConvergeResult(
            function="x.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=0,
            final_survivors=0,
            iterations=(),
            written_path="",
            total_mutants=4,
            killed=4,
            value_killed=0,
            remaining=(),
            wiring=None,
            survivor_report=None,
            functionally_complete=True,
            line_complete=True,
            missing_lines=(),
            line_basis="observed",
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=0,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
            synthesized_only=False,
            policy_id=None,
            environment_coupled=(),
            stale_target=False,
            environment_gated=(),
            budget_exhausted=False,
            cut_phase="",
            verification=None,
            stdout_bytes=0,
            needs_receiver=None,
            receiver_identity=None,
            capability_identity=None,
        )
    )
    assert (
        result
        == "FINAL x.py::f: ✓ COMPLETE (operator universe) · line axis unqualified (engine reports no admissible coverage) · 4/4 killed"
    )
