# detective-content-sha256: 6bb294d2c13aef355713f7467f6c9f44d315e9353370cc7f5c93f3726aae9302
"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::rewrite_verdict.
Function digest: d99c901e9d5df0e8.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import rewrite_verdict


@pytest.mark.detective
def test_rewrite_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = rewrite_verdict(
        receipt_valid=True,
        classification_ran=True,
        proof_replayed_ok=True,
        new_dimensions=1,
        differences=2,
        abstentions=3,
        delta_status="abc",
    )
    assert result == "CHANGED"


@pytest.mark.detective
def test_rewrite_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rewrite_verdict(
        receipt_valid=True,
        classification_ran=True,
        proof_replayed_ok=True,
        new_dimensions=-1,
        differences=-1,
        abstentions=-1,
        delta_status="a",
    )
    assert result == "PRESERVED"


@pytest.mark.detective
def test_rewrite_verdict_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rewrite_verdict(
        receipt_valid=False,
        classification_ran=False,
        proof_replayed_ok=False,
        new_dimensions=-1,
        differences=-1,
        abstentions=-1,
        delta_status="changed",
    )
    assert result == "ABSTAIN"


@pytest.mark.detective
def test_rewrite_verdict_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rewrite_verdict(
        receipt_valid=True,
        classification_ran=True,
        proof_replayed_ok=True,
        new_dimensions=1,
        differences=1,
        abstentions=1,
        delta_status="x",
    )
    assert result == "CHANGED"
