# detective-content-sha256: 9dd5f09a4c0ee0726c28c1796c83ff77148cf125b97eb533ac4a9b1f3911ca17
"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/writer.py::numeric_backend_for.
Function digest: b5d7911dded337c1.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.writer import numeric_backend_for


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("import numpy as np\n",), "numpy"),
        (("from scipy.linalg import norm\n",), "scipy"),
        (("def f():\n    return 1\n",), ""),
    ],
)
def test_numeric_backend_for_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert numeric_backend_for(*args) == expected
