# detective-content-sha256: a58fcc3593a50b41a207080ff4f1154eb5b227249702f96d9430dab5050f7d26
"""Auto-generated by Detective — warrant-classed tests for Detective/budget.py::growth_class.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.budget import growth_class


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([1.0], [1.0]), "unmeasurable"),
        (([1.0, 1.0], [1.0]), "unmeasurable"),
        (([1.0], [1.0, 1.0]), "unmeasurable"),
    ],
)
def test_growth_class_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert growth_class(*args) == expected
