"""Auto-generated by Detective — warrant-classed tests for Detective/verdict_cache.py::proof_cache_admits.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.verdict_cache import proof_cache_admits


@pytest.mark.detective
def test_proof_cache_admits_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = proof_cache_admits(gateable=True, budget_exhausted=True, engine_reports_gateable=True)
    assert result is False


@pytest.mark.detective
def test_proof_cache_admits_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = proof_cache_admits(gateable=False, budget_exhausted=False, engine_reports_gateable=False)
    assert result is True
