# detective-content-sha256: 572b4d4cae34b51a0dcf529272f40fd288da670962bf2d75fa8e40bbf69174b4
"""Auto-generated by Detective — warrant-classed tests for Detective/plan.py::next_command.
Function digest: a7994a98247651c6.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.plan import next_command


@pytest.mark.detective
def test_next_command_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = next_command(reason="abc", region="abc", gate="abc", move="abc")
    assert result == ""
