# detective-content-sha256: 13f43debffee5e303e78ad87ff64ccaba9fd9e893425930240583a5f36f4eddd
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::no_tests_attribution.
Function digest: d71fbb93750aaf5e.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import no_tests_attribution


@pytest.mark.detective
def test_no_tests_attribution_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = no_tests_attribution(tests_discovered=1, load_failed=True)
    assert result == "silent"


@pytest.mark.detective
def test_no_tests_attribution_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = no_tests_attribution(tests_discovered=0, load_failed=False)
    assert result == "absent_tests"


@pytest.mark.detective
def test_no_tests_attribution_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = no_tests_attribution(tests_discovered=0, load_failed=True)
    assert result == "cause_below"
