"""Auto-generated by Detective — warrant-classed tests for Detective/validity.py::measurement_cut_reasons.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.validity import measurement_cut_reasons


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, True, True, "abc", "abc", True), ("budget_exhausted", "ambiguous_module_identity")),
        ((True, False, False, "profiled", "contained", False), ("engine_refused_unspecified",)),
    ],
)
def test_measurement_cut_reasons_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert measurement_cut_reasons(*args) == expected


@pytest.mark.detective
def test_measurement_cut_reasons_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = measurement_cut_reasons(
        reported_gateable=False,
        gateable=False,
        budget_exhausted=False,
        coverage_depth="cut",
        containment="uncontained",
        identity_ambiguous=False,
    )
    assert result == ("uncontained_worker", "coverage_truncated")


@pytest.mark.detective
def test_measurement_cut_reasons_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = measurement_cut_reasons(
        reported_gateable=False,
        gateable=False,
        budget_exhausted=False,
        coverage_depth="sampled",
        containment="uncontained",
        identity_ambiguous=False,
    )
    assert result == ("uncontained_worker", "sampled_universe")
