"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::parameter_scope.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import parameter_scope


@pytest.mark.detective
def test_parameter_scope_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = parameter_scope(param_names=("x",))
    assert result == "known"


@pytest.mark.detective
def test_parameter_scope_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = parameter_scope(param_names=None)
    assert result == "unknown"


@pytest.mark.detective
def test_parameter_scope_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = parameter_scope(param_names=())
    assert result == "none"
