"""Auto-generated by Detective — warrant-classed tests for Detective/reachability.py::within_declared_testpaths.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.reachability import within_declared_testpaths


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("tests/test_x.py", []), "unrestricted"),
        (("tests/test_x.py", ["tests"]), "within"),
        ((".venv312/lib/test_y.py", ["tests"]), "foreign"),
        (("tests", ["tests"]), "within"),
        (("testsuite/test_x.py", ["tests"]), "foreign"),
        (("src/pkg/tests/test_z.py", ["src/pkg/tests", "tests"]), "within"),
    ],
)
def test_within_declared_testpaths_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert within_declared_testpaths(*args) == expected
