"""Auto-generated by Detective — warrant-classed tests for Detective/reachability.py::is_virtualenv_root.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.reachability import is_virtualenv_root


@pytest.mark.detective
def test_is_virtualenv_root_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_virtualenv_root(dir_filenames=["pyvenv.cfg", "bin", "lib"])
    assert result is True


@pytest.mark.detective
def test_is_virtualenv_root_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_virtualenv_root(dir_filenames=["setup.py", "src"])
    assert result is False


@pytest.mark.detective
def test_is_virtualenv_root_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_virtualenv_root(dir_filenames=[])
    assert result is False


@pytest.mark.detective
def test_is_virtualenv_root_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_virtualenv_root(dir_filenames=["x"])
    assert result is False


@pytest.mark.detective
def test_is_virtualenv_root_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_virtualenv_root(dir_filenames=["x", "x"])
    assert result is False
