# detective-content-sha256: 544edd9314554e84c96491f9f8771d38b1e03bad8fa5a3972265f2d398492f47
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::diagnose_next_action.
Function digest: ccc9b5e1d78c68cc.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import diagnose_next_action


@pytest.mark.detective
def test_diagnose_next_action_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = diagnose_next_action(entangled=True, seams=1, unspecified_dof=2)
    assert result == "decompose_first"


@pytest.mark.detective
def test_diagnose_next_action_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = diagnose_next_action(entangled=True, seams=2, unspecified_dof=2)
    assert result == "decompose_first"


@pytest.mark.detective
def test_diagnose_next_action_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = diagnose_next_action(entangled=True, seams=-1, unspecified_dof=-1)
    assert result == "settled"


@pytest.mark.detective
def test_diagnose_next_action_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = diagnose_next_action(entangled=False, seams=3, unspecified_dof=0)
    assert result == "settled"


@pytest.mark.detective
def test_diagnose_next_action_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = diagnose_next_action(entangled=False, seams=1, unspecified_dof=1)
    assert result == "close_the_gap"


@pytest.mark.detective
def test_diagnose_next_action_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = diagnose_next_action(entangled=True, seams=0, unspecified_dof=1)
    assert result == "close_the_gap"
