"""Auto-generated by Detective — warrant-classed tests for Detective/session_manifest.py::module_identity_conflicts.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.session_manifest import module_identity_conflicts


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"pkg.mod": ["/a/mod.py", "/b/mod.py"], "pkg.ok": ["/a/ok.py"], "pkg.empty": []},), ["pkg.mod"]),
        (({"x": ["x"]},), []),
    ],
)
def test_module_identity_conflicts_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert module_identity_conflicts(*args) == expected
