"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony_map.py::_clean_pct.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony_map import _clean_pct


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2), 50),
        ((2, 1), -100),
    ],
)
def test__clean_pct_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _clean_pct(*args) == expected


@pytest.mark.detective
def test__clean_pct_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _clean_pct(flagged=-1, total=0)
    assert result == 100


@pytest.mark.detective
def test__clean_pct_value_1():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = _clean_pct(flagged=1, total=2)
    assert result == 50
    assert type(result) is int


@pytest.mark.detective
def test__clean_pct_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _clean_pct(flagged=-1, total=-1)
    assert result == 0
