"""Auto-generated by Detective — warrant-classed tests for Detective/binding.py::classify_binding_kind.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.binding import classify_binding_kind


@pytest.mark.detective
def test_classify_binding_kind_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_binding_kind(decorators=("x",), in_class=True, first_param="abc")
    assert repr(result) == "<BindingKind.UNSUPPORTED: 'unsupported'>"


@pytest.mark.detective
def test_classify_binding_kind_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_binding_kind(decorators=("x",), in_class=True, first_param="self")
    assert repr(result) == "<BindingKind.INSTANCE_METHOD: 'instance_method'>"


@pytest.mark.detective
def test_classify_binding_kind_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_binding_kind(decorators=("x",), in_class=False, first_param="self")
    assert repr(result) == "<BindingKind.FUNCTION: 'function'>"


@pytest.mark.detective
def test_classify_binding_kind_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = classify_binding_kind(decorators=("x",), in_class=True, first_param="cls")
    assert repr(result) == "<BindingKind.INSTANCE_METHOD: 'instance_method'>"


@pytest.mark.detective
def test_classify_binding_kind_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_binding_kind(decorators=("property",), in_class=True, first_param="self")
    assert repr(result) == "<BindingKind.PROPERTY: 'property'>"


@pytest.mark.detective
def test_classify_binding_kind_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_binding_kind(decorators=("staticmethod",), in_class=True, first_param="x")
    assert repr(result) == "<BindingKind.STATIC_METHOD: 'static_method'>"


@pytest.mark.detective
def test_classify_binding_kind_value_6():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_binding_kind(decorators=("classmethod",), in_class=True, first_param="cls")
    assert repr(result) == "<BindingKind.CLASS_METHOD: 'class_method'>"
