"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::clock_covers.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.capabilities import clock_covers


@pytest.mark.detective
def test_clock_covers_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = clock_covers(reason="abc")
    assert result is False
