# detective-content-sha256: 8d2d391ac9237f0aaa21b8f3b6a3440d34fb802573a06366783617047df96067
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::measurement_block_route.
Function digest: 039a79c196da373c.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import measurement_block_route


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, None, False), "fix_load"),
        ((False, False, False), "close_the_gap"),
        ((False, None, True), "provide_sample"),
        ((False, None, False), ""),
    ],
)
def test_measurement_block_route_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert measurement_block_route(*args) == expected
