"""Auto-generated by Detective — warrant-classed tests for Detective/suite_edit.py::removal_file_hint.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.suite_edit import removal_file_hint


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), ""),
        (("a.py::t_one",), "a.py"),
        (("legacy:?::t_two",), ""),
        (("bare",), ""),
        (("legacy:a.py::t[x]",), "a.py"),
    ],
)
def test_removal_file_hint_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert removal_file_hint(*args) == expected
