# detective-content-sha256: 744f1a29f0c2d0c6548b6a619f905720023be39baaab2fcf926eae3a7712e523
"""Auto-generated by Detective — warrant-classed tests for Detective/capture.py::profile_hook_disposition.
Function digest: e245a4c5120ff9fc.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.capture import profile_hook_disposition


@pytest.mark.detective
def test_profile_hook_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = profile_hook_disposition(prev_is_none=True, prev_is_callable=True)
    assert result == "install"


@pytest.mark.detective
def test_profile_hook_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = profile_hook_disposition(prev_is_none=False, prev_is_callable=True)
    assert result == "install_and_restore"


@pytest.mark.detective
def test_profile_hook_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = profile_hook_disposition(prev_is_none=False, prev_is_callable=False)
    assert result == "foreign_unrestorable"
