# detective-content-sha256: 4104f3a69e437a1c3b701fe93177a2b444664668481f3d98e45595b8a580d27d
"""Auto-generated by Detective — warrant-classed tests for Detective/call_sites.py::usage_evidence_class.
Function digest: 3d24105bd9fcb45f.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.call_sites import usage_evidence_class


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((("x",),), "none"),
        ((("attr:shape",),), "resolved"),
        ((("subscript", "subscript_tuple"),), "unresolved_object"),
    ],
)
def test_usage_evidence_class_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert usage_evidence_class(*args) == expected
