"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_width_vote.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _width_vote


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1,), 1),
        ((5,), -1),
    ],
)
def test__width_vote_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _width_vote(*args) == expected


@pytest.mark.detective
def test__width_vote_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _width_vote(n_params=0)
    assert result == 1


@pytest.mark.detective
def test__width_vote_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _width_vote(n_params=2)
    assert result == 0


@pytest.mark.detective
def test__width_vote_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _width_vote(n_params=4)
    assert result == 0
