"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::helper_generic_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose_apply import helper_generic_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([], []), ""),
        (([["E", "E", []]], ["E"]), "[E]"),
        (([["E", "E", []], ["R", "R: list[E]", ["E"]]], ["R"]), "[E, R: list[E]]"),
        (([["E", "E", ["X"]]], ["E"]), "[E]"),
        (([["E", "E", []]], []), ""),
        (
            (
                [
                    ["T", "T: list[T]", ["B", "E"]],
                    ["R", "R", []],
                    ["E", "E: list[T]", ["T"]],
                    ["B", "B", ["E", "T"]],
                ],
                ["R", "B", "T", "E", "X"],
            ),
            "[T: list[T], R, E: list[T], B]",
        ),
        (
            (
                [["T", "T", ["E", "B"]], ["E", "E", ["A"]], ["A", "A", ["T", "B"]], ["B", "B", ["E"]]],
                ["A", "X"],
            ),
            "[T, E, A, B]",
        ),
    ],
)
def test_helper_generic_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert helper_generic_clause(*args) == expected
