"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::structural_input_difficulty.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.equivalence import structural_input_difficulty


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, True, False), "deep_structural"),
        ((True, False, False), "flat"),
    ],
)
def test_structural_input_difficulty_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert structural_input_difficulty(*args) == expected
