# detective-content-sha256: b9c3cbf4af98dfa7f65350622aa8b2ef6df169c413bfbdc4fd63b5a2e3c9e4a7
"""Auto-generated by Detective — warrant-classed tests for Detective/doctor.py::mix_product.
Function digest: a8da5965e9ef25d5.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.doctor import mix_product


@pytest.mark.detective
def test_mix_product_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = mix_product(green_live=True, red_live=True, yellow_live=True)
    assert result == "ordered_remediation"


@pytest.mark.detective
def test_mix_product_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mix_product(green_live=False, red_live=True, yellow_live=False)
    assert result == "none"


@pytest.mark.detective
def test_mix_product_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mix_product(green_live=False, red_live=False, yellow_live=True)
    assert result == "none"


@pytest.mark.detective
def test_mix_product_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mix_product(green_live=True, red_live=True, yellow_live=False)
    assert result == "suppression"


@pytest.mark.detective
def test_mix_product_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mix_product(green_live=True, red_live=False, yellow_live=True)
    assert result == "unreliability"


@pytest.mark.detective
def test_mix_product_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mix_product(green_live=False, red_live=True, yellow_live=True)
    assert result == "ordering"
