# detective-content-sha256: dc52ca1e85393284a74cf26d112a5f343695556b7007069a808c8e04f3591478
"""Auto-generated by Detective — warrant-classed tests for Detective/ledger.py::state_basis.
Function digest: db2322ec1804b855.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.ledger import state_basis


@pytest.mark.detective
def test_state_basis_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = state_basis(has_prior=True, same_args=True, cheap_says_changed=True)
    assert result == "escalate_exact"


@pytest.mark.detective
def test_state_basis_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = state_basis(has_prior=False, same_args=False, cheap_says_changed=False)
    assert result == "cheap"


@pytest.mark.detective
def test_state_basis_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = state_basis(has_prior=True, same_args=False, cheap_says_changed=False)
    assert result == "cheap"


@pytest.mark.detective
def test_state_basis_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = state_basis(has_prior=True, same_args=True, cheap_says_changed=False)
    assert result == "cheap"
