# detective-content-sha256: 985b29969b3c4346d61a518e3571574254b4230e824b2c7669dbad624a856e24
"""Auto-generated by Detective — warrant-classed tests for Detective/doctor.py::taste_disposition.
Function digest: 8e61021c7733b6c6.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.doctor import taste_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2, 3, 4, 5), "extractable_core"),
        ((3, 0, 0, 0, 1), "unresolved_param"),
        ((3, 0, 0, 0, 0), "clear"),
    ],
)
def test_taste_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert taste_disposition(*args) == expected


@pytest.mark.detective
def test_taste_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = taste_disposition(
        scanned=0, extractable_core=0, impure_body=0, trapped_by_imports=0, unresolved_param=0
    )
    assert result == "nothing_to_read"


@pytest.mark.detective
def test_taste_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = taste_disposition(
        scanned=-1, extractable_core=-1, impure_body=-1, trapped_by_imports=-1, unresolved_param=-1
    )
    assert result == "nothing_to_read"


@pytest.mark.detective
def test_taste_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = taste_disposition(
        scanned=3, extractable_core=0, impure_body=2, trapped_by_imports=-1, unresolved_param=1
    )
    assert result == "impure_body"


@pytest.mark.detective
def test_taste_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = taste_disposition(
        scanned=2, extractable_core=-1, impure_body=1, trapped_by_imports=3, unresolved_param=0
    )
    assert result == "impure_body"


@pytest.mark.detective
def test_taste_disposition_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = taste_disposition(
        scanned=3, extractable_core=-1, impure_body=0, trapped_by_imports=1, unresolved_param=2
    )
    assert result == "trapped_by_imports"


@pytest.mark.detective
def test_taste_disposition_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = taste_disposition(
        scanned=1, extractable_core=1, impure_body=1, trapped_by_imports=1, unresolved_param=1
    )
    assert result == "extractable_core"
