"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_suggest_name.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose import _suggest_name


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"out"}, "conj"), "_conj_helper"),
        (({"a", "b"}, "match_entities"), "_match_entities_helper"),
        (({"a", "b"}, "_conjunction_sentences"), "_conjunction_sentences_helper"),
    ],
)
def test__suggest_name_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _suggest_name(*args) == expected
