"""Auto-generated by Detective — warrant-classed tests for Detective/validity.py::cut_reason_sentence.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.validity import cut_reason_sentence


@pytest.mark.detective
def test_cut_reason_sentence_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = cut_reason_sentence(reason="abc")
    assert result == "an unrecognised engine refusal (abc)"


@pytest.mark.detective
def test_cut_reason_sentence_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = cut_reason_sentence(reason="")
    assert result == "an unrecognised engine refusal ()"
