# detective-content-sha256: b6b068fc0c61050965eabf2da01e2e749db75dbda05f5fcfaefa0c16a15d90aa
"""Auto-generated by Detective — warrant-classed tests for Detective/ledger.py::spiral_disposition.
Function digest: f2918e7a16dd18d9.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.ledger import spiral_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, True, True, 1), "repeat_no_change"),
        ((True, True, False, 0), "repeat_state_changed"),
    ],
)
def test_spiral_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert spiral_disposition(*args) == expected


@pytest.mark.detective
def test_spiral_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = spiral_disposition(has_prior=True, same_args=True, same_state=True, identical_repeats=2)
    assert result == "spiral"


@pytest.mark.detective
def test_spiral_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = spiral_disposition(has_prior=True, same_args=True, same_state=True, identical_repeats=3)
    assert result == "spiral"


@pytest.mark.detective
def test_spiral_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = spiral_disposition(has_prior=False, same_args=False, same_state=False, identical_repeats=1)
    assert result == "no_prior"


@pytest.mark.detective
def test_spiral_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = spiral_disposition(has_prior=True, same_args=False, same_state=True, identical_repeats=0)
    assert result == "progressed"
