# detective-content-sha256: 78f0aa85a1750435e0e9b3aafa8ec3fbd7d366d90c1c5a7741a424ff0c66f81f
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::residual_done_why.
Function digest: fb72413bd4e6c0f9.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.cli import residual_done_why


@pytest.mark.detective
def test_residual_done_why_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = residual_done_why(basis="unprobed")
    assert (
        result
        == "What remains was not distinguished by any input Detective TRIED. That is\na fact about a bounded search, not a frontier — it may be SEARCH BUDGET.\nBefore accepting `modulo N`, probe each survivor with boundary inputs\n(both sides of every comparison edge, the None of every Optional) via\n--input. Flag only what you can prove."
    )


@pytest.mark.detective
def test_residual_done_why_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = residual_done_why(basis="")
    assert result == "unrecognised residual basis: "


@pytest.mark.detective
def test_residual_done_why_value_2():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = residual_done_why(basis="none")
    assert result == "The suite pins every behaviour this function makes."
