# detective-content-sha256: e5b2d057fefedc05e2e002bd8e9711a2c5311d35d9d4408b4659175f52183283
"""Auto-generated by Detective — warrant-classed tests for Detective/trial_journal.py::trial_recovery_disposition.
Function digest: f81587083be34eb4.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.trial_journal import trial_recovery_disposition


@pytest.mark.detective
def test_trial_recovery_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = trial_recovery_disposition(current_digest="abc", trial_digest="abc", original_digest="abc")
    assert result == "already_restored"


@pytest.mark.detective
def test_trial_recovery_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = trial_recovery_disposition(current_digest="a", trial_digest="", original_digest="")
    assert result == "diverged"


@pytest.mark.detective
def test_trial_recovery_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = trial_recovery_disposition(current_digest="a", trial_digest="a", original_digest="")
    assert result == "restore"
