# detective-content-sha256: af0a4c6b94e96f9409a20fe94215db9086361cb494effcfa76a7a6a042ee682d
"""Auto-generated by Detective — warrant-classed tests for Detective/doctor.py::command_setup_fault.
Function digest: d7f8d8d33869b69c.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.doctor import command_setup_fault


@pytest.mark.detective
def test_command_setup_fault_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = command_setup_fault(regime_conflict="abc", load_failed=True, collection_incomplete=True)
    assert result == "regime_conflict"


@pytest.mark.detective
def test_command_setup_fault_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = command_setup_fault(regime_conflict="", load_failed=True, collection_incomplete=False)
    assert result == "target_load_failed"


@pytest.mark.detective
def test_command_setup_fault_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = command_setup_fault(regime_conflict="", load_failed=False, collection_incomplete=True)
    assert result == "collection_incomplete"


@pytest.mark.detective
def test_command_setup_fault_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = command_setup_fault(regime_conflict="", load_failed=False, collection_incomplete=False)
    assert result == "none"
