"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::_pair_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.equivalence import _pair_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("<classifier-timeout>", "x"), "blocked"),
        (("5", "6"), "witness"),
    ],
)
def test__pair_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _pair_disposition(*args) == expected
