"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::trial_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose import trial_verdict


@pytest.mark.detective
def test_trial_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = trial_verdict(proven=True, has_proof_suite=True, apply_disposition_code="abc")
    assert result == "witnessed"


@pytest.mark.detective
def test_trial_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = trial_verdict(proven=True, has_proof_suite=False, apply_disposition_code="apply")
    assert result == "proven"


@pytest.mark.detective
def test_trial_verdict_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = trial_verdict(proven=False, has_proof_suite=False, apply_disposition_code="apply")
    assert result == "unproven"


@pytest.mark.detective
def test_trial_verdict_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = trial_verdict(proven=False, has_proof_suite=True, apply_disposition_code="apply")
    assert result == "rejected"
