# detective-content-sha256: 739337034dc5b6e443a2ba93ee9f4f3fe3d0946f51085bba95a5bcb12ceb49de
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::universe_claim.
Function digest: 64fcdc5a4e7ba652.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import universe_claim


@pytest.mark.detective
def test_universe_claim_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = universe_claim(fast=True, approximate_universe=True)
    assert result == "fast_sampled"


@pytest.mark.detective
def test_universe_claim_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = universe_claim(fast=False, approximate_universe=True)
    assert result == "comprehensive_estimated"


@pytest.mark.detective
def test_universe_claim_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = universe_claim(fast=False, approximate_universe=False)
    assert result == "comprehensive_exact"
