# detective-content-sha256: a7b799f512289b591a91dfaa3cb546f528dff5ccd1da126acdd3668e259bf3e7
"""Auto-generated by Detective — warrant-classed tests for Detective/ledger.py::outcome_disposition.
Function digest: 3ca510f4e82a2cc7.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.ledger import outcome_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2, True), "authoritative"),
        ((1, 0, False), "authoritative"),
        ((2, 0, True), "authoritative"),
        ((0, 1, False), "nested_only"),
    ],
)
def test_outcome_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert outcome_disposition(*args) == expected


@pytest.mark.detective
def test_outcome_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = outcome_disposition(matching_count=0, other_count=-1, matching_are_identical=False)
    assert result == "unobserved"


@pytest.mark.detective
def test_outcome_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = outcome_disposition(matching_count=0, other_count=0, matching_are_identical=False)
    assert result == "unobserved"


@pytest.mark.detective
def test_outcome_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = outcome_disposition(matching_count=2, other_count=1, matching_are_identical=False)
    assert result == "ambiguous"
