"""Auto-generated by Detective — warrant-classed tests for Detective/audit.py::audit_partition_sums.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.audit import audit_partition_sums


@pytest.mark.detective
def test_audit_partition_sums_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = audit_partition_sums(
        total=1, value_killed=2, killable=3, candidate_equivalent=4, manual=5, unclassified=6
    )
    assert result is False


@pytest.mark.detective
def test_audit_partition_sums_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_partition_sums(
        total=-1, value_killed=0, killable=1, candidate_equivalent=2, manual=3, unclassified=-1
    )
    assert result is False


@pytest.mark.detective
def test_audit_partition_sums_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_partition_sums(
        total=1, value_killed=3, killable=0, candidate_equivalent=2, manual=-1, unclassified=1
    )
    assert result is False


@pytest.mark.detective
def test_audit_partition_sums_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_partition_sums(
        total=-1, value_killed=1, killable=3, candidate_equivalent=0, manual=2, unclassified=-1
    )
    assert result is False


@pytest.mark.detective
def test_audit_partition_sums_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_partition_sums(
        total=0, value_killed=0, killable=0, candidate_equivalent=0, manual=0, unclassified=0
    )
    assert result is True
