# detective-content-sha256: 082e932a4b3e29f4bb18e57f226d761216a04d9167ffba4955e8867b2e52e669
"""Auto-generated by Detective — warrant-classed tests for Detective/norms.py::weighted_median.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.norms import weighted_median


@pytest.mark.detective
def test_weighted_median_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = weighted_median(values=[1.0], weights=[1.0])
    assert result == 1.0


@pytest.mark.detective
def test_weighted_median_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = weighted_median(values=[1.0, 1.0], weights=[1.0])
    assert result is None


@pytest.mark.detective
def test_weighted_median_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = weighted_median(values=[1.0], weights=[1.0, 1.0])
    assert result is None
