"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::value_capture_coupling.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import value_capture_coupling


@pytest.mark.detective
def test_value_capture_coupling_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = value_capture_coupling(disposition="abc")
    assert result == "none"


@pytest.mark.detective
def test_value_capture_coupling_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = value_capture_coupling(disposition="refuse_environment_read")
    assert result == "function_coupled"


@pytest.mark.detective
def test_value_capture_coupling_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = value_capture_coupling(disposition="refuse_machine_path")
    assert result == "value_local"


@pytest.mark.detective
def test_value_capture_coupling_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = value_capture_coupling(disposition="refuse_clock_dependent")
    assert result == "function_coupled"


@pytest.mark.detective
def test_value_capture_coupling_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = value_capture_coupling(disposition="refuse_default_path_read")
    assert result == "function_coupled"


@pytest.mark.detective
def test_value_capture_coupling_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = value_capture_coupling(disposition="refuse_writes")
    assert result == "function_coupled"
