# detective-content-sha256: cc5db035ccc573897dd560e0782f294d92169285cd28ba906bd36f597b3d3b8a
"""Auto-generated by Detective — warrant-classed tests for Detective/equivalents.py::contract_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.equivalents import contract_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((False, True, True, "equivalent"), "equivalent"),
        ((False, True, True, "fence"), "fence"),
        ((False, True, True, ""), "unclassified"),
        ((True, True, True, ""), "killable"),
        ((True, False, True, ""), "unclassified"),
        ((True, False, False, "equivalent"), "equivalent"),
        ((True, False, False, "fence"), "fence"),
        ((True, False, False, ""), "candidate"),
    ],
)
def test_contract_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (8 inputs)."""
    assert contract_disposition(*args) == expected
