"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::apply_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose import apply_disposition


@pytest.mark.detective
def test_apply_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = apply_disposition(evidences=["x"])
    assert result == "apply"
