"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_overload_vote.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _overload_vote


@pytest.mark.detective
def test__overload_vote_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _overload_vote(dof_density=1.0625)
    assert result == 0


@pytest.mark.detective
def test__overload_vote_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _overload_vote(dof_density=2.5)
    assert result == -1


@pytest.mark.detective
def test__overload_vote_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _overload_vote(dof_density=1.0)
    assert result == 1


@pytest.mark.detective
def test__overload_vote_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _overload_vote(dof_density=-1.0)
    assert result == 1
