# detective-content-sha256: a0bebdd020d52a3f1032067843421d6cd9c559b8ed9b7d392673897cc3a4ad43
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::diagnose_next_action.
Function digest: f080290e34eb30e4.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import diagnose_next_action


@pytest.mark.detective
def test_diagnose_next_action_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = diagnose_next_action(block="abc", entangled=True, seams=1, unspecified_dof=2)
    assert result == "abc"


@pytest.mark.detective
def test_diagnose_next_action_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = diagnose_next_action(block="", entangled=True, seams=2, unspecified_dof=2)
    assert result == "decompose_first"
