"""Auto-generated by Detective — warrant-classed tests for Detective/adequacy.py::adequacy_bucket.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.adequacy import adequacy_bucket


@pytest.mark.detective
def test_adequacy_bucket_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = adequacy_bucket(produced=True, import_broke=True, suite_passed=True)
    assert result == "structurally_impossible"


@pytest.mark.detective
def test_adequacy_bucket_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = adequacy_bucket(produced=True, import_broke=False, suite_passed=False)
    assert result == "detected"


@pytest.mark.detective
def test_adequacy_bucket_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = adequacy_bucket(produced=False, import_broke=False, suite_passed=False)
    assert result == "not_applicable"


@pytest.mark.detective
def test_adequacy_bucket_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = adequacy_bucket(produced=True, import_broke=False, suite_passed=True)
    assert result == "undetected"
