"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::_block_span_with_comments.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose_apply import _block_span_with_comments


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["def f():\n", "    x = 1\n", "        # c\n", "    y = 2\n"], 2, 2), (2, 3)),
        ((["a\n", "    x=1\n", "    y=2\n"], 2, 2), (2, 2)),
        ((["a\n", "    x\n", "        # c1\n", "        # c2\n", "    y\n"], 2, 2), (2, 4)),
        ((["a\n", "    x\n", "    # same\n", "    y\n"], 2, 2), (2, 2)),
        ((["a\n", "    x\n", "    y\n"], 2, 2), (2, 2)),
        ((["a\n", "    x\n"], 2, 2), (2, 2)),
    ],
)
def test__block_span_with_comments_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert _block_span_with_comments(*args) == expected
