"""Auto-generated by Detective — warrant-classed tests for Detective/audit.py::mutation_estimate_seconds.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.audit import mutation_estimate_seconds


@pytest.mark.detective
def test_mutation_estimate_seconds_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = mutation_estimate_seconds(mutant_count=1, per_mutant_ms=1.0625)
    assert result == 0.0010625


@pytest.mark.detective
def test_mutation_estimate_seconds_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutation_estimate_seconds(mutant_count=0, per_mutant_ms=-1.0)
    assert result == -0.0


@pytest.mark.detective
def test_mutation_estimate_seconds_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = mutation_estimate_seconds(mutant_count=-1, per_mutant_ms=-1.0)
    assert result is None
