# detective-content-sha256: 30cc8692b5a86182201583cf950f0a879493cec1385e587c19e4b44553f42776
"""Auto-generated by Detective — warrant-classed tests for Detective/doctor.py::setup_disposition.
Function digest: 83c068e309f5c55a.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.doctor import setup_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", True, ("x",), ("x",), True, True), "regime_conflict"),
        (("", True, ("funcy",), ("funcy",), False, False), "deps_elsewhere"),
        (("", True, ("funcy",), (), False, False), "deps_missing"),
        (("", True, (), (), True, False), "stale_load_failure"),
        (("", True, (), (), False, True), "stale_collection_failure"),
        (("", True, (), (), False, False), "clean"),
        (("", False, (), (), False, False), "no_pytest"),
    ],
)
def test_setup_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert setup_disposition(*args) == expected
