"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::env_token_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.capabilities import env_token_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc",), "malformed"),
        (("NAME=value",), "set"),
        (("=value",), "malformed"),
        (("NAME-",), "absent"),
        (("-",), "malformed"),
        (("x-",), "absent"),
    ],
)
def test_env_token_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert env_token_disposition(*args) == expected
