"""Auto-generated by Detective — warrant-classed tests for Detective/certify.py::pytest_status.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.certify import pytest_status


@pytest.mark.detective
def test_pytest_status_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = pytest_status(returncode=1, passed=2)
    assert result == "tests_failed"


@pytest.mark.detective
def test_pytest_status_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_status(returncode=0, passed=-1)
    assert result == "no_tests"


@pytest.mark.detective
def test_pytest_status_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_status(returncode=0, passed=0)
    assert result == "no_tests"


@pytest.mark.detective
def test_pytest_status_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_status(returncode=0, passed=1)
    assert result == "passed"


@pytest.mark.detective
def test_pytest_status_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_status(returncode=2, passed=-1)
    assert result == "collection_failed"


@pytest.mark.detective
def test_pytest_status_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_status(returncode=5, passed=-1)
    assert result == "no_tests"


@pytest.mark.detective
def test_pytest_status_value_6():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_status(returncode=-1, passed=-1)
    assert result == "tests_failed"
