# detective-content-sha256: dbf68ab7756404f5af1472b7d170748ce1fdd7cdcdac179cfb925220ee30e344
"""Auto-generated by Detective — warrant-classed tests for Detective/plan.py::unexamined.
Function digest: c57cba4cc69944da.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.plan import unexamined


@pytest.mark.detective
def test_unexamined_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = unexamined(fences_note="abc", template_count=1)
    assert result == (
        "what this plan did not propose is UNEXAMINED, not approved",
        "regime — unread: it needs a live mutation profile this static plan never runs",
        "abc",
        "recognizers — 1 template(s); a region with no match is a library gap, not a clean bill",
    )
