"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::receipt_refusal.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import receipt_refusal


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("abc", "abc", "abc", "abc", "abc"),
            "unrecognized receipt schema 'abc' (expected 'detective-rewrite-receipt/1')",
        ),
        (
            ("detective-rewrite-receipt/1", "x", "wrongdigest", "a.py::a", "a.py::a"),
            "receipt source digest does not match its recorded source — corrupt or tampered receipt",
        ),
        (
            (
                "detective-rewrite-receipt/1",
                "x",
                "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881",
                "a.py::a",
                "b.py::b",
            ),
            "receipt is for 'a.py::a', but verification was requested for 'b.py::b' — a receipt binds to exactly one function",
        ),
    ],
)
def test_receipt_refusal_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert receipt_refusal(*args) == expected


@pytest.mark.detective
def test_receipt_refusal_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = receipt_refusal(
        schema="detective-rewrite-receipt/1",
        original_source="x",
        source_digest="2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881",
        receipt_function="a.py::a",
        requested_key="a.py::a",
    )
    assert result is None
