"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/oracle_light.py::property_id.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.oracle_light import property_id


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("m.py::f", "VALUE", "x = 1", "assert f(x) == 2", "(1,)", "", "VALUE_abc"), "e96b0ff75f9cd807"),
        (("abc", "abc", "abc", "abc", "abc", "abc", "abc"), "14bb9edc225be440"),
    ],
)
def test_property_id_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert property_id(*args) == expected
