"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_purity_vote.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _purity_vote


@pytest.mark.detective
def test__purity_vote_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _purity_vote(pure=True)
    assert result == 1


@pytest.mark.detective
def test__purity_vote_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _purity_vote(pure=False)
    assert result == 0
