# detective-content-sha256: 60f95b93b36a214f61f1b6e6c649120863660514358792b433411801c75b237c
"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::golden_observation_scope.
Function digest: aec73fe1483cd6ef.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import golden_observation_scope


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, "numpy 2.4.6"), "platform_specific"),
        ((True, ""), "platform_independent"),
    ],
)
def test_golden_observation_scope_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert golden_observation_scope(*args) == expected
