# detective-content-sha256: 2214d20c4c2930f23b50c51988d396584eb03f6fdd820692af5f7625ac54521e
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::plugin_presence.
Function digest: 62c60d3489957b60.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.cli import plugin_presence


@pytest.mark.detective
def test_plugin_presence_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = plugin_presence(plugin="abc", installed_here=True)
    assert result == "present"


@pytest.mark.detective
def test_plugin_presence_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = plugin_presence(plugin="", installed_here=False)
    assert result == "unnamed"
