"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::basis_freshness.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import basis_freshness


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"x": "x"}, {"x": "x"}), "fresh"),
        (({}, {}), "unfrozen"),
        (({"a.py": "x"}, {"a.py": "y"}), "moved"),
        (({"a.py": "x"}, {"a.py": "x"}), "fresh"),
    ],
)
def test_basis_freshness_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert basis_freshness(*args) == expected
