"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_agreement.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _agreement


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (((1,),), 0),
        (((-1, 0, 1, -1),), 2),
    ],
)
def test__agreement_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _agreement(*args) == expected
