# detective-content-sha256: 2a1bb337bf86ae063137408de09b0deaf327273dbc985b44e8efeb3f3d744815
"""Auto-generated by Detective — warrant-classed tests for Detective/distinction.py::distinction_disposition.
Function digest: 23a287f4c6c4b9c4.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.distinction import distinction_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["x"], ["x"], True, "abc"), "collapse_stale"),
        ((["a", "b", "c"], ["a"], False, ""), "collapses"),
    ],
)
def test_distinction_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert distinction_disposition(*args) == expected


@pytest.mark.detective
def test_distinction_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = distinction_disposition(codes=[], distinguished=["x"], forwards=False, collapse_reason="")
    assert result == "phantom_code"


@pytest.mark.detective
def test_distinction_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = distinction_disposition(
        codes=["x", "x"], distinguished=["x", "x"], forwards=False, collapse_reason="abc"
    )
    assert result == "collapse_stale"


@pytest.mark.detective
def test_distinction_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = distinction_disposition(
        codes=["x", "x"], distinguished=[], forwards=False, collapse_reason="abc"
    )
    assert result == "collapse_declared"


@pytest.mark.detective
def test_distinction_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = distinction_disposition(codes=[], distinguished=[], forwards=False, collapse_reason="")
    assert result == "distinguishes_all"
