"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::env_covers.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.capabilities import env_covers


@pytest.mark.detective
def test_env_covers_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = env_covers(reason="reads process env via os.environ")
    assert result is True


@pytest.mark.detective
def test_env_covers_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = env_covers(reason="reads the clock via time.time()")
    assert result is False
