# detective-content-sha256: 2415189ca1974f5a4b4b97335710250cd386ae7f641bdfe4e213293db4129589
"""Auto-generated by Detective — warrant-classed tests for Detective/atomic_store.py::store_read_disposition.
Function digest: dad11c45c66853a1.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.atomic_store import store_read_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((False, False, False, False), "absent"),
        ((True, False, False, False), "unreadable"),
        ((True, True, True, True), "readable"),
    ],
)
def test_store_read_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert store_read_disposition(*args) == expected


@pytest.mark.detective
def test_store_read_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = store_read_disposition(exists=True, read_ok=True, parsed=False, is_mapping=True)
    assert result == "corrupt"
