"""Auto-generated by Detective — warrant-classed tests for Detective/certify.py::witness_origin.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.certify import witness_origin


@pytest.mark.detective
def test_witness_origin_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = witness_origin(authorship="abc", edited=True)
    assert result == "intent"


@pytest.mark.detective
def test_witness_origin_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = witness_origin(authorship="unreadable", edited=False)
    assert result == "unattributed"


@pytest.mark.detective
def test_witness_origin_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = witness_origin(authorship="hand_written", edited=False)
    assert result == "intent"


@pytest.mark.detective
def test_witness_origin_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = witness_origin(authorship="", edited=False)
    assert result == "characterization"
