"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::install_extra_target.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import install_extra_target


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["test"],), ".[test]"),
        ((["tests"],), ".[tests]"),
        ((["testing"],), ".[testing]"),
        ((["dev"],), ".[dev]"),
        ((["develop"],), ".[develop]"),
        ((["development"],), ".[development]"),
        ((["game"],), "."),
    ],
)
def test_install_extra_target_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert install_extra_target(*args) == expected
