# detective-content-sha256: 22ce3b97eca89a4632a022adbd6dc7991a393d6e65aafb4711fb2f4c2e558f49
"""Auto-generated by Detective — warrant-classed tests for Detective/censor.py::learn_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.censor import learn_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("CHANGED", True), "learn"),
        (("CHANGED", False), "skip_disabled"),
        (("PRESERVED", True), "skip_unchanged"),
    ],
)
def test_learn_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert learn_disposition(*args) == expected
