"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::clock_freezes.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.capabilities import clock_freezes


@pytest.mark.detective
def test_clock_freezes_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = clock_freezes(clock=1.0625)
    assert result == [
        ("time", 1.0625),
        ("monotonic", 1.0625),
        ("perf_counter", 1.0625),
        ("time_ns", 1062500000),
        ("monotonic_ns", 1062500000),
    ]


@pytest.mark.detective
def test_clock_freezes_value_1():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = clock_freezes(clock=-1.0)
    assert result == [
        ("time", -1.0),
        ("monotonic", -1.0),
        ("perf_counter", -1.0),
        ("time_ns", -1000000000),
        ("monotonic_ns", -1000000000),
    ]
    assert type(result[3][1]) is int
    assert type(result[4][1]) is int
