# detective-content-sha256: 8dc9d82f2e3b3877472cb27d189c4435956f0562aba9cd60cb2b403b2f7e910b
"""Auto-generated by Detective — warrant-classed tests for Detective/ledger.py::suite_state_comparison.
Function digest: d3a106f4c64026b3.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.ledger import suite_state_comparison


@pytest.mark.detective
def test_suite_state_comparison_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = suite_state_comparison(cheap_same=True, both_exact=True, exact_same=True)
    assert result == "unchanged_exact"


@pytest.mark.detective
def test_suite_state_comparison_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = suite_state_comparison(cheap_same=True, both_exact=False, exact_same=False)
    assert result == "unchanged_cheap"


@pytest.mark.detective
def test_suite_state_comparison_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = suite_state_comparison(cheap_same=False, both_exact=False, exact_same=False)
    assert result == "unknown"


@pytest.mark.detective
def test_suite_state_comparison_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = suite_state_comparison(cheap_same=False, both_exact=True, exact_same=False)
    assert result == "changed_exact"
