# detective-content-sha256: 23c7a5570a3e5ef544fdf9f2d88f04e0889c55a9dbc956e28ae3699609ed24b5
"""Auto-generated by Detective — warrant-classed tests for Detective/validity.py::cut_reason_sentence.
Function digest: 9b6852d884447520.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.validity import cut_reason_sentence


@pytest.mark.detective
def test_cut_reason_sentence_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = cut_reason_sentence(reason="some_future_reason")
    assert result == "an unrecognised engine refusal (some_future_reason)"
