# detective-content-sha256: d8039c1269d43fb6b94131dfc3737f98d1b38cb7103c311f3dbbc7684e7b3ac2
"""Auto-generated by Detective — warrant-classed tests for Detective/validity.py::measurement_cut_reasons.
Function digest: 053fbac463dfa852.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.validity import measurement_cut_reasons


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            (True, False, False, "exhaustive", "contained", False, False, True),
            ("mutant_construction_failed",),
        ),
        (
            (True, True, True, "abc", "abc", True, True, True, True, True, True),
            (
                "target_load_failed",
                "budget_exhausted",
                "collection_incomplete",
                "ambiguous_module_identity",
                "mutant_construction_failed",
                "mutant_not_installed",
                "mutant_not_entered",
            ),
        ),
    ],
)
def test_measurement_cut_reasons_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert measurement_cut_reasons(*args) == expected
