"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::rescue_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.engine import rescue_disposition


@pytest.mark.detective
def test_rescue_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = rescue_disposition(expressible=True, rescuable=True, has_inexpressible_witness=True)
    assert result == "run"


@pytest.mark.detective
def test_rescue_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rescue_disposition(expressible=False, rescuable=False, has_inexpressible_witness=False)
    assert result == "nothing"


@pytest.mark.detective
def test_rescue_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rescue_disposition(expressible=True, rescuable=True, has_inexpressible_witness=False)
    assert result == "skip_ask_input"
