"""Auto-generated by Detective — warrant-classed tests for Detective/certify.py::verify_timeout_s.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.certify import verify_timeout_s


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1.0625, 1.0625), 1.0625),
        ((None, 120.0), 120.0),
        ((-5.0, 120.0), 0.0),
        ((0.05, 120.0), 0.05),
    ],
)
def test_verify_timeout_s_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert verify_timeout_s(*args) == expected


@pytest.mark.detective
def test_verify_timeout_s_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = verify_timeout_s(remaining_s=0, cap_s=-1.0)
    assert result == 0.0


@pytest.mark.detective
def test_verify_timeout_s_value_1():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = verify_timeout_s(remaining_s=1, cap_s=1.0)
    assert result == 1.0
    assert type(result) is float
