# detective-content-sha256: 435290a1c8a07b625502192d82b462f12154e7d654eebd62aec3210f81be2a89
"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::clock_covers.
Function digest: 12801440d9fb6e27.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.capabilities import clock_covers


@pytest.mark.detective
def test_clock_covers_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = clock_covers(reason="abc")
    assert result is False
