"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::receipt_load_refusal.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import receipt_load_refusal


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", "abc"), "malformed_json"),
        (("not json at all", "v1"), "malformed_json"),
        (("[1, 2]", "v1"), "not_an_object"),
        (("{}", "v1"), "missing_schema"),
        (('{"schema": "other"}', "v1"), "unknown_schema"),
        (('{"schema": "v1"}', "v1"), "bad_fields"),
        (('{"schema": "v1", "original_source": "x", "source_digest": "deadbeef"}', "v1"), "digest_mismatch"),
        (
            (
                '{"schema": "v1", "original_source": "x", "source_digest": "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881"}',
                "v1",
            ),
            "",
        ),
    ],
)
def test_receipt_load_refusal_golden(args, expected):
    """VALUE golden captures — pure + deterministic (8 inputs)."""
    assert receipt_load_refusal(*args) == expected
