"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::basis_action.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.engine import basis_action


@pytest.mark.detective
def test_basis_action_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = basis_action(admits_certificate=True, has_open_obligations=True)
    assert result == "gap"


@pytest.mark.detective
def test_basis_action_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = basis_action(admits_certificate=False, has_open_obligations=False)
    assert result == "unresolved"


@pytest.mark.detective
def test_basis_action_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = basis_action(admits_certificate=True, has_open_obligations=False)
    assert result == "complete"
