"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::_pyproject_pytest_section.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.regime import _pyproject_pytest_section


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("[tool.pytest.ini_options]\nx = 1\n",), "[tool.pytest.ini_options]"),
        (("[tool.pytest]\nmarkers = []\n",), "[tool.pytest]"),
    ],
)
def test__pyproject_pytest_section_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _pyproject_pytest_section(*args) == expected


@pytest.mark.detective
def test__pyproject_pytest_section_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _pyproject_pytest_section(source="abc")
    assert result is None


@pytest.mark.detective
def test__pyproject_pytest_section_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _pyproject_pytest_section(source="[tool.pytest.ini_options]\n")
    assert result == "[tool.pytest.ini_options]"


@pytest.mark.detective
def test__pyproject_pytest_section_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _pyproject_pytest_section(source="")
    assert result is None


@pytest.mark.detective
def test__pyproject_pytest_section_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _pyproject_pytest_section(source="[tool.pytest]\n")
    assert result is None
