# detective-content-sha256: a0ea022c7f723f3fd78ac56f1be8ecf2cbb677c5190e1fcd0f889a83a60e359e
"""Auto-generated by Detective — warrant-classed tests for Detective/kappa.py::call_graph_neighbors.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.kappa import call_graph_neighbors


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"a": {"b"}, "b": {"c"}}, "b"), {"c", "a"}),
        (({"a": {"b"}}, "c"), set()),
    ],
)
def test_call_graph_neighbors_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert call_graph_neighbors(*args) == expected
