# detective-content-sha256: c40d6c01c702d7446d1b1d90379d0dd974ee09f401135d423d0f6623d87a39b9
"""Auto-generated by Detective — warrant-classed tests for Detective/consumption.py::consumption_disposition.
Function digest: a6362f174311a027.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.consumption import consumption_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, 2, "abc"), "exemption_stale"),
        ((1, 0, ""), "consumed"),
        ((0, 0, "a reason"), "exempt_declared"),
        ((0, 1, ""), "pinned_unconsumed"),
        ((0, 0, ""), "unreferenced"),
    ],
)
def test_consumption_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert consumption_disposition(*args) == expected
