"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::rewrite_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import rewrite_verdict


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((False, True, True, 0, 0, 0), "ABSTAIN"),
        ((True, False, True, 0, 0, 0), "ABSTAIN"),
        ((True, True, False, 0, 0, 0), "CHANGED"),
        ((True, True, True, 1, 0, 0), "UNREVIEWED"),
        ((True, True, True, 0, 1, 0), "CHANGED"),
        ((True, True, True, 0, 0, 1), "ABSTAIN"),
        ((True, True, True, 0, 0, 0), "PRESERVED"),
    ],
)
def test_rewrite_verdict_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert rewrite_verdict(*args) == expected
