# detective-content-sha256: f14efc1ead4348d263525bd53790c23ef9b4e660ae17ad684d196fc677753b81
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::audit_next_action.
Function digest: b8e488fc2cee7ade.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import audit_next_action


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", True, 1, 2, 3, True, 4, True, 5), "fix_failing_test"),
        (("", False, 0, 0, 0, False, 2, True, 0), "flag_equivalents"),
        (("", False, 0, 0, 0, False, 0, False, 3), "done_unclassified"),
        (("", False, 0, 0, 0, False, 0, False, 0), "done_complete"),
    ],
)
def test_audit_next_action_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert audit_next_action(*args) == expected


@pytest.mark.detective
def test_audit_next_action_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="fix_load",
        has_failing_tests=False,
        killable_gaps=-1,
        missing_lines=-1,
        redundant_tests=-1,
        removing=False,
        candidate_equivalent=-1,
        has_equivalent_ids=False,
        unclassified=-1,
    )
    assert result == "fix_load"


@pytest.mark.detective
def test_audit_next_action_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="a",
        has_failing_tests=False,
        killable_gaps=-1,
        missing_lines=0,
        redundant_tests=1,
        removing=False,
        candidate_equivalent=3,
        has_equivalent_ids=False,
        unclassified=0,
    )
    assert result == "remove_redundant"


@pytest.mark.detective
def test_audit_next_action_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="abc",
        has_failing_tests=False,
        killable_gaps=2,
        missing_lines=-1,
        redundant_tests=1,
        removing=False,
        candidate_equivalent=0,
        has_equivalent_ids=False,
        unclassified=-1,
    )
    assert result == "close_the_gap"


@pytest.mark.detective
def test_audit_next_action_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="",
        has_failing_tests=False,
        killable_gaps=0,
        missing_lines=2,
        redundant_tests=-1,
        removing=False,
        candidate_equivalent=3,
        has_equivalent_ids=False,
        unclassified=2,
    )
    assert result == "close_the_gap"


@pytest.mark.detective
def test_audit_next_action_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="",
        has_failing_tests=False,
        killable_gaps=0,
        missing_lines=0,
        redundant_tests=0,
        removing=False,
        candidate_equivalent=1,
        has_equivalent_ids=False,
        unclassified=3,
    )
    assert result == "done_unclassified"


@pytest.mark.detective
def test_audit_next_action_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="",
        has_failing_tests=False,
        killable_gaps=1,
        missing_lines=0,
        redundant_tests=0,
        removing=False,
        candidate_equivalent=2,
        has_equivalent_ids=True,
        unclassified=0,
    )
    assert result == "close_the_gap"


@pytest.mark.detective
def test_audit_next_action_value_6():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="",
        has_failing_tests=False,
        killable_gaps=0,
        missing_lines=1,
        redundant_tests=0,
        removing=False,
        candidate_equivalent=2,
        has_equivalent_ids=True,
        unclassified=0,
    )
    assert result == "close_the_gap"


@pytest.mark.detective
def test_audit_next_action_value_7():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="",
        has_failing_tests=False,
        killable_gaps=0,
        missing_lines=0,
        redundant_tests=0,
        removing=False,
        candidate_equivalent=1,
        has_equivalent_ids=True,
        unclassified=0,
    )
    assert result == "flag_equivalents"


@pytest.mark.detective
def test_audit_next_action_value_8():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_next_action(
        block="",
        has_failing_tests=False,
        killable_gaps=0,
        missing_lines=0,
        redundant_tests=0,
        removing=False,
        candidate_equivalent=0,
        has_equivalent_ids=False,
        unclassified=1,
    )
    assert result == "done_unclassified"
