# detective-content-sha256: a9dc22b0c3fe4e9edafc8f900f0d7458a9a5906578d27adccb2855452aafba0a
"""Auto-generated by Detective — warrant-classed tests for Detective/validity.py::cut_reason_sentence.
Function digest: 47a344fbca257c41.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.validity import cut_reason_sentence


@pytest.mark.detective
def test_cut_reason_sentence_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = cut_reason_sentence(reason="some_future_reason")
    assert result == "an unrecognised engine refusal (some_future_reason)"
