"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::reconcile_config_file.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.regime import reconcile_config_file


@pytest.mark.detective
def test_reconcile_config_file_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = reconcile_config_file(static_rel="abc", live_rel="abc")
    assert result == ("abc", "")


@pytest.mark.detective
def test_reconcile_config_file_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reconcile_config_file(static_rel="", live_rel="a")
    assert result == (
        "a",
        "config resolution diverged — the precedence mirror picked <none>, but pytest reads a; registering into pytest's (this repo's config is non-standard)",
    )


@pytest.mark.detective
def test_reconcile_config_file_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reconcile_config_file(static_rel="", live_rel="")
    assert result == ("", "")
