# detective-content-sha256: 267cd84e1f58a07dfe9c2d7a936d2c801bd36fb689db03e9751034dc1ca2fd59
"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::boundary_probe_gate.
Function digest: d391705ab013af39.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.engine import boundary_probe_gate


@pytest.mark.detective
def test_boundary_probe_gate_value_0():
    """VALUE survivor — golden capture (pure + deterministic)."""
    result = boundary_probe_gate(residual=1, has_effects=True, expressible=True, wall_exhausted=True)
    assert result == "skip_effects"


@pytest.mark.detective
def test_boundary_probe_gate_value_1():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = boundary_probe_gate(residual=-1, has_effects=False, expressible=False, wall_exhausted=False)
    assert result == "skip_no_residual"
