"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_cohesion_vote.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _cohesion_vote


@pytest.mark.detective
def test__cohesion_vote_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _cohesion_vote(n_components=1)
    assert result == 1


@pytest.mark.detective
def test__cohesion_vote_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _cohesion_vote(n_components=-1)
    assert result == -1


@pytest.mark.detective
def test__cohesion_vote_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _cohesion_vote(n_components=0)
    assert result == 0
