"""Auto-generated by Detective — warrant-classed tests for Detective/adequacy.py::bucket_is_finding.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.adequacy import bucket_is_finding


@pytest.mark.detective
def test_bucket_is_finding_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bucket_is_finding(bucket="abc")
    assert result is False


@pytest.mark.detective
def test_bucket_is_finding_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = bucket_is_finding(bucket="undetected")
    assert result is True
