"""Auto-generated by Detective — warrant-classed tests for Detective/verdict_cache.py::_retyped_trace_row.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.verdict_cache import _retyped_trace_row


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({},), {}),
        (
            ({"test_id": "t", "lines": [1, 2], "arcs": [[1, 2], [3, 4]], "reason": "r"},),
            {"test_id": "t", "lines": (1, 2), "arcs": ((1, 2), (3, 4)), "reason": "r"},
        ),
        (({"test_id": "t", "bogus": 9, "lines": [5]},), {"test_id": "t", "lines": (5,)}),
    ],
)
def test__retyped_trace_row_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _retyped_trace_row(*args) == expected
