# detective-content-sha256: cb3e95d5754c90ee095278a082c5d26bf572ac3730062584a07be74ccfcc96bb
"""Auto-generated by Detective — warrant-classed tests for Detective/certificates.py::certificate_cut_reasons.
Function digest: 619a9ee8d2df868e.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.certificates import certificate_cut_reasons


@pytest.mark.detective
def test_certificate_cut_reasons_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = certificate_cut_reasons(standing="abc", cut_reasons=("x",))
    assert result == ("x",)


@pytest.mark.detective
def test_certificate_cut_reasons_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = certificate_cut_reasons(standing="ungateable", cut_reasons=("x",))
    assert result == ("x",)
