"""Auto-generated by Detective — warrant-classed tests for Detective/converge.py::line_proof_basis.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.converge import line_proof_basis


@pytest.mark.detective
def test_line_proof_basis_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = line_proof_basis(has_admissible=True, engine_reports_it=True)
    assert result == "admissible"


@pytest.mark.detective
def test_line_proof_basis_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = line_proof_basis(has_admissible=False, engine_reports_it=False)
    assert result == "observed"


@pytest.mark.detective
def test_line_proof_basis_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = line_proof_basis(has_admissible=False, engine_reports_it=True)
    assert result == "none_admissible"
