# detective-content-sha256: 3c98131757ca258554a13f79cab7c54bffa8c9fda13af5288da7ef43f5af1dda
"""Auto-generated by Detective — warrant-classed tests for Detective/atomic_store.py::store_write_disposition.
Function digest: 7dd509d7e64e8513.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.atomic_store import store_write_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("abc", True), "refuse_unreadable"),
        (("absent", False), "write"),
        (("corrupt", True), "write"),
    ],
)
def test_store_write_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert store_write_disposition(*args) == expected
