"""Auto-generated by Detective — warrant-classed tests for Detective/certify.py::write_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.certify import write_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((True, "other.py::f", "mine.py::f"), "refuse_foreign"),
        ((True, "", "mine.py::f"), "refuse_unowned"),
        ((True, "abc", "abc"), "write"),
    ],
)
def test_write_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert write_disposition(*args) == expected
