"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::machine_specific_probe_hit.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import machine_specific_probe_hit


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("/Users/me/proj/data", ("/Users/me",)), "/Users/me"),
        (("/etc/hosts", ("/Users/me",)), ""),
        (("anything", ()), ""),
        (("/a", ("/a",)), ""),
        (("xx", ("",)), ""),
        (("/tmp/x/y", ("/nope", "/tmp/x")), "/tmp/x"),
        (("", ("/Users/me",)), ""),
        (("abc", ("x",)), ""),
    ],
)
def test_machine_specific_probe_hit_golden(args, expected):
    """VALUE golden captures — pure + deterministic (8 inputs)."""
    assert machine_specific_probe_hit(*args) == expected
