# detective-content-sha256: 2aabf3f69aecef0b43fc6dc12934331251dfc86961add2f030ff10dd5a3b214c
"""Auto-generated by Detective — warrant-classed tests for Detective/binding.py::classify_target.
Function digest: b23ec4f2f66218df.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import ast

import pytest

from Detective.binding import classify_target


@pytest.mark.detective
def test_classify_target_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_target(
        tree=ast.parse(
            "def _f(x, y):\n    total = x + y\n    total = abs(total)\n    if total > 10:\n        raise ValueError('big')\n    return round(total, 2)"
        ),
        qualname="abc",
    )
    assert (
        repr(result)
        == "TargetBinding(kind=<BindingKind.UNSUPPORTED: 'unsupported'>, owner='', attribute='abc', receiver_params=0)"
    )


@pytest.mark.detective
def test_classify_target_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = classify_target(tree=ast.parse("x = 1"), qualname="abc")
    assert (
        repr(result)
        == "TargetBinding(kind=<BindingKind.UNSUPPORTED: 'unsupported'>, owner='', attribute='abc', receiver_params=0)"
    )
