"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::eta_seconds.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import eta_seconds


@pytest.mark.detective
def test_eta_seconds_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = eta_seconds(done=1, total=2, elapsed_ms=1.0625, anchor_done=3, anchor_ms=1.0625)
    assert result is None


@pytest.mark.detective
def test_eta_seconds_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = eta_seconds(done=1, total=2, elapsed_ms=1.0625, anchor_done=-1, anchor_ms=0.0)
    assert result == 0.00053125


@pytest.mark.detective
def test_eta_seconds_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = eta_seconds(done=3, total=-1, elapsed_ms=0.0, anchor_done=1, anchor_ms=2.5)
    assert result is None


@pytest.mark.detective
def test_eta_seconds_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = eta_seconds(done=2, total=3, elapsed_ms=-1.0, anchor_done=0, anchor_ms=1.0)
    assert result == 0.0
