# detective-content-sha256: 91a307bc5c8e0954eb4ced5800b7ba04bae06ca205d6f535273bd7d7f6d96352
"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::float_spelling.
Function digest: a6191cfabec70d99.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.equivalence import float_spelling


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((float("nan"),), "nan"),
        ((float("-inf"),), "-inf"),
        ((float("inf"),), "inf"),
        ((1.0625,), "finite"),
    ],
)
def test_float_spelling_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert float_spelling(*args) == expected
