"""Auto-generated by Detective — warrant-classed tests for Detective/capabilities.py::capability_identity.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.capabilities import capability_identity


@pytest.mark.detective
def test_capability_identity_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = capability_identity(clock=1.0625)
    assert result == "clock=1.0625"
