# detective-content-sha256: 9f2ae8368349aa3590d90f40eb33388bc6bfd7cd217bde642ae2f0c805d4d85e
"""Auto-generated by Detective — warrant-classed tests for Detective/ledger.py::order_disposition.
Function digest: 82f615f042e747ba.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.ledger import order_disposition


@pytest.mark.detective
def test_order_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = order_disposition(command_herb="abc", target_ever_pinned=True, target_has_prior_measurement=True)
    assert result == "ok"


@pytest.mark.detective
def test_order_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = order_disposition(
        command_herb="yellow", target_ever_pinned=False, target_has_prior_measurement=False
    )
    assert result == "taste_without_measurement"


@pytest.mark.detective
def test_order_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = order_disposition(command_herb="", target_ever_pinned=False, target_has_prior_measurement=False)
    assert result == "ok"


@pytest.mark.detective
def test_order_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = order_disposition(
        command_herb="yellow", target_ever_pinned=False, target_has_prior_measurement=True
    )
    assert result == "taste_before_behaviour"


@pytest.mark.detective
def test_order_disposition_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = order_disposition(
        command_herb="yellow", target_ever_pinned=True, target_has_prior_measurement=True
    )
    assert result == "ok"
