"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::rate_label.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import rate_label


@pytest.mark.detective
def test_rate_label_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = rate_label(done=1, elapsed_ms=1.0625)
    assert result == "941.2/s"


@pytest.mark.detective
def test_rate_label_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rate_label(done=1, elapsed_ms=-1.0)
    assert result == "…"


@pytest.mark.detective
def test_rate_label_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rate_label(done=-1, elapsed_ms=1.0)
    assert result == "…"


@pytest.mark.detective
def test_rate_label_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rate_label(done=1, elapsed_ms=0.0)
    assert result == "…"


@pytest.mark.detective
def test_rate_label_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = rate_label(done=0, elapsed_ms=1.0)
    assert result == "…"
