# detective-content-sha256: bbb5e8b2c58c32e09e6151435b8ecd699700d55a45314bd83202279ee894bbe8
"""Auto-generated by Detective — warrant-classed tests for Detective/extract.py::extract_readiness.
Function digest: c4653880217a7167.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.extract import extract_readiness


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("reachable", False), "reachable"),
        (("trapped_by_imports", True), "move"),
        (("extractable_core", True), "propose"),
        (("extractable_core", False), "no_primitive_seam"),
    ],
)
def test_extract_readiness_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert extract_readiness(*args) == expected
