"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::pytest_honors_bare_tool_pytest.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.regime import pytest_honors_bare_tool_pytest


@pytest.mark.detective
def test_pytest_honors_bare_tool_pytest_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = pytest_honors_bare_tool_pytest(version="abc")
    assert result is False


@pytest.mark.detective
def test_pytest_honors_bare_tool_pytest_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = pytest_honors_bare_tool_pytest(version="")
    assert result is False


@pytest.mark.detective
def test_pytest_honors_bare_tool_pytest_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = pytest_honors_bare_tool_pytest(version="9.0.0")
    assert result is True


@pytest.mark.detective
def test_pytest_honors_bare_tool_pytest_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = pytest_honors_bare_tool_pytest(version="8.3.3")
    assert result is False
