"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony_map.py::_group_rank.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony_map import _group_rank


@pytest.mark.detective
def test__group_rank_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _group_rank(max_smells=1, flagged_count=2)
    assert result == (-1, -2)
