"""Auto-generated by Detective — warrant-classed tests for Detective/suite_edit.py::nodeid_function_name.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.suite_edit import nodeid_function_name


@pytest.mark.detective
def test_nodeid_function_name_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = nodeid_function_name(identifier="legacy:a.py::t_two[x]")
    assert result == "t_two"
