# detective-content-sha256: 873cb0bb5a05c460240940ae708ffaa9dcb712d447b160acaa5a9fec2f053989
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::residual_done_basis.
Function digest: b25d62efe889d068.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose."""

import pytest

from Detective.cli import residual_done_basis


@pytest.mark.detective
def test_residual_done_basis_value_0():
    """VALUE survivor — distinguishing witness (equivalence search)."""
    result = residual_done_basis(candidate_equivalent=-1, crash_only=-1, boundary_probe="run")
    assert result == "none"
