"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_seam_vote.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _seam_vote


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1,), -1),
        ((0,), 1),
    ],
)
def test__seam_vote_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _seam_vote(*args) == expected


@pytest.mark.detective
def test__seam_vote_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _seam_vote(n_seams=2)
    assert result == -1
