"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::open_is_write.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import open_is_write


@pytest.mark.detective
def test_open_is_write_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = open_is_write(mode=1, flags=1)
    assert result is True


@pytest.mark.detective
def test_open_is_write_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = open_is_write(mode="w", flags=0)
    assert result is True


@pytest.mark.detective
def test_open_is_write_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = open_is_write(mode="r", flags=0)
    assert result is False


@pytest.mark.detective
def test_open_is_write_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = open_is_write(mode=123, flags="x")
    assert result is False
