# detective-content-sha256: 2eac53d71f347b5e10e59b2a27c8e9a573140f2d4e55dac7666632d01c70d938
"""Auto-generated by Detective — warrant-classed tests for Detective/ledger.py::environment_drift_disposition.
Function digest: 4fffb949cc24ccd6.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.ledger import environment_drift_disposition


@pytest.mark.detective
def test_environment_drift_disposition_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = environment_drift_disposition(
        has_prior=True, same_interpreter=True, same_engine_paths=True, same_version=True
    )
    assert result == "stable"


@pytest.mark.detective
def test_environment_drift_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = environment_drift_disposition(
        has_prior=False, same_interpreter=False, same_engine_paths=False, same_version=False
    )
    assert result == "no_prior"


@pytest.mark.detective
def test_environment_drift_disposition_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = environment_drift_disposition(
        has_prior=True, same_interpreter=False, same_engine_paths=False, same_version=False
    )
    assert result == "interpreter_changed"


@pytest.mark.detective
def test_environment_drift_disposition_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = environment_drift_disposition(
        has_prior=True, same_interpreter=True, same_engine_paths=False, same_version=False
    )
    assert result == "engine_changed"


@pytest.mark.detective
def test_environment_drift_disposition_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = environment_drift_disposition(
        has_prior=True, same_interpreter=True, same_engine_paths=True, same_version=False
    )
    assert result == "version_changed"
