# detective-content-sha256: 72bb82b289a35e8d3aa592ac6006d90ef101c55420ee5c7fb8b66b4d106dc39b
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::exit_code_meaning.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import exit_code_meaning


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((0,), "clean"),
        ((1,), "gap_or_refusal"),
        ((2,), "conflict_or_precondition"),
        ((3,), "invalid_measurement_rerun"),
        ((5,), "unknown"),
    ],
)
def test_exit_code_meaning_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert exit_code_meaning(*args) == expected
