# detective-content-sha256: 079d94a6cf1802bd7eef92ca938095a314a0e48a6f748685fa163a5ac26f55d8
"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/typed_synthesis.py::_extract.
Function digest: 7cd9190bc2dabe35.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import ast

import pytest

from Detective.synthesis.typed_synthesis import _extract


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((ast.parse("1 + 1").body[0].value,), ("", [])),
        ((ast.parse("a < b").body[0].value,), ("", [])),
    ],
)
def test__extract_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _extract(*args) == expected


@pytest.mark.detective
def test__extract_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _extract(node=ast.parse("typing.Any").body[0].value)
    assert result == ("Any", [])


@pytest.mark.detective
def test__extract_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _extract(node=ast.parse("None").body[0].value)
    assert result == ("None", [])


@pytest.mark.detective
def test__extract_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _extract(node=ast.parse("0").body[0].value)
    assert result == ("", [])


@pytest.mark.detective
def test__extract_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _extract(node=ast.parse("int + str").body[0].value)
    assert result == ("", [])


@pytest.mark.detective
def test__extract_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _extract(node=ast.parse("int | None").body[0].value)
    assert result == ("int", [])


@pytest.mark.detective
def test__extract_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _extract(node=ast.parse("None | str").body[0].value)
    assert result == ("str", [])
