"""Auto-generated by Detective — warrant-classed tests for Detective/converge.py::admissible_line_owners.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.converge import admissible_line_owners


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["x"], "abc"), ()),
        ((["b", "a"], "admissible"), ("a", "b")),
    ],
)
def test_admissible_line_owners_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert admissible_line_owners(*args) == expected


@pytest.mark.detective
def test_admissible_line_owners_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = admissible_line_owners(owner_ids=["x", "x"], line_basis="admissible")
    assert result == ("x",)
