"""Auto-generated by Detective — warrant-classed tests for Detective/audit.py::audit_gate_exit.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.audit import audit_gate_exit


@pytest.mark.detective
def test_audit_gate_exit_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = audit_gate_exit(spec_gap=True, measurement_incomplete=True, strict=True)
    assert result == 1


@pytest.mark.detective
def test_audit_gate_exit_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_gate_exit(spec_gap=False, measurement_incomplete=False, strict=True)
    assert result == 0


@pytest.mark.detective
def test_audit_gate_exit_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_gate_exit(spec_gap=False, measurement_incomplete=True, strict=True)
    assert result == 2
