"""Auto-generated by Detective — warrant-classed tests for Detective/parsimony.py::_complexity_vote.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.parsimony import _complexity_vote


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1,), 1),
        ((20,), -1),
        ((10,), 0),
    ],
)
def test__complexity_vote_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _complexity_vote(*args) == expected
