# detective-content-sha256: 528a52d37952d2d46fc8332c2d6455dc91553305edc874501a14cadb59f3086d
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::line_gap_rationale.
Function digest: 2cbb8cd2939a9b50.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import line_gap_rationale


@pytest.mark.detective
def test_line_gap_rationale_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = line_gap_rationale(unclassified=1, killable=2)
    assert result == "classification_incomplete"


@pytest.mark.detective
def test_line_gap_rationale_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = line_gap_rationale(unclassified=0, killable=-1)
    assert result == "every_killable_dead"


@pytest.mark.detective
def test_line_gap_rationale_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = line_gap_rationale(unclassified=-1, killable=0)
    assert result == "every_killable_dead"


@pytest.mark.detective
def test_line_gap_rationale_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = line_gap_rationale(unclassified=-1, killable=1)
    assert result == "killable_remain"
