# detective-content-sha256: 4e5caa47df90bf1dfb222ddc684a206fbd382f327b3c8db47c5085f414397c79
"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::float_bearing.
Function digest: 6a0afd721517709f.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.synthesis.characterization import float_bearing


@pytest.mark.detective
def test_float_bearing_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = float_bearing(value=1.5)
    assert result is True


@pytest.mark.detective
def test_float_bearing_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = float_bearing(value=True)
    assert result is False


@pytest.mark.detective
def test_float_bearing_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = float_bearing(value=3)
    assert result is False


@pytest.mark.detective
def test_float_bearing_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = float_bearing(value=[1, 2.5])
    assert result is True


@pytest.mark.detective
def test_float_bearing_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = float_bearing(value={"a": 1.0})
    assert result is True


@pytest.mark.detective
def test_float_bearing_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = float_bearing(value=(1, 2))
    assert result is False
