# detective-content-sha256: db54ff76fba9a3e90205424288b04714db6d3048d88f3ea340b85596db924bb0
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::line_gap_why.
Function digest: bf8633b59fe1c7da.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import line_gap_why


@pytest.mark.detective
def test_line_gap_why_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = line_gap_why(rationale="abc")
    assert result == "unrecognised rationale: abc"
