# detective-content-sha256: 60309ebaf28ea0fce9244e342a346220549ea1dd299753cea300cd87c3622775
"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::guard_comparison_target.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.engine import guard_comparison_target


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((">", 5), 6),
        (("<", 5), 4),
        ((">=", 5), 5),
        (("==", 5), 5),
        (("!=", 5), 6),
        (("<=", 5), 5),
    ],
)
def test_guard_comparison_target_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert guard_comparison_target(*args) == expected


@pytest.mark.detective
def test_guard_comparison_target_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = guard_comparison_target(op="in", const=5)
    assert result is None


@pytest.mark.detective
def test_guard_comparison_target_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = guard_comparison_target(op="abc", const=1)
    assert result is None
