"""Auto-generated by Detective — warrant-classed tests for Detective/audit.py::audit_measurement_incomplete.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.audit import audit_measurement_incomplete


@pytest.mark.detective
def test_audit_measurement_incomplete_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = audit_measurement_incomplete(unclassified=1)
    assert result is True


@pytest.mark.detective
def test_audit_measurement_incomplete_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = audit_measurement_incomplete(unclassified=0)
    assert result is False
