"""Auto-generated by Detective — warrant-classed tests for Detective/converge.py::owned_obligation_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.converge import owned_obligation_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (([True],), "foreign_only"),
        (([],), "unwitnessed"),
        (([False],), "owned"),
        (([True, False],), "owned"),
    ],
)
def test_owned_obligation_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert owned_obligation_disposition(*args) == expected
