# detective-content-sha256: 1c880368eb7e1f72d1fff3b6368a18658c39cee1cf0a1beadf8aadf4f9f390ff
"""Auto-generated by Detective — warrant-classed tests for Detective/rewrite.py::verify_rewrite_replay_row_shown.
Function digest: 695bdafab6494fa4.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.rewrite import verify_rewrite_replay_row_shown


@pytest.mark.detective
def test_verify_rewrite_replay_row_shown_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = verify_rewrite_replay_row_shown(proof_replayed="abc")
    assert result == "ran"


@pytest.mark.detective
def test_verify_rewrite_replay_row_shown_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = verify_rewrite_replay_row_shown(proof_replayed="skipped")
    assert result == "skipped"
