# detective-content-sha256: 24e8a3f480114f5a26cda99ae43d4c88ab57e1ed5e28980c33f75176c6144da6
"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::regime_outcome.
Function digest: aab92e14691dc641.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import regime_outcome


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("shadowed-target", False, False), "shadowed-target"),
        (("", True, False), "migrated"),
        (("", False, True), "migration_available"),
        (("", False, False), "clean"),
    ],
)
def test_regime_outcome_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert regime_outcome(*args) == expected
