"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::reachable_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.cli import reachable_disposition


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((2, False, None), "declined_multi"),
        ((1, True, None), "declined_error"),
        ((1, False, None), "roots"),
        ((1, False, 3), "scoped"),
    ],
)
def test_reachable_disposition_golden(args, expected):
    """VALUE golden captures — pure + deterministic (4 inputs)."""
    assert reachable_disposition(*args) == expected
