"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::_annotated_params.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest

from Detective.decompose_apply import _annotated_params


@pytest.mark.detective
def test__annotated_params_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _annotated_params(inputs=["a", "b"], annotations={"a": "int"})
    assert result == "a: int, b"
