"""Assemble synthesized properties into an idiomatic pytest module.

Takes a function's surviving mutants, turns each into an oracle-light property
(:mod:`Detective.synthesis.oracle_light`), and emits a clean, warrant-classed
pytest file: deduped imports, one test per survivor, a docstring stating the
warrant, and ``@pytest.mark.skip`` for properties that still need an oracle
(rather than emitting a failing or vacuous test).

This is where the auto-generation hygiene invariant lives: what Detective writes
is idiomatic, runnable-or-skipped pytest.
"""

from __future__ import annotations

import ast
import sys

from .oracle_light import ExecutableProperty, generate_executable_property

_INDENT = "    "


def synthesize_test_module(
    func_key: str,
    func_node: ast.FunctionDef | ast.AsyncFunctionDef | None,
    survivors: list[dict],
    call_site_inputs: list[dict] | None = None,
) -> str:
    """Return pytest source pinning each survivor, or "" when there is nothing to write."""
    props = [generate_executable_property(s, func_key, func_node, call_site_inputs) for s in survivors]
    return render_module(func_key, props)


def render_module(func_key: str, props: list[ExecutableProperty]) -> str:
    """Render a pytest module from already-built (and possibly filtered) properties."""
    if not props:
        return ""

    test_name = func_key.rsplit("::", 1)[-1].replace(".", "_")
    call_name = func_key.rsplit("::", 1)[-1]  # the callable name (dotted for methods)
    imports = _collect_imports(props)
    # Every generated test carries @pytest.mark.detective (and needs_oracle ones also
    # @pytest.mark.skip), so pytest is always imported even when no property's own setup
    # pulled it in.
    if "import pytest" not in imports:
        imports.append("import pytest")
    # The target's own top-level package is FIRST-party in the file we emit — it is the
    # module under test, so isort ranks it last. ("pkg/mod.py" -> "pkg"; "mod.py" -> "mod".)
    first_party = func_key.rsplit("::", 1)[0].replace("\\", "/").split("/")[0].removesuffix(".py")
    imports = _isort(imports, first_party)

    # Fold 2+ golden value-captures into ONE @pytest.mark.parametrize test (the idiomatic
    # data-driven form); a single golden and everything else render as individual tests.
    goldens = [p for p in props if p.golden_case is not None]
    blocks: list[str] = []
    if len(goldens) >= 2:
        blocks.append(_render_parametrized(test_name, call_name, goldens))
        rest = [p for p in props if p.golden_case is None]
    else:
        rest = props
    blocks += [_render_test(test_name, i, p) for i, p in enumerate(rest)]

    header = f'"""Auto-generated by Detective — warrant-classed tests for {func_key}."""'
    parts = [header, ""]
    if imports:
        # TWO blank lines after the import block: isort's `lines-after-imports` for
        # module-level code, and what `ruff check` demands of the files we emit.
        parts += imports + ["", ""]
    # TWO blank lines between top-level defs (PEP8, and what `ruff format` enforces on the
    # files we emit). Only visible with 2+ individual tests, which is why a single-test
    # module never surfaced it.
    parts.append("\n\n\n".join(blocks))
    return "\n".join(parts) + "\n"


def individual_test_names(func_key: str, props: list[ExecutableProperty]) -> dict[str, ExecutableProperty]:
    """Map each INDIVIDUAL rendered test name back to its property, mirroring render_module's
    naming EXACTLY — so a caller (converge) can act on a redundant-test finding from the profile,
    which is keyed by rendered name. Golden captures that fold into the one parametrized test are
    excluded: they are not individually named/droppable here (each case is already minimal-cover
    selected), so a value-pin is never silently dropped."""
    test_name = func_key.rsplit("::", 1)[-1].replace(".", "_")
    goldens = [p for p in props if p.golden_case is not None]
    rest = [p for p in props if p.golden_case is None] if len(goldens) >= 2 else props
    return {
        f"test_{test_name}_{p.category.lower()}_{i}": p for i, p in enumerate(rest) if p.golden_case is None
    }


def _render_parametrized(test_name: str, call_name: str, goldens: list[ExecutableProperty]) -> str:
    """Fold golden value-captures into one ``@pytest.mark.parametrize`` test — the
    idiomatic data-driven form: one test body, N ``(input, expected)`` rows."""
    rows = "\n".join(
        f"{_INDENT}{_INDENT}({args}, {expected}),"
        for args, expected in (g.golden_case for g in goldens if g.golden_case)
    )
    return "\n".join(
        [
            "@pytest.mark.detective",
            '@pytest.mark.parametrize("args, expected", [',
            rows,
            "])",
            f"def test_{test_name}_golden(args, expected):",
            f'{_INDENT}"""VALUE golden captures — pure + deterministic ({len(goldens)} inputs)."""',
            f"{_INDENT}assert {call_name}(*args) == expected",
        ]
    )


def _collect_imports(props: list[ExecutableProperty]) -> list[str]:
    """Deduped import/setup lines across all properties (unordered — see `_isort`)."""
    seen: dict[str, None] = {}
    for p in props:
        for line in p.setup_code.split("\n"):
            line = line.strip()
            if line.startswith(("import ", "from ")):
                seen[line] = None
    return list(seen)


def _top_module(line: str) -> str:
    """The top-level package an import line binds (``from a.b import c`` -> ``a``)."""
    parts = line.split()
    if len(parts) < 2:
        return ""
    return parts[1].split(".")[0].rstrip(",")


def _isort(lines: list[str], first_party: str) -> list[str]:
    """Order imports as ruff/isort (I001) does: stdlib, third-party, first-party — groups
    blank-line separated, plain ``import x`` before ``from x import y`` within a group.

    A flat lexicographic sort is NOT this ordering: it puts ``from Detective…`` ahead of
    ``import pytest`` because ``f`` < ``i``. That matters because a project lints the tests
    Detective writes (this one runs `ruff check tests/` in CI), so a generated file must be
    clean AS EMITTED — the hygiene invariant in this module's docstring.
    """
    groups: dict[int, list[str]] = {0: [], 1: [], 2: []}
    for line in lines:
        top = _top_module(line)
        if top in sys.stdlib_module_names:
            rank = 0
        elif first_party and top == first_party:
            rank = 2
        else:
            rank = 1
        groups[rank].append(line)

    out: list[str] = []
    for rank in (0, 1, 2):
        # `import x` sorts before `from x import y` — isort's default section ordering.
        block = sorted(groups[rank], key=lambda s: (s.startswith("from "), s))
        if block:
            if out:
                out.append("")
            out += block
    return out


def _render_test(fname: str, index: int, prop: ExecutableProperty) -> str:
    """Render one property as a pytest function (skipped when it needs an oracle)."""
    name = f"test_{fname}_{prop.category.lower()}_{index}"
    warrant = _warrant(prop)
    # Tag every generated test so a user can select/deselect them: `pytest -m detective`
    # runs only these; `pytest -m "not detective"` runs only the project's own tests.
    lines: list[str] = ["@pytest.mark.detective"]
    if prop.needs_oracle:
        lines.append(f'@pytest.mark.skip(reason="needs oracle: {_one_line(prop.assertion_code)}")')
    lines.append(f"def {name}():")
    lines.append(f'{_INDENT}"""{warrant}"""')
    lines.extend(f"{_INDENT}{line}" if line else "" for line in prop.assertion_code.split("\n"))
    return "\n".join(lines)


def _warrant(prop: ExecutableProperty) -> str:
    pre = "; ".join(prop.preconditions) if prop.preconditions else "no preconditions"
    mid = f" [{prop.mutant_id}]" if prop.mutant_id else ""
    return f"{prop.category} survivor{mid} — {pre} (confidence {prop.confidence})."


def _one_line(text: str) -> str:
    """First non-comment line of an assertion, collapsed for a skip reason."""
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            return stripped
    return text.split("\n")[0].strip()
