"""Assemble synthesized properties into an idiomatic pytest module.

Takes a function's surviving mutants, turns each into an oracle-light property
(:mod:`Detective.synthesis.oracle_light`), and emits a clean, warrant-classed
pytest file: deduped imports, one test per survivor, a docstring stating the
warrant, and ``@pytest.mark.skip`` for properties that still need an oracle
(rather than emitting a failing or vacuous test).

This is where the auto-generation hygiene invariant lives: what Detective writes
is idiomatic, runnable-or-skipped pytest.
"""

from __future__ import annotations

import ast

from .oracle_light import ExecutableProperty, generate_executable_property

_INDENT = "    "


def synthesize_test_module(
    func_key: str,
    func_node: ast.FunctionDef | ast.AsyncFunctionDef | None,
    survivors: list[dict],
    call_site_inputs: list[dict] | None = None,
) -> str:
    """Return pytest source pinning each survivor, or "" when there is nothing to write."""
    props = [generate_executable_property(s, func_key, func_node, call_site_inputs) for s in survivors]
    return render_module(func_key, props)


def render_module(func_key: str, props: list[ExecutableProperty]) -> str:
    """Render a pytest module from already-built (and possibly filtered) properties."""
    if not props:
        return ""

    test_name = func_key.rsplit("::", 1)[-1].replace(".", "_")
    call_name = func_key.rsplit("::", 1)[-1]  # the callable name (dotted for methods)
    imports = _collect_imports(props)
    # Every generated test carries @pytest.mark.detective (and needs_oracle ones also
    # @pytest.mark.skip), so pytest is always imported even when no property's own setup
    # pulled it in.
    if "import pytest" not in imports:
        imports = sorted([*imports, "import pytest"])

    # Fold 2+ golden value-captures into ONE @pytest.mark.parametrize test (the idiomatic
    # data-driven form); a single golden and everything else render as individual tests.
    goldens = [p for p in props if p.golden_case is not None]
    blocks: list[str] = []
    if len(goldens) >= 2:
        blocks.append(_render_parametrized(test_name, call_name, goldens))
        rest = [p for p in props if p.golden_case is None]
    else:
        rest = props
    blocks += [_render_test(test_name, i, p) for i, p in enumerate(rest)]

    header = f'"""Auto-generated by Detective — warrant-classed tests for {func_key}."""'
    parts = [header, ""]
    if imports:
        parts += imports + [""]
    parts.append("\n\n".join(blocks))
    return "\n".join(parts) + "\n"


def _render_parametrized(
    test_name: str, call_name: str, goldens: list[ExecutableProperty]
) -> str:
    """Fold golden value-captures into one ``@pytest.mark.parametrize`` test — the
    idiomatic data-driven form: one test body, N ``(input, expected)`` rows."""
    rows = "\n".join(
        f"{_INDENT}{_INDENT}({args}, {expected}),"
        for args, expected in (g.golden_case for g in goldens if g.golden_case)
    )
    return "\n".join(
        [
            "@pytest.mark.detective",
            '@pytest.mark.parametrize("args, expected", [',
            rows,
            "])",
            f"def test_{test_name}_golden(args, expected):",
            f'{_INDENT}"""VALUE golden captures — pure + deterministic ({len(goldens)} inputs)."""',
            f"{_INDENT}assert {call_name}(*args) == expected",
        ]
    )


def _collect_imports(props: list[ExecutableProperty]) -> list[str]:
    """Deduped, sorted import/setup lines across all properties."""
    seen: dict[str, None] = {}
    for p in props:
        for line in p.setup_code.split("\n"):
            line = line.strip()
            if line.startswith(("import ", "from ")):
                seen[line] = None
    return sorted(seen)


def _render_test(fname: str, index: int, prop: ExecutableProperty) -> str:
    """Render one property as a pytest function (skipped when it needs an oracle)."""
    name = f"test_{fname}_{prop.category.lower()}_{index}"
    warrant = _warrant(prop)
    # Tag every generated test so a user can select/deselect them: `pytest -m detective`
    # runs only these; `pytest -m "not detective"` runs only the project's own tests.
    lines: list[str] = ["@pytest.mark.detective"]
    if prop.needs_oracle:
        lines.append(f'@pytest.mark.skip(reason="needs oracle: {_one_line(prop.assertion_code)}")')
    lines.append(f"def {name}():")
    lines.append(f'{_INDENT}"""{warrant}"""')
    lines.extend(f"{_INDENT}{line}" if line else "" for line in prop.assertion_code.split("\n"))
    return "\n".join(lines)


def _warrant(prop: ExecutableProperty) -> str:
    pre = "; ".join(prop.preconditions) if prop.preconditions else "no preconditions"
    mid = f" [{prop.mutant_id}]" if prop.mutant_id else ""
    return f"{prop.category} survivor{mid} — {pre} (confidence {prop.confidence})."


def _one_line(text: str) -> str:
    """First non-comment line of an assertion, collapsed for a skip reason."""
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            return stripped
    return text.split("\n")[0].strip()
