# Auto-generated by Detective: makes the project root importable under pytest.
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))


def pytest_configure(config):
    # Register Detective's marker so `@pytest.mark.detective` is valid (no warning,
    # and safe under --strict-markers). Run only generated tests with
    # `pytest -m detective`; run only your own with `pytest -m 'not detective'`.
    config.addinivalue_line("markers", "detective: test generated by Detective")
