"""EXP-DS-006 — the cross-language gate, end-to-end through the REAL receipt (Wave 5).

The full path, no internal shortcuts (the house verification law): a seeded one-function
project → the real `detective receipt` CLI (which converges the target to mutation-completeness
first, so the recorded proof basis is real) → the receipt's own runnable OLD source becomes the
obligation-ledger oracle over a STATED deterministic input family → three C emissions through
`run_c_gate` under the pinned toolchain:

  arm 1  a faithful translation      → expect PRESERVED_PORTABLE
  arm 2  a boundary-flipped mutant   → expect CHANGED (with the distinguishing input named)
  arm 3  a non-compiling emission    → expect INVALID_MEASUREMENT (never CHANGED)

The observing set is named throughout: PRESERVED means "over this family, at this codec,
under this toolchain pin" — the §8/Cor-8.3 discipline, not a weakening of it.

Run:  PYTHONPATH=.:../Wesker python3 dev/exp_ds_006_emission.py
"""

from __future__ import annotations

import itertools
import json
import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from Detective.emission import CrossLangEmission, run_c_gate, value_portability  # noqa: E402
from Detective.rewrite import RewriteReceipt  # noqa: E402

_SEED_SRC = '''\
def tier_price(units: int, rate: int) -> int:
    """Seeded target: branchy, pure, int-total — every obligation rides the v1 codec."""
    if units <= 0:
        return 0
    total = units * rate
    if units > 100:
        total = total - (units - 100) * (rate // 2)
    if total > 10000:
        total = 10000
    return total
'''

_C_FAITHFUL = """\
long long tier_price(long long units, long long rate) {
    if (units <= 0) return 0;
    long long total = units * rate;
    if (units > 100) total = total - (units - 100) * (rate / 2);
    if (total > 10000) total = 10000;
    return total;
}
"""

# The adversarial arm — and a measured lesson worth its comment: the FIRST draft flipped
# `units > 100` to `>=`, and the gate correctly read PRESERVED, because that mutant is
# EQUIVALENT — at units == 100 the discount term is (units − 100) · … = 0, so the two programs
# agree on every input. The harness's own adversary was the undecidable-residue shape this
# project studies, live. The arm now drops the halved rate from the discount (rate/2 → rate),
# which the family's own (150, 7) distinguishes: old 900, mutant 700.
_C_MUTANT = _C_FAITHFUL.replace("(rate / 2)", "rate")

_C_BROKEN = "long long tier_price(long long units, long long rate) { return units +; }"

# The STATED input family: the boundary-adjacent grid (the seeded function's own edges ±1,
# plus zero/negative/interior points). Deterministic, enumerated, printed with the result.
_FAMILY = list(itertools.product((-1, 0, 1, 50, 99, 100, 101, 150), (0, 1, 2, 3, 7, 100)))


def main() -> None:
    pp = os.pathsep.join(
        [
            os.path.abspath(os.path.join(os.path.dirname(__file__), "..")),
            os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "Wesker")),
        ]
    )
    with tempfile.TemporaryDirectory() as tmp:
        with open(os.path.join(tmp, "pricing.py"), "w", encoding="utf-8") as fh:
            fh.write(_SEED_SRC)
        with open(os.path.join(tmp, "pyproject.toml"), "w", encoding="utf-8") as fh:
            fh.write('[tool.pytest.ini_options]\nmarkers = ["detective: generated by Detective"]\n')
        receipt_path = os.path.join(tmp, "receipt.json")
        cli = subprocess.run(
            [sys.executable, "-m", "Detective.cli", "receipt", "pricing.py::tier_price", "-o", receipt_path],
            cwd=tmp,
            env={**os.environ, "PYTHONPATH": pp},
            capture_output=True,
            text=True,
            timeout=900,
        )
        print(f"detective receipt exit: {cli.returncode}  (0 = complete + verified green)")
        if cli.returncode != 0:
            print(cli.stdout[-800:], cli.stderr[-800:])
            sys.exit(3)
        with open(receipt_path, encoding="utf-8") as fh:
            receipt = RewriteReceipt.from_json(fh.read())
        print(
            f"receipt: complete={receipt.functionally_complete} · proof={receipt.proof_status} · "
            f"universe={receipt.universe_size} · basis={len(receipt.proof_suite)} file(s)\n"
        )

        # The obligation ledger: the receipt's OWN runnable old source is the oracle.
        ns: dict = {}
        exec(receipt.original_source, ns)  # noqa: S102 — the receipt's stated purpose is to be runnable
        old = ns["tier_price"]
        obligations = [((u, r), old(u, r)) for u, r in _FAMILY]
        portable = sum(1 for _, v in obligations if value_portability(v) == "portable")
        print(f"obligation ledger: {len(obligations)} over the stated family · {portable} portable\n")

        results = {}
        for arm, src, expect in (
            ("faithful", _C_FAITHFUL, "PRESERVED_PORTABLE"),
            ("boundary-mutant", _C_MUTANT, "CHANGED"),
            ("broken", _C_BROKEN, "INVALID_MEASUREMENT"),
        ):
            emission = CrossLangEmission(
                language="c",
                source=src,
                entrypoint="tier_price",
                environment="",
                warrant=f"pricing.py::tier_price@{receipt.source_digest[:12]}",
            )
            res = run_c_gate(emission, obligations, tmp)
            ok = res["disposition"] == expect
            results[arm] = {"disposition": res["disposition"], "expected": expect, "pass": ok}
            print(f"── {arm} ──")
            print(f"  disposition: {res['disposition']}  (expected {expect})  PASS: {ok}")
            if res["mismatches"]:
                m = res["mismatches"][0]
                print(f"  first distinguishing input: args={m['args']} old={m['expected']} new={m['got']}")
            if arm == "faithful":
                print(f"  toolchain pin: {res['environment']}")
            print()

        print(json.dumps(results))
        print(f"{sum(1 for r in results.values() if r['pass'])}/3 arms pass")


if __name__ == "__main__":
    main()
