"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::apply_migration."""

import pytest

from Detective.regime import Migration, apply_migration


@pytest.mark.detective
def test_apply_migration_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = apply_migration(
        Migration(
            root="x",
            declare_marker=True,
            declare_pythonpath=True,
            remove_conftests=("x",),
            create_config=False,
            blocked=("x",),
        )
    )
    assert result == ()


@pytest.mark.detective
def test_apply_migration_value_1():
    """VALUE survivor — distinguishing witness (original raises FileNotFoundError: [Errno 2] No such file or directory: 'x/pyproject.toml') (confidence 0.95)."""
    try:
        _result = apply_migration(
            Migration(
                root="x",
                declare_marker=True,
                declare_pythonpath=True,
                remove_conftests=("x",),
                create_config=True,
                blocked=("x",),
            )
        )
    except FileNotFoundError as _exc:
        assert str(_exc) == "[Errno 2] No such file or directory: 'x/pyproject.toml'"
    except BaseException as _exc:
        pytest.fail(f"expected FileNotFoundError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected FileNotFoundError, but the call returned {_result!r}")
