"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_params_only."""

import pytest

from Detective.cli import _params_only


@pytest.mark.detective
def test__params_only_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _params_only("abc", "abc", ("x",))
    assert result is False


@pytest.mark.detective
def test__params_only_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _params_only("", "", ("x",))
    assert result is False
