"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::_literal_values."""

import ast

import pytest

from Detective.engine import _literal_values


@pytest.mark.detective
def test__literal_values_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _literal_values(ast.parse("def _f(x):\n    return x").body[0])
    assert result == []
