"""Tests for Detective.certify.

``_write`` is pure file I/O and is mutation-driven to the ceiling (plain helpers,
no fixtures). ``certify`` itself is an orchestrator that runs the full Wesker
engine; it is covered by an end-to-end integration smoke test (mutation-profiling
it would nest profiling), so that one may use fixtures.
"""

from __future__ import annotations

import os
import tempfile

from Detective.certify import (
    _PYTEST_SECTION,
    _wiring_message,
    _write,
    certify,
    ensure_marker_registered,
)

# ── _wiring_message (mutation-driven — the exact CLI wording IS the product) ─
# The message is the idiot-proof surface a first-time user reads, so its full text
# is the contract: assert it verbatim (kills every VALUE mutant, incl. the prose).
_WIRED_TAIL = (
    "the generated tests carry `@pytest.mark.detective`, which `--strict-markers` rejects "
    "unless it is declared. Declared in config, so nothing new is importable and nothing "
    "can collide"
)
_DID = "registered the `detective` marker in [tool.pytest.ini_options]"


def test_wiring_message_wired_and_verified_verbatim():
    msg = _wiring_message(conftest_wired=_DID, collects=True, passed=3)
    assert msg == f"pytest wiring: {_DID} — {_WIRED_TAIL}; verified 3 test(s) pass under pytest"


def test_wiring_message_already_declared_verbatim():
    msg = _wiring_message(conftest_wired=None, collects=True, passed=2)
    assert msg == (
        "pytest wiring: pytest config already declares the marker — nothing to change; "
        "verified 2 test(s) pass under pytest"
    )


def test_wiring_message_warns_when_tests_do_not_collect_verbatim():
    msg = _wiring_message(conftest_wired=_DID, collects=False, passed=0)
    assert msg == (
        f"pytest wiring: {_DID} — {_WIRED_TAIL}; "
        "⚠ pytest could NOT collect the generated tests — check the import path"
    )


# ── ensure_marker_registered (declarative wiring — never a second conftest) ──
def test_marker_is_added_to_an_existing_pytest_section():
    d = tempfile.mkdtemp()
    cfg = os.path.join(d, "pyproject.toml")
    with open(cfg, "w", encoding="utf-8") as fh:
        fh.write(f'[project]\nname = "x"\n\n{_PYTEST_SECTION}\ntestpaths = ["tests"]\n')
    assert ensure_marker_registered(d) == f"registered the `detective` marker in {_PYTEST_SECTION}"
    with open(cfg, encoding="utf-8") as fh:
        body = fh.read()
    assert 'markers = ["detective: test generated by Detective"]' in body
    assert 'testpaths = ["tests"]' in body  # the consumer's own settings survive


def test_the_pytest_section_is_created_when_absent():
    d = tempfile.mkdtemp()
    cfg = os.path.join(d, "pyproject.toml")
    with open(cfg, "w", encoding="utf-8") as fh:
        fh.write('[project]\nname = "x"\n')
    assert ensure_marker_registered(d) == f"added {_PYTEST_SECTION} with the `detective` marker"
    with open(cfg, encoding="utf-8") as fh:
        body = fh.read()
    assert _PYTEST_SECTION in body
    assert '[project]\nname = "x"' in body


def test_registering_twice_changes_nothing():
    # Idempotent: converge runs constantly, and a wiring step that appends every run is a
    # tool that vandalises the config it is supposed to be tidying.
    d = tempfile.mkdtemp()
    cfg = os.path.join(d, "pyproject.toml")
    with open(cfg, "w", encoding="utf-8") as fh:
        fh.write(f'{_PYTEST_SECTION}\ntestpaths = ["tests"]\n')
    ensure_marker_registered(d)
    with open(cfg, encoding="utf-8") as fh:
        once = fh.read()
    assert ensure_marker_registered(d) is None
    with open(cfg, encoding="utf-8") as fh:
        assert fh.read() == once


def test_no_pyproject_writes_nothing_at_all():
    # We declare into a config the project already has; we do not invent one.
    d = tempfile.mkdtemp()
    assert ensure_marker_registered(d) is None
    assert os.listdir(d) == []


def test_it_never_writes_a_conftest():
    # THE regression this function exists to prevent: a generated root conftest.py collides
    # with tests/conftest.py (both import as module `conftest`), which killed Detective's own
    # live pytest session and silently dropped every fixture-taking test from the profile.
    d = tempfile.mkdtemp()
    with open(os.path.join(d, "pyproject.toml"), "w", encoding="utf-8") as fh:
        fh.write(f"{_PYTEST_SECTION}\n")
    ensure_marker_registered(d)
    assert not os.path.exists(os.path.join(d, "conftest.py"))


# ── _write (mutation-driven) ──────────────────────────────────────
def test_write_creates_named_file():
    d = tempfile.mkdtemp()
    path = _write("# content\n", d, "reset")
    assert path == os.path.join(d, "test_reset_synth.py")
    with open(path, encoding="utf-8") as fh:
        assert fh.read() == "# content\n"


def test_write_converts_dotted_qualname():
    d = tempfile.mkdtemp()
    path = _write("x", d, "Counter.reset")
    assert os.path.basename(path) == "test_Counter_reset_synth.py"


def test_write_creates_missing_directory():
    d = os.path.join(tempfile.mkdtemp(), "nested", "dir")
    path = _write("x", d, "f")
    assert os.path.isdir(d) and os.path.exists(path)


# ── certify (fast path only — full runs are verified out-of-suite) ─
# certify() runs the full Wesker engine, which nests a whole-suite pytest
# collection; running it inside the suite hangs, so the end-to-end path is
# verified by a standalone run, not here. Only the pre-profiling guard is tested.
def test_certify_unknown_function_raises():
    import pytest

    with pytest.raises(LookupError):
        certify("Detective/scope.py", "no_such_function", ".")
