"""Auto-generated by Detective — warrant-classed tests for Detective/converge.py::passes_to_complete."""

from Detective.converge import passes_to_complete
import pytest

@pytest.mark.detective
@pytest.mark.parametrize("args, expected", [
        (((26, 5, 2),), 1),
        (((100, 10, 1),), 1),
        (((),), 0),
        (((0,),), 0),
        (((5, 5),), -1),
        (((3, 6),), -1),
        (((1,),), -1),
        (((26, 5, 2, 0),), 0),
        (((-1, 8, 4, 2),), 1),
])
def test_passes_to_complete_golden(args, expected):
    """VALUE golden captures — pure + deterministic (9 inputs)."""
    assert passes_to_complete(*args) == expected
