"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_collect_reads."""

from Detective.decompose import _collect_reads
import ast

def test__collect_reads_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _collect_reads(ast.parse('def _f(x):\n    return x').body[0])
    assert result == {'x'}
