"""A human edit of a generated test flips its origin to intent — the digest makes it observable (X5).

TEST_BASIS §16 X5 (Part V gap ledger, G5). Before this, `witness_origin_of` hard-coded `edited=False`
— Detective recorded no content digest of what it wrote, so a human takeover of a generated file was
invisible and the file read `characterization` forever. X5 stamps a body-content digest into the
generated file's own header (the ruling: in the file, not a sidecar — the signal survives a
`.detective` wipe), and `witness_origin_of` re-hashes to detect an edit.

`content_edited(has_digest, digest_matches)` is pinned here by ENUMERATION: two booleans is four
cases, a COMPLETE truth table. (converge could not pin it in isolation — it is already wired into the
audit census through `witness_origin_of`, so its covering set inflates to suite scale, the documented
converge-before-wiring hang. A total truth table is the honest pin.)
"""

from __future__ import annotations

import importlib

_cm = importlib.import_module("Detective.certify")


def test_content_edited_truth_table_is_total():
    # Edited ONLY when a digest was recorded AND the body no longer matches it.
    assert _cm.content_edited(has_digest=True, digest_matches=False) is True
    assert _cm.content_edited(has_digest=True, digest_matches=True) is False
    # No recorded digest → never edited, regardless of the (meaningless) match bit — the absence of a
    # record must not manufacture an "edited" verdict (§2.3).
    assert _cm.content_edited(has_digest=False, digest_matches=False) is False
    assert _cm.content_edited(has_digest=False, digest_matches=True) is False


def test_stamp_and_status_round_trip():
    src = '"""a generated module."""\n\n\ndef test_x():\n    assert True\n'
    stamped = _cm._stamp_content_digest(src)
    assert stamped.startswith(_cm._CONTENT_DIGEST_PREFIX)
    assert stamped.endswith(src)  # the digest line is PREPENDED; the body is untouched


def test_a_generated_file_reads_characterization_until_a_human_edits_it(tmp_path):
    # A real generated module: the Detective header claims the target, so generated_owner marks it 𝒢.
    src = (
        f'"""{_cm._HEADER_PREFIX}mod.py::f.\n\ngenerated by Detective."""\n\n\n'
        "def test_f():\n    assert True\n"
    )
    path = _cm._write(src, str(tmp_path), "mod.py::f")
    assert path, "write must produce a path"
    # As written: generated + unedited (digest matches) → characterization (𝒢).
    assert _cm.witness_origin_of(path) == "characterization"

    # A human takes it over: append a real assertion. The body no longer matches the stamped digest.
    with open(path, "a", encoding="utf-8") as fh:
        fh.write("\n\ndef test_f_boundary():\n    assert True  # a human's intent\n")
    assert _cm.witness_origin_of(path) == "intent", "an edited generated file is intent (ℋ), not 𝒢"


def test_a_generated_file_with_no_stamped_digest_stays_characterization(tmp_path):
    # A file written before X5 (or with the digest line removed) carries no record → not edited.
    src = f'"""{_cm._HEADER_PREFIX}mod.py::g.\n\nlegacy generated."""\n\n\ndef test_g():\n    assert True\n'
    path = tmp_path / "legacy_synth.py"
    path.write_text(src)  # written WITHOUT _stamp_content_digest
    assert _cm.witness_origin_of(str(path)) == "characterization"
