"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::_compared_literals."""

import ast

import pytest

from Detective.engine import _compared_literals


@pytest.mark.detective
def test__compared_literals_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _compared_literals(ast.parse("def _f(x):\n    return x").body[0])
    assert result == {}
