"""Auto-generated by Detective — warrant-classed tests for Detective/equivalence.py::_binds."""

import pytest

from Detective.equivalence import _binds


@pytest.mark.detective
def test__binds_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _binds(1, (1,))
    assert result is True
