"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_collect_reads."""

import ast

from Detective.decompose import _collect_reads


def test__collect_reads_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _collect_reads(ast.parse("def _f(x):\n    return x").body[0])
    assert result == {"x"}
