"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_collect_writes."""

from Detective.decompose import _collect_writes
import ast

def test__collect_writes_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _collect_writes(ast.parse('def _f(x):\n    return x').body[0])
    assert result == set()
