"""A generated suite never replaces a file it does not own (issue #61).

`_write` checked the ownership header before deleting the LEGACY sibling, then removed or
overwrote the PRIMARY destination with no check at all — while the comment directly above it
read "Ownership is checked by the header grammar, never assumed from the name; user files are
untouchable." The guard existed and was applied to the wrong path.

That is reachable without any user error, because `synth_filename` is NOT INJECTIVE: it
flattens `/ \\ . - space` all to `_`, so several distinct targets — and a plausible hand-written
filename — normalise to one name.

Refusing rather than quietly writing elsewhere is the point. A different name would make the
collision invisible again; the ambiguity has to be impossible to lose before it can be fixed.
"""

from __future__ import annotations

import pytest

from Detective.certify import (
    GeneratedSuiteCollision,
    _readable_stem,
    _write,
    generated_owner,
    synth_filename,
    write_disposition,
)

_HEADER = "Auto-generated by Detective — warrant-classed tests for {key}."


def _generated(key: str) -> str:
    return f'"""{_HEADER.format(key=key)}\n\nbody\n"""\n\n\ndef test_x():\n    assert True\n'


def test_the_filename_scheme_is_injective_over_the_colliding_family():
    """The four keys the issue names once produced ONE filename — the flattening turns
    ``/ \\ . - space`` all into ``_``. The key digest separates them by construction rather than
    by hoping their punctuation survives."""
    keys = ("a/b.py::c", "a_b.py::c", "a-b.py::c", "a b.py::c")
    names = {synth_filename(k) for k in keys}
    assert len(names) == len(keys), f"expected {len(keys)} distinct names, got {names}"


def test_the_readable_stem_alone_still_collides():
    """And that is fine — the stem is for humans. Pinned so nobody 'fixes' the flattening into
    something unreadable believing it carries identity; the digest is what does."""
    stems = {_readable_stem(k) for k in ("a/b.py::c", "a_b.py::c", "a-b.py::c")}
    assert len(stems) == 1


def test_a_users_file_is_refused_not_destroyed(tmp_path):
    """The data-loss case. No Detective header means it is someone's own work."""
    key = "m.py::f"
    dest = tmp_path / synth_filename(key)
    dest.write_text("def test_mine():\n    assert True\n", encoding="utf-8")

    with pytest.raises(GeneratedSuiteCollision, match="no Detective ownership header"):
        _write(_generated(key), str(tmp_path), key)

    assert dest.read_text() == "def test_mine():\n    assert True\n"


def test_another_targets_file_is_refused_and_names_the_owner(tmp_path):
    """Our collision, not the user's problem — so the message has to carry the OTHER func_key.
    A refusal that says only 'not yours' sends the reader to inspect their own tests."""
    mine, theirs = "a/b.py::c", "a_b.py::c"
    # The digest now separates these two, so the collision is staged directly at OUR
    # destination. That is the case the guard still has to cover: a digest collision, a
    # hand-copied file, or any future naming change can put a foreign-owned file here, and
    # naming is probabilistic while this check is not.
    dest = tmp_path / synth_filename(mine)
    dest.write_text(_generated(theirs), encoding="utf-8")

    with pytest.raises(GeneratedSuiteCollision, match="a_b.py::c"):
        _write(_generated(mine), str(tmp_path), mine)


def test_our_own_file_is_still_overwritten(tmp_path):
    """The control. Regeneration is the normal path and must not be blocked — a guard that
    refused here would break every second converge."""
    key = "m.py::f"
    dest = tmp_path / synth_filename(key)
    dest.write_text(_generated(key), encoding="utf-8")

    written = _write(_generated(key) + "\n# fresh\n", str(tmp_path), key)
    assert written == str(dest)
    assert "# fresh" in dest.read_text()


def test_an_empty_source_does_not_delete_a_file_we_do_not_own(tmp_path):
    """The delete branch destroys as much as the write branch. An empty-source pass — converge's
    minimize dropping every generated test — must not remove someone else's file."""
    key = "m.py::f"
    dest = tmp_path / synth_filename(key)
    dest.write_text("def test_mine():\n    assert True\n", encoding="utf-8")

    with pytest.raises(GeneratedSuiteCollision):
        _write("   ", str(tmp_path), key)

    assert dest.exists(), "a file we do not own was deleted"


def test_writing_into_an_empty_directory_is_unaffected(tmp_path):
    """Nothing there, nothing to protect."""
    key = "m.py::f"
    written = _write(_generated(key), str(tmp_path), key)
    assert written and generated_owner(written) == key


def test_the_disposition_distinguishes_the_two_refusals():
    """They call for different investigations, so they must not share a value."""
    assert write_disposition(True, "other.py::g", "m.py::f") == "refuse_foreign"
    assert write_disposition(True, "", "m.py::f") == "refuse_unowned"
    assert write_disposition(True, "m.py::f", "m.py::f") == "write"
    assert write_disposition(False, "", "m.py::f") == "write"
