"""Auto-generated by Detective — warrant-classed tests for Detective/synthesis/characterization.py::distinction_pin_lines."""

import pytest

from Detective.synthesis.characterization import distinction_pin_lines


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1, "1.0"), ["assert type(result) is int"]),
        ((True, "1"), ["assert type(result) is bool"]),
        ((0.0, "-0.0"), ["assert repr(result) == '0.0'"]),
        ((1, "2"), []),
        ((1, "<raised ValueError: boom>"), []),
        ((1, "<m.Thing object at 0x1>"), []),
        ((1, "abc"), []),
    ],
)
def test_distinction_pin_lines_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert distinction_pin_lines(*args) == expected
