"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::find_extraction_candidates."""

from Detective.decompose import find_extraction_candidates
import ast

def test_find_extraction_candidates_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = find_extraction_candidates(ast.parse('def _f(x):\n    return x').body[0], 1, 2, 3)
    assert repr(result) == '()'

def test_find_extraction_candidates_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = find_extraction_candidates(ast.parse('def _f(x):\n    return x').body[0], -1, -1, -1)
    assert repr(result) == '()'
