"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_has_exit_statement."""

import ast

from Detective.decompose import _has_exit_statement


def test__has_exit_statement_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _has_exit_statement(ast.parse("def _f(x):\n    return x").body[0])
    assert repr(result) == "False"
