"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_format_uncollected."""

import pytest

from Detective.cli import _format_uncollected


@pytest.mark.detective
def test__format_uncollected_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _format_uncollected({"x": None}, ["x"], "abc")
    assert result == ""
