"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::_conftests."""

import pytest

from Detective.regime import _conftests


@pytest.mark.detective
def test__conftests_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _conftests("")
    assert result == (("tests/conftest.py",), (), ())
