"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::_test_names_in_source."""

import pytest

from Detective.decompose_apply import _test_names_in_source


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("def broken(:",), set()),
        (("def test_hit(): pass\ndef helper(): pass",), {"test_hit", "helper"}),
        (("abc",), set()),
    ],
)
def test__test_names_in_source_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert _test_names_in_source(*args) == expected
