"""Tests for Detective.certify.

``_write`` is pure file I/O and is mutation-driven to the ceiling (plain helpers,
no fixtures). ``certify`` itself is an orchestrator that runs the full Wesker
engine; it is covered by an end-to-end integration smoke test (mutation-profiling
it would nest profiling), so that one may use fixtures.
"""

from __future__ import annotations

import os
import tempfile

from Detective.certify import (
    _PYTEST_SECTION,
    _wiring_message,
    _write,
    certify,
    ensure_marker_registered,
    run_pytest_verification,
    synth_filename,
    verify_timeout_s,
)

# ── _wiring_message (mutation-driven — the exact CLI wording IS the product) ─
# The message is the idiot-proof surface a first-time user reads, so its full text
# is the contract: assert it verbatim (kills every VALUE mutant, incl. the prose).
_WIRED_TAIL = (
    "the generated tests carry `@pytest.mark.detective`, which `--strict-markers` rejects "
    "unless it is declared. Declared in config, so nothing new is importable and nothing "
    "can collide"
)
_DID = "registered the `detective` marker in [tool.pytest.ini_options]"


def test_wiring_message_wired_and_verified_verbatim():
    msg = _wiring_message("registered_now", _DID, collects=True, passed=3)
    assert msg == f"pytest wiring: {_DID} — {_WIRED_TAIL}; verified 3 test(s) pass under pytest"


def test_wiring_message_already_declared_verbatim():
    msg = _wiring_message("already_declared", None, collects=True, passed=2)
    assert msg == (
        "pytest wiring: pytest config already declares the marker — nothing to change; "
        "verified 2 test(s) pass under pytest"
    )


def test_wiring_message_no_config_directs_to_migrate():
    # #32: no config is NOT "already declared" — say so, and give the working next action.
    msg = _wiring_message("no_config", None, collects=True, passed=2)
    assert "no pytest config here" in msg
    assert "detective regime --migrate" in msg
    assert "never a conftest.py" in msg
    assert "already declares" not in msg


def test_marker_disposition_splits_no_config_from_already_declared():
    from Detective.certify import marker_disposition

    assert marker_disposition(_DID, has_config=True) == "registered_now"
    assert marker_disposition(None, has_config=True) == "already_declared"
    assert marker_disposition(None, has_config=False) == "no_config"


def test_wiring_message_warns_when_tests_do_not_collect_verbatim():
    msg = _wiring_message("registered_now", _DID, collects=False, passed=0)
    assert msg == (
        f"pytest wiring: {_DID} — {_WIRED_TAIL}; "
        "⚠ pytest could NOT collect the generated tests — check the import path"
    )


# ── ensure_marker_registered (declarative wiring — never a second conftest) ──
def test_marker_is_added_to_an_existing_pytest_section():
    d = tempfile.mkdtemp()
    cfg = os.path.join(d, "pyproject.toml")
    with open(cfg, "w", encoding="utf-8") as fh:
        fh.write(f'[project]\nname = "x"\n\n{_PYTEST_SECTION}\ntestpaths = ["tests"]\n')
    assert (
        ensure_marker_registered(d)
        == f"registered the `detective` marker in {_PYTEST_SECTION} of pyproject.toml"
    )
    with open(cfg, encoding="utf-8") as fh:
        body = fh.read()
    assert 'markers = ["detective: test generated by Detective"]' in body
    assert 'testpaths = ["tests"]' in body  # the consumer's own settings survive


def test_the_pytest_section_is_created_when_absent():
    d = tempfile.mkdtemp()
    cfg = os.path.join(d, "pyproject.toml")
    with open(cfg, "w", encoding="utf-8") as fh:
        fh.write('[project]\nname = "x"\n')
    assert (
        ensure_marker_registered(d)
        == f"added {_PYTEST_SECTION} to pyproject.toml with the `detective` marker"
    )
    with open(cfg, encoding="utf-8") as fh:
        body = fh.read()
    assert _PYTEST_SECTION in body
    assert '[project]\nname = "x"' in body


def test_registering_twice_changes_nothing():
    # Idempotent: converge runs constantly, and a wiring step that appends every run is a
    # tool that vandalises the config it is supposed to be tidying.
    d = tempfile.mkdtemp()
    cfg = os.path.join(d, "pyproject.toml")
    with open(cfg, "w", encoding="utf-8") as fh:
        fh.write(f'{_PYTEST_SECTION}\ntestpaths = ["tests"]\n')
    ensure_marker_registered(d)
    with open(cfg, encoding="utf-8") as fh:
        once = fh.read()
    assert ensure_marker_registered(d) is None
    with open(cfg, encoding="utf-8") as fh:
        assert fh.read() == once


def test_no_pyproject_writes_nothing_at_all():
    # We declare into a config the project already has; we do not invent one.
    d = tempfile.mkdtemp()
    assert ensure_marker_registered(d) is None
    assert os.listdir(d) == []


def test_it_never_writes_a_conftest():
    # THE regression this function exists to prevent: a generated root conftest.py collides
    # with tests/conftest.py (both import as module `conftest`), which killed Detective's own
    # live pytest session and silently dropped every fixture-taking test from the profile.
    d = tempfile.mkdtemp()
    with open(os.path.join(d, "pyproject.toml"), "w", encoding="utf-8") as fh:
        fh.write(f"{_PYTEST_SECTION}\n")
    ensure_marker_registered(d)
    assert not os.path.exists(os.path.join(d, "conftest.py"))


# ── _write (mutation-driven) ──────────────────────────────────────
def test_write_creates_named_file():
    d = tempfile.mkdtemp()
    path = _write("# content\n", d, "reset")
    assert path == os.path.join(d, synth_filename("reset"))
    with open(path, encoding="utf-8") as fh:
        written = fh.read()
    # #X5: a body-content digest is stamped as the first line so a later human edit is observable.
    # The source itself is written verbatim after it (the digest covers exactly that body).
    assert written.startswith("# detective-content-sha256: ")
    assert written.endswith("# content\n")


def test_write_converts_dotted_qualname():
    d = tempfile.mkdtemp()
    path = _write("x", d, "Counter.reset")
    assert os.path.basename(path) == synth_filename("Counter.reset")


def test_write_creates_missing_directory():
    d = os.path.join(tempfile.mkdtemp(), "nested", "dir")
    path = _write("x", d, "f")
    assert os.path.isdir(d) and os.path.exists(path)


# ── synth_filename: one file per TARGET, not per function name ────
def test_same_function_name_in_two_modules_gets_two_files():
    """The regression this rule exists for. Both named the file after the qualname alone, so
    `beta.py::load`'s converge overwrote `alpha.py::load`'s suite — measured: alpha fell from
    `✓ COMPLETE 13/13` to `0.0% killed, 10 real gaps`, silently, while beta reported success.
    `load`/`run`/`main`/`parse` make that a matter of when, not whether."""
    assert synth_filename("alpha.py::load") != synth_filename("beta.py::load")
    assert synth_filename("alpha.py::load").startswith("test_alpha_load_")
    assert synth_filename("beta.py::load").startswith("test_beta_load_")


def test_the_extension_is_stripped_from_the_module_not_the_middle():
    """`.py` has to go before the halves are joined. Flattening first leaves it mid-string
    where `removesuffix` is a no-op, and the file becomes `test_orphan_py_tier_price_synth.py`."""
    assert synth_filename("orphan.py::tier_price").startswith("test_orphan_tier_price_")
    assert "_py_" not in synth_filename("orphan.py::tier_price")


def test_a_nested_module_path_flattens_and_stays_unique():
    """Two `mod.py` under different packages are different targets, so the package has to
    survive into the name — otherwise the collision just moves up a directory."""
    a = synth_filename("pkg/mod.py::run")
    b = synth_filename("other/mod.py::run")
    assert a.startswith("test_pkg_mod_run_") and b.startswith("test_other_mod_run_")
    assert a != b


def test_a_dotted_qualname_keeps_its_owner():
    assert synth_filename("m.py::Counter.reset").startswith("test_m_Counter_reset_")


def test_a_bare_name_is_used_as_is():
    """Direct `_write(..., "reset")` callers pass no module half; the fallback keeps their
    name in the readable stem rather than inventing an empty one. The key digest still follows
    it (#61) — a bare name is a key like any other, and exempting it would reintroduce exactly
    the collision the digest exists to prevent between `reset` and `a/reset.py::`."""
    assert synth_filename("reset").startswith("test_reset_")
    assert synth_filename("reset").endswith("_synth.py")
    assert synth_filename("reset") != synth_filename("other.py::reset")


# ── certify (fast path only — full runs are verified out-of-suite) ─
# certify() runs the full Wesker engine, which nests a whole-suite pytest
# collection; running it inside the suite hangs, so the end-to-end path is
# verified by a standalone run, not here. Only the pre-profiling guard is tested.
def test_certify_unknown_function_raises():
    import pytest

    with pytest.raises(LookupError):
        certify("Detective/scope.py", "no_such_function", ".")


# ── deadline-aware verification (#35: one wall, never a fresh 120s) ─
def test_verify_timeout_s_clamps_to_the_remaining_wall():
    assert verify_timeout_s(None) == 120.0  # no wall → full cap
    assert verify_timeout_s(0.0) == 0.0  # exhausted → withhold
    assert verify_timeout_s(-3.0) == 0.0  # never negative
    assert verify_timeout_s(0.5) == 0.5  # clamp to the little that's left
    assert verify_timeout_s(500.0) == 120.0  # never more than the cap


def test_verification_withholds_without_spawning_when_deadline_exhausted(tmp_path):
    """An exhausted aggregate wall must NOT spawn a fresh 120s pytest (the #35 overrun). The proof is
    a real green test file that the exhausted-deadline path never runs: no exit code, nothing collected."""
    t = tmp_path / "test_x.py"
    t.write_text("def test_ok():\n    assert True\n")
    v = run_pytest_verification(str(tmp_path), [str(t)], deadline_s=0.0)
    assert v.status == "timed_out"  # unverified, honestly withheld
    assert v.exit_code is None and v.collected == 0  # pytest never ran
    assert not v.ok
