"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_derived_input."""

import pytest

from Detective.certify import PytestWiring
from Detective.cli import _derived_input
from Detective.converge import ConvergeIteration, ConvergeResult
from Detective.equivalence import MutantVerdict, SurvivorReport


@pytest.mark.detective
def test__derived_input_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _derived_input(
        r=1,
        proof=ConvergeResult(
            function="x",
            converged=True,
            at_ceiling=True,
            initial_survivors=1,
            final_survivors=1,
            iterations=(ConvergeIteration(survivors=1, written=1),),
            written_path="x",
            total_mutants=1,
            killed=1,
            value_killed=1,
            remaining=("x",),
            wiring=PytestWiring(conftest_wired="x", collects=True, passed=1, message="x"),
            survivor_report=SurvivorReport(
                verdicts=(None,),
                unclassified=("x",),
                note="x",
                manual_equivalent=("x",),
                inputs_expressible=True,
            ),
            functionally_complete=True,
            line_complete=True,
            missing_lines=(1,),
            manually_unreachable=1,
            contradicted_line_flags=("x",),
            missing_line_guards=((1, "x"),),
            redundant_tests=("x",),
            minimal_test_count=1,
            universe_size=1,
            fast=True,
            coverage_guarantee=1.0,
            signature="x",
            param_names=("x",),
            synthesized_only=True,
        ),
        rep=SurvivorReport(
            verdicts=(
                MutantVerdict(
                    mutant_id="x",
                    category="x",
                    diff_summary="x",
                    killable=True,
                    witness=None,
                    searched=1,
                    crash_only=True,
                    crash_witness=None,
                    suite_detected=True,
                ),
            ),
            unclassified=("x",),
            note="x",
            manual_equivalent=("x",),
            inputs_expressible=True,
        ),
        target="x",
        verb="x",
        report="x",
    )
    assert result == [
        'DO THIS:  x --input "(<x>,)"',
        "",
        "  · Signature          x",
        "",
        "  · Task               Author 1 call(s) — one per line below — each as",
        "                       its own --input. Detective derives every test from them.",
        "  · Why                Every killable mutant is already dead. What is left is",
        "                       lines no test executes; a mutant on a line that never",
        "                       runs cannot be killed, so reach these first.",
        "  · Uncovered          1. line 1 — reached only when: x",
    ]
