"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::_wanted_test_names."""

import pytest

from Detective.decompose_apply import _wanted_test_names


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (({"M_1": ["t[case-a]", "plain"], "M_2": ["t[case-b]"]},), {"t", "plain"}),
        (({"x": ["x"]},), {"x"}),
    ],
)
def test__wanted_test_names_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert _wanted_test_names(*args) == expected
