"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_suggest_name."""

import pytest

from Detective.decompose import _suggest_name


@pytest.mark.detective
def test__suggest_name_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _suggest_name({"x"}, "abc")
    assert result == "_compute_x"


@pytest.mark.detective
def test__suggest_name_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _suggest_name({"total", "fee"}, "f")
    assert result == "_compute_fee_total"
