"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::plan_migration."""

import pytest

from Detective.engine import ShadowedTarget
from Detective.regime import TestRegime, plan_migration


@pytest.mark.detective
def test_plan_migration_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = plan_migration(
        TestRegime(
            root="x",
            layout="x",
            suite_path=("x",),
            testpaths=("x",),
            pythonpath=("x",),
            marker_declared=False,
            has_config=True,
            conftests=("x",),
            colliding_conftests=("x",),
            generated_conftests=("x",),
            target="x",
            module="x",
            shadow=ShadowedTarget(module="x", target="x", imported="x"),
        )
    )
    assert (
        repr(result)
        == "Migration(root='x', declare_marker=True, declare_pythonpath=False, remove_conftests=('x',), create_config=False, blocked=('`x` imports x, not this tree — install this one (`pip install -e .`) or point --project-root at that one',))"
    )


@pytest.mark.detective
def test_plan_migration_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = plan_migration(
        TestRegime(
            root="x",
            layout="x",
            suite_path=("x",),
            testpaths=("x",),
            pythonpath=("x",),
            marker_declared=True,
            has_config=False,
            conftests=("x",),
            colliding_conftests=("x",),
            generated_conftests=("x",),
            target="x",
            module="x",
            shadow=ShadowedTarget(module="x", target="x", imported="x"),
        )
    )
    assert (
        repr(result)
        == "Migration(root='x', declare_marker=False, declare_pythonpath=False, remove_conftests=('x',), create_config=False, blocked=('`x` imports x, not this tree — install this one (`pip install -e .`) or point --project-root at that one',))"
    )
