"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_always_evaluated."""

import pytest

from Detective.cli import _always_evaluated


@pytest.mark.detective
def test__always_evaluated_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _always_evaluated("abc", "abc", 1, "abc")
    assert result is False


@pytest.mark.detective
def test__always_evaluated_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _always_evaluated("", "", -1, "")
    assert result is False
