"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_format_decompose."""

import pytest

from Detective.cli import _format_decompose
from Detective.decompose_apply import Decomposition, DecompositionApply, Extraction


@pytest.mark.detective
def test__format_decompose_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _format_decompose(
        DecompositionApply(
            function="x",
            applied=(Extraction(helper_name="x", params=("x",), returns=("x",), new_source="x"),),
            proposed=(
                Decomposition(
                    extraction=Extraction(helper_name="x", params=("x",), returns=("x",), new_source="x"),
                    validated=True,
                ),
            ),
            unsafe_blocks=("x",),
            proof=None,
        ),
        True,
        "x",
        "x",
    )
    assert (
        result
        == "──────────────────────────────────────────────────────────────────────────────\nx — decompose\n\n  ✓ APPLIED            x(x) -> x\n  ✓ proven             x(x) -> x\n  ✗ not extractable    x\n\nDONE:  your source is rewritten. The suite ran green before AND after, and\n       unspecified behaviour was not baked in.\n       Next (optional):  detective converge 'x'"
    )
