"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::_as_list."""

import pytest

from Detective.regime import _as_list


@pytest.mark.detective
def test__as_list_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _as_list("abc", "abc")
    assert result == "abc"


@pytest.mark.detective
def test__as_list_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _as_list("markers", "")
    assert result == []


@pytest.mark.detective
def test__as_list_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _as_list("testpaths", "")
    assert result == []


@pytest.mark.detective
def test__as_list_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _as_list("norecursedirs", "")
    assert result == []
