"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::_covering_test_files."""

import pytest

from Detective.decompose_apply import _covering_test_files


@pytest.mark.detective
def test__covering_test_files_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _covering_test_files(".", {"M_1": ["test_scope_conforms_to_reference[clean_mixed_regime_a]"]})
    assert result == ("tests/test_scope_oracle.py",)
