"""Auto-generated by Detective — warrant-classed tests for Detective/decompose.py::_is_empty_initializer."""

import ast

import pytest

from Detective.decompose import _is_empty_initializer


@pytest.mark.detective
def test__is_empty_initializer_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _is_empty_initializer(ast.parse("total = abs(total)").body[0])
    assert result is False


@pytest.mark.detective
def test__is_empty_initializer_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _is_empty_initializer(ast.parse("items.append(x)").body[0])
    assert result is False


@pytest.mark.detective
def test__is_empty_initializer_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _is_empty_initializer(ast.parse("cfg[k] = v").body[0])
    assert result is False
