"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_final_banner."""

import pytest

from Detective.certify import PytestWiring
from Detective.cli import _final_banner
from Detective.converge import ConvergeResult


@pytest.mark.detective
def test__final_banner_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        ConvergeResult(
            function="m.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=4,
            final_survivors=0,
            iterations=(),
            written_path=None,
            total_mutants=10,
            killed=10,
            value_killed=0,
            remaining=(),
            wiring=PytestWiring(conftest_wired=None, collects=True, passed=1, message=""),
            survivor_report=None,
            functionally_complete=True,
            line_complete=True,
            missing_lines=(),
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=3,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
        )
    )
    # `written_path=None` — nothing of ours reached disk, so the 3 is the minimal COVER over
    # the whole suite, not a file we wrote. Named as such: the bare `· 3 test(s)` this pinned
    # reads as "wrote 3 tests" and sent the reader looking for a path that is not there.
    assert result == "FINAL m.py::f: ✓ COMPLETE (operator universe) · 10/10 killed · minimal cover 3 test(s)"


@pytest.mark.detective
def test__final_banner_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _final_banner(
        ConvergeResult(
            function="m.py::f",
            converged=True,
            at_ceiling=True,
            initial_survivors=4,
            final_survivors=0,
            iterations=(),
            written_path="tests/test_f_synth.py",
            total_mutants=10,
            killed=8,
            value_killed=0,
            remaining=(),
            wiring=PytestWiring(conftest_wired=None, collects=True, passed=1, message=""),
            survivor_report=None,
            functionally_complete=True,
            line_complete=False,
            missing_lines=(8, 10),
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=3,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="",
            param_names=(),
        )
    )
    assert result == "FINAL m.py::f: Incomplete: 2-line gap · 8/10 killed · 1 test(s) → tests/test_f_synth.py"
