"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_may_divert."""

import ast

import pytest

from Detective.cli import _may_divert


@pytest.mark.detective
def test__may_divert_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _may_divert(
        ast.parse(
            "def _f(x, y):\n    total = x + y\n    total = abs(total)\n    if total > 10:\n        raise ValueError('big')\n    return round(total, 2)"
        ).body[0]
    )
    assert result is False
