"""Synth output geography (issue #21): certificates live in their own home,
and a file this target left at the old default is migrated, never orphaned.

The hazard the migration exists for: after the default moved from tests/ to
tests/detective/, a target's OLD synth file would keep running beside the new
one — stale certificate content pytest still collects. Ownership is read from
the header grammar, so a user's hand-written file at the legacy path is
untouchable even when its name collides.
"""

from __future__ import annotations

from pathlib import Path

from Detective.certify import _legacy_synth_path, _owned_by, _write, synth_filename

KEY = "calc.py::add"


def _owned_source() -> str:
    return (
        f'"""Auto-generated by Detective — warrant-classed tests for {KEY}.\n'
        "\n"
        'Regenerated wholesale by `detective converge`."""\n'
        "\n"
        "def test_add_value_0():\n"
        "    assert True\n"
    )


def test_legacy_path_only_for_the_moved_default(tmp_path: Path):
    assert _legacy_synth_path(str(tmp_path / "tests" / "detective"), KEY) == str(
        tmp_path / "tests" / synth_filename(KEY)
    )
    # A custom --write-dir carries no migration story.
    assert _legacy_synth_path(str(tmp_path / "generated"), KEY) is None


def test_migration_removes_the_owned_legacy_file(tmp_path: Path):
    tests = tmp_path / "tests"
    tests.mkdir()
    legacy = tests / synth_filename(KEY)
    legacy.write_text(_owned_source())

    new_path = _write(_owned_source(), str(tests / "detective"), KEY)
    assert Path(new_path) == tests / "detective" / synth_filename(KEY)
    assert not legacy.exists(), "the stale legacy certificate kept running"


def test_migration_never_touches_a_user_file(tmp_path: Path):
    tests = tmp_path / "tests"
    tests.mkdir()
    legacy = tests / synth_filename(KEY)
    legacy.write_text("def test_add_hand_written():\n    assert True\n")

    _write(_owned_source(), str(tests / "detective"), KEY)
    assert legacy.exists(), "a hand-written file at the legacy path was deleted"
    assert not _owned_by(str(legacy), KEY)
