"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_derived_input."""

import pytest

from Detective.cli import _derived_input
from Detective.converge import ConvergeResult
from Detective.decompose_apply import Decomposition, DecompositionApply, Extraction
from Detective.equivalence import SurvivorReport


@pytest.mark.detective
def test__derived_input_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _derived_input(
        DecompositionApply(
            function="quote",
            applied=(),
            proposed=(
                Decomposition(
                    extraction=Extraction(
                        helper_name="_compute_base",
                        params=("weight",),
                        returns=("base",),
                        new_source="import os\n\n\nclass Account:\n    pass\n\n\ndef _compute_base(weight):\n    base = 500\n    return base\n",
                    ),
                    validated=False,
                ),
            ),
            unsafe_blocks=(),
            proof=ConvergeResult(
                function="p.py::quote",
                converged=False,
                at_ceiling=True,
                initial_survivors=69,
                final_survivors=22,
                iterations=(),
                written_path="tests/test_quote_synth.py",
                total_mutants=93,
                killed=71,
                value_killed=0,
                remaining=(),
                wiring=None,
                survivor_report=SurvivorReport(
                    verdicts=(),
                    unclassified=("U0", "U1"),
                    note=None,
                    manual_equivalent=(),
                    inputs_expressible=None,
                ),
                functionally_complete=False,
                line_complete=True,
                missing_lines=(),
                manually_unreachable=0,
                contradicted_line_flags=(),
                missing_line_guards=(),
                redundant_tests=(),
                minimal_test_count=9,
                universe_size=0,
                fast=False,
                coverage_guarantee=1.0,
                signature="quote(weight, distance, tier, rush, insured)",
                param_names=("weight", "distance", "tier", "rush", "insured"),
            ),
        ),
        ConvergeResult(
            function="p.py::quote",
            converged=False,
            at_ceiling=True,
            initial_survivors=69,
            final_survivors=22,
            iterations=(),
            written_path="tests/test_quote_synth.py",
            total_mutants=93,
            killed=71,
            value_killed=0,
            remaining=(),
            wiring=None,
            survivor_report=SurvivorReport(
                verdicts=(),
                unclassified=("U0", "U1"),
                note=None,
                manual_equivalent=(),
                inputs_expressible=None,
            ),
            functionally_complete=False,
            line_complete=True,
            missing_lines=(),
            manually_unreachable=0,
            contradicted_line_flags=(),
            missing_line_guards=(),
            redundant_tests=(),
            minimal_test_count=9,
            universe_size=0,
            fast=False,
            coverage_guarantee=1.0,
            signature="quote(weight, distance, tier, rush, insured)",
            param_names=("weight", "distance", "tier", "rush", "insured"),
        ),
        SurvivorReport(
            verdicts=(), unclassified=("U0", "U1"), note=None, manual_equivalent=(), inputs_expressible=None
        ),
        "p.py::quote",
        "",
        "",
    )
    assert result == [
        "DO THIS:  detective decompose 'p.py::quote' --apply --input \"(<weight>, <distance>, <tier>, <rush>, <insured>)\"",
        "",
        "  · Signature          quote(weight, distance, tier, rush, insured)",
        "",
        "  · Task               Author one real call and pass it as --input.",
        "  · Requirement        It must run. Detective derives every test from it.",
        "                       Values are yours to choose — it will not invent one whose",
        "                       meaning is not in the code. A class from the module goes",
        "                       in as its constructor. Repeatable for another branch.",
    ]

