"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::_layout."""

import pytest

from Detective.regime import _layout


@pytest.mark.detective
def test__layout_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _layout("abc")
    assert result == "scripts"
