"""The FunctionBasis admits per-test witnesses, split ℋ/𝒢 by recorded origin (D1/D5 wiring).

TEST_BASIS §9. `basis_membership` and `BasisWitness` had NO production consumer (G4). Now
`function_basis` populates `admitted`: one witness per test that discharged an obligation, carrying
what it discharged, its `basis_membership` warrant, and its ℋ/𝒢 origin from the recorded authorship
fact. This is the per-test view under the census's aggregate counts — a hand-written test is intent
(ℋ), a Detective-generated one is characterization (𝒢).
"""

from __future__ import annotations

import importlib

from Detective.engine import profile

_cm = importlib.import_module("Detective.certify")


def _repo(tmp_path):
    (tmp_path / "pyproject.toml").write_text('[tool.pytest.ini_options]\ntestpaths = ["tests"]\n')
    (tmp_path / "m.py").write_text("def f(n):\n    if n > 0:\n        return n\n    return -n\n")
    tdir = tmp_path / "tests"
    tdir.mkdir()
    # ℋ — a human's test.
    (tdir / "test_hand.py").write_text("from m import f\n\n\ndef test_pos():\n    assert f(2) == 2\n")
    # 𝒢 — a Detective-headered generated test (no digest stamp → unedited → characterization).
    (tdir / "test_gen.py").write_text(
        f'"""{_cm._HEADER_PREFIX}m.py::f.\n\ngenerated by Detective."""\n'
        "from m import f\n\n\ndef test_neg():\n    assert f(-3) == 3\n"
    )
    return str(tmp_path)


def test_admitted_witnesses_split_hand_written_and_generated_by_origin(tmp_path):
    r = profile("m.py", "f", _repo(tmp_path), use_cache=False)
    b = r.function_basis
    assert len(b.admitted) >= 2, "both covering tests should be admitted witnesses"
    origins = {w.origin for w in b.admitted}
    assert "intent" in origins, "the hand-written test is ℋ (intent)"
    assert "characterization" in origins, "the Detective-headered test is 𝒢 (characterization)"
    # Every admitted witness carries a warrant and discharges at least one obligation.
    for w in b.admitted:
        assert w.warrant in {"proof", "routing", "barred"}
        assert w.discharged.lines or w.discharged.mutation_dims


def test_a_fresh_admissible_cover_warrants_proof(tmp_path):
    r = profile("m.py", "f", _repo(tmp_path), use_cache=False)
    # A fresh run's admissible coverage is `proof` — the only warrant that may enter the basis.
    assert all(w.warrant == "proof" for w in r.function_basis.admitted)


def test_a_warm_verdict_cache_hit_keeps_proof_warrants_not_routing(tmp_path):
    # P1 review: a `complete` basis must rest on PROOF, not routing. The verdict cache stores only
    # gateable certificates keyed on the function/tests/regime, so a hit REPLAYS an established proof
    # over unchanged inputs and regains proof status — it is NOT §2.1's trace-cache routing replay.
    root = _repo(tmp_path)
    profile("m.py", "f", root, use_cache=True)  # populate the verdict cache
    warm = profile("m.py", "f", root, use_cache=True)  # cache hit
    assert getattr(warm, "served_from_cache", False), "the second run must be a cache hit"
    assert warm.function_basis.admitted, "the warm result still carries witnesses"
    assert all(w.warrant == "proof" for w in warm.function_basis.admitted)
