"""Auto-generated by Detective — warrant-classed tests for Detective/converge.py::_witness_property."""

import pytest

from Detective.converge import _witness_property
from Detective.equivalence import Witness


@pytest.mark.detective
def test__witness_property_value_0():
    """VALUE survivor — distinguishing witness (original raises AttributeError: 'int' object has no attribute 'args') (confidence 0.95)."""
    try:
        _result = _witness_property("", -1, "")
    except AttributeError as _exc:
        assert str(_exc) == "'int' object has no attribute 'args'"
    except BaseException as _exc:
        pytest.fail(f"expected AttributeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected AttributeError, but the call returned {_result!r}")


@pytest.mark.detective
def test__witness_property_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _witness_property(
        "m::sign", Witness(args=(0,), original="0", mutant="1", original_value=None), None
    )
    assert (
        repr(result)
        == "ExecutableProperty(category='VALUE', inputs={}, setup_code='from m import sign', assertion_code='result = sign(0)\\nassert result == 0', preconditions=['distinguishing witness (equivalence search)'], confidence=0.95, source_lenses=['witness'], needs_oracle=False, function_key='', mutant_id='', golden_case=None)"
    )
