"""Design-warranted tests for Detective.synthesis.writer.

The load-bearing invariant: what Detective writes is valid, idiomatic pytest.
Plain module-level helpers only (no fixtures).
"""

from __future__ import annotations

import ast

from Detective.synthesis.oracle_light import ExecutableProperty, generate_executable_property
from Detective.synthesis.writer import (
    _collect_imports,
    _one_line,
    _render_test,
    _warrant,
    synthesize_test_module,
)


def _fn(src: str) -> ast.FunctionDef:
    node = ast.parse(src).body[0]
    assert isinstance(node, ast.FunctionDef)
    return node


def test_empty_survivors_returns_empty():
    assert synthesize_test_module("m::f", _fn("def f(x):\n return x"), []) == ""


def test_module_is_valid_python_and_wires_the_test():
    node = _fn("def sub(a, b):\n return a - b")
    src = synthesize_test_module("m::sub", node, [{"category": "SWAP", "mutant_id": "SWAP_0"}])
    ast.parse(src)  # must be valid Python
    assert "from m import sub" in src
    assert "def test_sub_swap_0():" in src
    assert '"""Auto-generated by Detective' in src
    assert "SWAP: parameter order should matter" in src


def test_module_exact_output():
    # pins the whole module template (header, spacing, the always-present pytest
    # import, and the @pytest.mark.detective marker on every generated test)
    node = _fn("def sub(a, b):\n return a - b")
    src = synthesize_test_module("m::sub", node, [{"category": "SWAP", "mutant_id": "SWAP_0"}])
    assert src == (
        '"""Auto-generated by Detective — warrant-classed tests for m::sub."""\n'
        "\n"
        "from m import sub\n"
        "import pytest\n"
        "\n"
        "@pytest.mark.detective\n"
        "def test_sub_swap_0():\n"
        '    """SWAP survivor [SWAP_0] — a != b; non-commutative (confidence 0.6)."""\n'
        "    result_ab = sub(1, 2)\n"
        "    result_ba = sub(2, 1)\n"
        '    assert result_ab != result_ba, "SWAP: parameter order should matter"\n'
    )




def test_no_duplicate_pytest_import():
    # a TYPE property already imports pytest; a needs-oracle property must not
    # add a second `import pytest`.
    node = _fn("def f(x):\n return x")
    props = [
        {"category": "TYPE", "mutant_id": "T0", "diff_summary": "- isinstance(x, str)\n+ True"},
        {"category": "VALUE", "mutant_id": "V0"},
    ]
    assert synthesize_test_module("m::f", node, props).count("import pytest") == 1


def test_render_preserves_blank_lines():
    # a blank line inside the assertion stays blank (not turned into content)
    p = ExecutableProperty("STATE", {}, "", "a = 1\n\nb = 2", [], 0.5)
    assert "    a = 1\n\n    b = 2" in _render_test("f", 0, p)





def test_method_name_dots_become_underscores():
    node = _fn("def reset(self):\n self.x = 1")
    src = synthesize_test_module("m::C.reset", node, [{"category": "STATE", "description": "return_none"}])
    assert "def test_C_reset_state_0():" in src


def test_warrant_names_category_mutant_and_confidence():
    p = generate_executable_property({"category": "SWAP", "mutant_id": "SWAP_2"}, "m::sub", _fn("def sub(a, b):\n return a - b"))
    w = _warrant(p)
    assert "SWAP survivor [SWAP_2]" in w and "confidence 0.6" in w


def test_warrant_no_preconditions():
    p = ExecutableProperty("X", {}, "", "pass", [], 0.5)
    assert "no preconditions" in _warrant(p)


def test_warrant_full_string_with_multiple_preconditions():
    p = ExecutableProperty("SWAP", {}, "", "pass", ["a != b", "non-commutative"], 0.6, mutant_id="SWAP_2")
    assert _warrant(p) == "SWAP survivor [SWAP_2] — a != b; non-commutative (confidence 0.6)."


def test_warrant_full_string_without_mutant_id():
    p = ExecutableProperty("X", {}, "", "pass", ["p"], 0.5)
    assert _warrant(p) == "X survivor — p (confidence 0.5)."


def test_collect_imports_dedupes_and_sorts():
    p1 = ExecutableProperty("X", {}, "from a import x", "pass", [], 0.5)
    p2 = ExecutableProperty("Y", {}, "from a import x\nimport b", "pass", [], 0.5)
    assert _collect_imports([p1, p2]) == ["from a import x", "import b"]


def test_collect_imports_ignores_non_import_setup():
    p = ExecutableProperty("X", {}, "obj = Thing()", "pass", [], 0.5)
    assert _collect_imports([p]) == []


def test_one_line_skips_comment_lines():
    assert _one_line("# a comment\nresult = f()") == "result = f()"


def test_one_line_all_comments_returns_first():
    assert _one_line("# only\n# comments") == "# only"


def test_render_test_indents_multiline_assertion():
    p = ExecutableProperty("STATE", {}, "", "result = f()\nassert result is not None", [], 0.7)
    block = _render_test("f", 3, p)
    assert "def test_f_state_3():" in block
    assert "\n    result = f()" in block
    assert "\n    assert result is not None" in block
    assert "@pytest.mark.skip" not in block  # needs_oracle default False


def test_two_properties_numbered_and_joined():
    node = _fn("def f(x):\n return x")
    src = synthesize_test_module(
        "m::f", node, [{"category": "VALUE", "mutant_id": "V0"}, {"category": "STATE", "description": "return_none"}]
    )
    assert "def test_f_value_0():" in src
    assert "def test_f_state_1():" in src
    assert "import pytest" in src  # VALUE needs oracle -> skip -> pytest imported
    assert src.count("\n\n\n") == 0  # blocks joined by exactly one blank line, not three
    ast.parse(src)


def test_bare_func_key_without_double_colon():
    # rsplit("::", 1)[-1] on a key with no "::" yields the whole name; the [1]
    # mutation would IndexError.
    node = _fn("def f(x):\n return x")
    src = synthesize_test_module("barefunc", node, [{"category": "VALUE", "mutant_id": "V0"}])
    assert "def test_barefunc_value_0():" in src


def test_needs_oracle_property_is_skipped_not_failing():
    node = _fn("def f(x):\n return x")
    src = synthesize_test_module("m::f", node, [{"category": "VALUE", "mutant_id": "VALUE_0"}])
    ast.parse(src)
    assert "@pytest.mark.skip(reason=" in src
    assert "def test_f_value_0():" in src


def test_skip_module_imports_pytest():
    # A @pytest.mark.skip decorator references pytest, so the module must import
    # it — otherwise the generated file NameErrors at collection.
    node = _fn("def f(x):\n return x")
    src = synthesize_test_module("m::f", node, [{"category": "VALUE", "mutant_id": "VALUE_0"}])
    assert "import pytest" in src
    assert src.index("import pytest") < src.index("@pytest.mark.skip")


def test_imports_are_deduped():
    node = _fn("def sub(a, b):\n return a - b")
    src = synthesize_test_module("m::sub", node, [{"category": "SWAP"}, {"category": "SWAP"}])
    assert src.count("from m import sub") == 1

