"""Auto-generated by Detective — warrant-classed tests for Detective/scope.py::_kill_quality_warning."""

import pytest

from Detective.scope import _kill_quality_warning


@pytest.mark.detective
def test__kill_quality_warning_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _kill_quality_warning(1, 2, 3)
    assert result is None
