"""Auto-generated by Detective — warrant-classed tests for Detective/engine.py::_safely_fresh."""

import pytest

from Detective.engine import _safely_fresh


@pytest.mark.detective
def test__safely_fresh_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _safely_fresh((1,), [(1,)])
    assert result is False
