"""Auto-generated by Detective — warrant-classed tests for Detective/capture.py::capture_call_inputs."""

import pytest

from Detective.capture import capture_call_inputs


@pytest.mark.detective
def test_capture_call_inputs_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = capture_call_inputs(1, [None])
    assert result == []
