"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_written_count."""

import pytest

from Detective.cli import _written_count


@pytest.mark.detective
def test__written_count_value_0():
    """VALUE survivor — distinguishing witness (original raises AttributeError: 'int' object has no attribute 'wiring') (confidence 0.95)."""
    try:
        _result = _written_count(-1)
    except AttributeError as _exc:
        assert str(_exc) == "'int' object has no attribute 'wiring'"
    except BaseException as _exc:
        pytest.fail(f"expected AttributeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected AttributeError, but the call returned {_result!r}")
