"""Auto-generated by Detective — warrant-classed tests for Detective/decompose_apply.py::transform_class_id."""

import pytest

from Detective.decompose_apply import transform_class_id


@pytest.mark.detective
def test_transform_class_id_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = transform_class_id()
    assert result == "1.a22af98fa124"
