"""Auto-generated by Detective — warrant-classed tests for Detective/cli.py::_headline."""

import pytest

from Detective.cli import _headline


@pytest.mark.detective
def test__headline_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _headline("abc")
    assert result == "Abc."
