"""Auto-generated by Detective — warrant-classed tests for Detective/regime.py::_is_ours."""

import pytest

from Detective.regime import _is_ours


@pytest.mark.detective
def test__is_ours_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _is_ours("")
    assert result is False
