"""The certify loop — the product's front door.

One pass of the workflow: diagnose a function (behavioral-scope map via Wesker),
and for each unspecified degree of freedom (surviving mutant) synthesize a
warrant-classed pytest test. Optionally write the synthesized module to disk.

Driving to the ceiling is the caller's loop: certify -> write -> re-run tests ->
certify again, until ``at_ceiling``.
"""

from __future__ import annotations

import ast
import os
from collections.abc import Sequence
from dataclasses import dataclass

from .decompose import DecompositionPlan, decompose
from .engine import _resolve, profile
from .scope import ScopeMap, scope_from_profiling
from .synthesis.writer import synthesize_test_module


@dataclass(frozen=True)
class CertifyResult:
    """Outcome of one certify pass."""

    function: str
    scope: ScopeMap
    survivors: int
    at_ceiling: bool
    test_source: str  # "" when at the ceiling or nothing is synthesizable
    written_path: str | None
    decomposition: DecompositionPlan | None = None  # set for entangled (regime-B) functions
    wiring: PytestWiring | None = None  # how the written suite was wired to run under pytest


# A generated test imports its target as ``from <module-under-root> import <fn>``,
# which only resolves when the project root is on sys.path during collection.
# python -m pytest happens to add cwd, but the console-script ``pytest`` does not —
# so a bare consumer repo would collect ImportError. A conftest.py at the project
# root is the standard, invocation-independent fix: pytest imports it and we put
# the root on the path explicitly. We never clobber a consumer's own conftest.
_CONFTEST_MARKER = "# Auto-generated by Detective: makes the project root importable under pytest."
_CONFTEST_BODY = (
    _CONFTEST_MARKER + "\n"
    "import os\n"
    "import sys\n"
    "\n"
    "sys.path.insert(0, os.path.dirname(__file__))\n"
    "\n"
    "\n"
    "def pytest_configure(config):\n"
    "    # Register Detective's marker so `@pytest.mark.detective` is valid (no warning,\n"
    "    # and safe under --strict-markers). Run only generated tests with\n"
    "    # `pytest -m detective`; run only your own with `pytest -m 'not detective'`.\n"
    '    config.addinivalue_line("markers", "detective: test generated by Detective")\n'
)


def ensure_conftest(project_root: str) -> str | None:
    """Wire a root ``conftest.py`` so generated tests' imports resolve under any
    pytest invocation. Returns its path if newly written, or None when a conftest
    already exists (the consumer's own setup wins — we never overwrite it)."""
    path = os.path.join(project_root, "conftest.py")
    if os.path.exists(path):
        return None
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_CONFTEST_BODY)
    return path


@dataclass(frozen=True)
class PytestWiring:
    """What Detective found and did so the generated suite runs in the consumer."""

    conftest_wired: str | None  # path, if Detective just created one
    collects: bool  # did the written suite collect+pass under real pytest?
    passed: int  # number of tests that passed under pytest
    message: str  # the stated, CLI-surfaced diagnosis + fix — read this


def _pytest_available() -> bool:
    """Whether pytest is importable in the interpreter that runs the generated tests
    (the same one ``verify_under_pytest`` shells out to)."""
    import importlib.util

    return importlib.util.find_spec("pytest") is not None


def _wiring_message(
    conftest_wired: str | None, collects: bool, passed: int, pytest_available: bool = True
) -> str:
    """State, in plain language, the wiring gap Detective found and how it fixed it.

    This is the line a first-time user reads to know the generated tests will
    actually run — the fix must be obvious, not implied.
    """
    if conftest_wired:
        fix = (
            f"wired {conftest_wired} — the generated tests import your module by name, "
            f"which the `pytest` console script cannot resolve without the project root "
            f"on sys.path"
        )
    else:
        fix = "conftest.py already present — imports resolve"
    if collects:
        proof = f"verified {passed} test(s) pass under pytest"
    elif not pytest_available:
        # Do NOT misdiagnose a missing runner as a broken import path.
        proof = (
            "⚠ pytest is not installed here, so the written tests cannot be run or verified — "
            "`pip install pytest` (a normal Detective install includes it as a dependency)"
        )
    else:
        proof = "⚠ pytest could NOT collect the generated tests — check the import path"
    return f"pytest wiring: {fix}; {proof}"


def verify_under_pytest(project_root: str, test_path: str | Sequence[str]) -> tuple[bool, int]:
    """Run the test file(s) under REAL pytest (the consumer path, which Wesker's
    direct-call runner bypasses). Returns (collected_and_passed, count).

    ``test_path`` is one path or several: a suite Detective wrote is a single file,
    but the PRE-EXISTING suite that proves a decomposition can span several
    hand-written files (`decompose_apply._covering_test_files`)."""
    import re
    import subprocess
    import sys

    paths = [test_path] if isinstance(test_path, str) else list(test_path)
    if not paths:
        return False, 0

    # ``-o addopts=`` neutralizes the CONSUMER's pyproject addopts: a project that
    # already sets ``-q`` would combine with ours into ``-qq`` (double-quiet), which
    # suppresses the "N passed" summary this parse depends on — reporting 0 passed
    # for a suite that in fact passes. Controlling our own output makes the verifier
    # robust to whatever addopts the target project carries.
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", *paths, "-o", "addopts=", "-q", "-p", "no:cacheprovider"],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    passed = 0
    m = re.search(r"(\d+) passed", proc.stdout)
    if m:
        passed = int(m.group(1))
    ok = proc.returncode == 0 and "error" not in proc.stdout.lower()
    return ok, passed


def wire_pytest(project_root: str, test_path: str) -> PytestWiring:
    """Make the generated suite runnable in the consumer and STATE what was done:
    ensure a root conftest, then verify the tests actually collect+pass under pytest."""
    conftest_wired = ensure_conftest(project_root)
    collects, passed = verify_under_pytest(project_root, test_path)
    return PytestWiring(
        conftest_wired,
        collects,
        passed,
        _wiring_message(conftest_wired, collects, passed, _pytest_available()),
    )


def certify(
    file: str,
    function: str,
    project_root: str = ".",
    *,
    write_dir: str | None = None,
    call_site_inputs: list[dict] | None = None,
) -> CertifyResult:
    """Diagnose ``function`` and synthesize tests for its surviving mutants."""
    root = os.path.abspath(project_root)
    full = file if os.path.isabs(file) else os.path.join(root, file)
    with open(full, encoding="utf-8") as fh:
        tree = ast.parse(fh.read(), filename=full)

    qualname, node = _resolve(tree, function)
    if qualname is None:
        raise LookupError(f"function {function!r} not found in {file}")

    result = profile(file, function, project_root)
    scope = scope_from_profiling(result)
    func_key = f"{os.path.relpath(full, root)}::{qualname}"
    at_ceiling = result.value_survived == 0

    source = ""
    if not at_ceiling:
        source = synthesize_test_module(func_key, node, result.value_survivor_records, call_site_inputs)

    # Entangled functions get a decomposition plan alongside the synthesized tests.
    plan = None
    if scope.regime == "B":
        plan = decompose(node, qualname, tuple(scope.surviving_categories))

    written = None
    if source and write_dir:
        # Resolve write_dir against the project root (not CWD) so tests land in
        # the consumer's tree where their imports resolve — matches converge.
        target = write_dir if os.path.isabs(write_dir) else os.path.join(root, write_dir)
        written = _write(source, target, qualname)
    # Wire the written suite so it runs under real pytest, and state how (see converge).
    wiring = wire_pytest(root, written) if written else None
    return CertifyResult(func_key, scope, result.value_survived, at_ceiling, source, written, plan, wiring)


def _write(source: str, write_dir: str, qualname: str) -> str:
    """Write synthesized source to ``write_dir/test_<qualname>_synth.py``; return the path,
    or "" when there was nothing to write.

    Empty source means we contribute no test — e.g. converge's minimize pass dropped every
    test it generated as redundant against a suite that already covers the target. Writing a
    0-byte file there would claim a product that does not exist, and leaving a stale one from
    an earlier pass of the SAME run would ship the pre-minimize content the pass just
    rejected. This path is Detective's own regeneratable product (§8), never user data, so
    clearing it is ours to do."""
    os.makedirs(write_dir, exist_ok=True)
    safe = qualname.replace(".", "_")
    path = os.path.join(write_dir, f"test_{safe}_synth.py")
    if not source.strip():
        if os.path.exists(path):
            os.remove(path)
        return ""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(source)
    return path
