"""The certify loop — the product's front door.

One pass of the workflow: diagnose a function (behavioral-scope map via Wesker),
and for each unspecified degree of freedom (surviving mutant) synthesize a
warrant-classed pytest test. Optionally write the synthesized module to disk.

Driving to the ceiling is the caller's loop: certify -> write -> re-run tests ->
certify again, until ``at_ceiling``.
"""

from __future__ import annotations

import ast
import hashlib
import os
from collections.abc import Sequence
from dataclasses import dataclass

from .decompose import DecompositionPlan, decompose
from .engine import _resolve, profile
from .scope import ScopeMap, scope_from_profiling
from .synthesis.writer import synthesize_test_module


@dataclass(frozen=True)
class CertifyResult:
    """Outcome of one certify pass."""

    function: str
    scope: ScopeMap
    survivors: int
    at_ceiling: bool
    test_source: str  # "" when at the ceiling or nothing is synthesizable
    written_path: str | None
    decomposition: DecompositionPlan | None = None  # set for entangled (regime-B) functions
    wiring: PytestWiring | None = None  # how the written suite was wired to run under pytest


# The marker a generated test carries, and the line that makes it legal under --strict-markers.
_MARKER_NAME = "detective"
_MARKER_SPEC = f'"{_MARKER_NAME}: test generated by Detective"'
_PYTEST_SECTION = "[tool.pytest.ini_options]"


def ensure_marker_registered(project_root: str, resolved: tuple[str, str, str] | None = None) -> str | None:
    """Make ``@pytest.mark.detective`` legal — DECLARATIVELY, in ``pyproject.toml``.

    ``resolved`` overrides the config target ``(path, dialect, section)``: the migrate flow passes the
    file pytest ITSELF named when it diverges from the static mirror (por qué no los dos), so the
    marker lands where pytest actually reads. Default None → resolve by the static precedence mirror.

    This used to write a root ``conftest.py``. That was a mistake with a long tail. A generated
    conftest.py and an existing ``tests/conftest.py`` both import as the module ``conftest`` (any
    tree whose ``tests/`` is not a package — which is most of them), and in a process that imports
    both, the second one raises ``import file mismatch``. Plain pytest tolerates it; Detective's
    OWN in-process live session does not, so it died, silently fell back to collect-only
    discovery, and every fixture-taking test vanished from the profile. Surviving DOF was then
    overstated on exactly the repos careful enough to use fixtures — and Detective did it to
    itself, in its own repo, for as long as the feature existed.

    A marker is configuration. Configuration belongs in the config file, where it is declarative,
    idempotent, greppable, and — the whole point — cannot become a second module named
    ``conftest``. Nothing this writes can collide with anything.

    The sys.path insert the old conftest also did is not replaced, and is not missed: a generated
    test now imports its target by the name the REST of the repo imports it by (see
    ``importable_module``), so it resolves however the repo's own suite already resolves. If that
    name does not resolve at all, the shadow guard refuses before we ever get here.

    Returns a one-line description of what changed, or None if nothing needed doing. Never
    rewrites an existing markers list beyond appending, and never touches a consumer's conftest.
    """
    from .regime import pytest_config

    # WHICH config file, asked of pytest's precedence rather than assumed. This wrote
    # `pyproject.toml` unconditionally, and `pytest.ini` outranks `[tool.pytest.ini_options]` (as
    # do `tox.ini` and `setup.cfg`). On a repo with one, the marker landed in a file pytest prints
    # a warning about ignoring, `--strict-markers` then rejected every generated test AT
    # COLLECTION, and the run that wrote them reported `✓ MIGRATED`. Declarative is only half the
    # lesson the conftest bug taught; the other half is that a declaration has to be somewhere the
    # thing reading it will look.
    resolved = resolved if resolved is not None else pytest_config(project_root)
    if resolved is None:
        return None  # nothing to declare into, and creating a config file is not ours to do
    path, dialect, section = resolved
    try:
        with open(path, encoding="utf-8") as fh:
            source = fh.read()
    except OSError:
        return None
    if f"{_MARKER_NAME}:" in source:
        return None  # already registered — idempotent, in either dialect
    entry = _MARKER_SPEC if dialect == "toml" else f"{_MARKER_NAME}: test generated by Detective"
    if section in source:
        # Append INTO the existing markers list rather than beside it: a second `markers =` key
        # silently replaces the first in both dialects, so declaring ours would UNDECLARE every
        # marker the repo already had — turning one missing marker into all of them, under the
        # same `--strict-markers` that made this matter.
        updated = _append_marker(source, section, entry, dialect)
        what = f"registered the `{_MARKER_NAME}` marker in {section} of {os.path.basename(path)}"
    else:
        block = f"markers = [{entry}]" if dialect == "toml" else f"markers =\n    {entry}"
        updated = f"{source.rstrip()}\n\n{section}\n{block}\n"
        what = f"added {section} to {os.path.basename(path)} with the `{_MARKER_NAME}` marker"
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(updated)
    except OSError:
        return None
    return what


def _append_marker(source: str, section: str, entry: str, dialect: str) -> str:
    """``source`` with ``entry`` added to ``section``'s markers — extending a list, never
    shadowing it. Falls back to declaring the key when the section has no markers yet."""
    head, sep, tail = source.partition(section)
    if not sep:
        return source
    lines = tail.split("\n")
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("markers"):
            continue
        if dialect != "toml":
            lines[i] = f"{line}\n    {entry}"  # ini: one marker per indented line
        elif "[]" in line:
            lines[i] = line.replace("[]", f"[{entry}]")
        elif "[" in line and "]" in line:  # single-line array: markers = ["a: …"]
            lines[i] = line.replace("]", f", {entry}]", 1)
        else:  # multi-line array: ours goes after the opening bracket
            lines[i] = f"{line}\n    {entry},"
        return head + sep + "\n".join(lines)
    block = f"markers = [{entry}]" if dialect == "toml" else f"markers =\n    {entry}"
    return f"{head}{sep}\n{block}" + tail


@dataclass(frozen=True)
class PytestWiring:
    """What Detective found and did so the generated suite runs in the consumer."""

    conftest_wired: str | None  # path, if Detective just created one
    collects: bool  # did the written suite collect+pass under real pytest?
    passed: int  # number of tests that passed under pytest
    message: str  # the stated, CLI-surfaced diagnosis + fix — read this
    # The typed verification behind ``collects``/``passed`` (issue #38) — distinguishes
    # tests_failed / collection_failed / runner_missing / timed_out / no_tests. Optional so
    # older constructions (and any external caller) keep working; wire_pytest always sets it.
    verification: PytestVerification | None = None


def _pytest_available() -> bool:
    """Whether pytest is importable in the interpreter that runs the generated tests
    (the same one ``verify_under_pytest`` shells out to)."""
    import importlib.util

    return importlib.util.find_spec("pytest") is not None


def marker_disposition(registered: str | None, has_config: bool) -> str:
    """Which wiring state the marker step reached (issue #32) — explicit, never inferred from a
    fused ``None``. ``ensure_marker_registered`` returns a description when it WROTE the marker and
    None otherwise, but None conflated 'already declared' with 'there is no pytest config to declare
    into'. Split by whether a config exists: a written marker is ``registered_now``; None WITH a
    config is ``already_declared``; None with NO config is ``no_config`` — the case that must never
    read as 'nothing to change', because plain pytest then warns on every generated test until the
    user runs ``detective regime --migrate``. Pure — Detective-pinned."""
    if registered:
        return "registered_now"
    return "already_declared" if has_config else "no_config"


def _wiring_message(
    disposition: str, registered: str | None, collects: bool, passed: int, pytest_available: bool = True
) -> str:
    """State, in plain language, the wiring gap Detective found and how it fixed it.

    This is the line a first-time user reads to know the generated tests will
    actually run — the fix must be obvious, not implied. Consumes the explicit
    ``disposition`` (issue #32), never re-deriving it from a truthy/falsy ``registered``.
    """
    if disposition == "registered_now":
        fix = (
            f"{registered} — the generated tests carry `@pytest.mark.detective`, which "
            f"`--strict-markers` rejects unless it is declared. Declared in config, so nothing "
            f"new is importable and nothing can collide"
        )
    elif disposition == "no_config":
        # The false-positive #32 fixes: there is NO config, so the marker is NOT declared, and plain
        # pytest warns on every generated test. Name the working next action rather than "nothing to
        # change" — and never a conftest.py, which the declarative design deliberately avoids.
        fix = (
            "no pytest config here, so `@pytest.mark.detective` is undeclared — plain pytest will "
            "warn on every generated test. Run `detective regime --migrate` to declare it (writes a "
            "minimal pyproject marker; never a conftest.py)"
        )
    else:  # already_declared
        fix = "pytest config already declares the marker — nothing to change"
    if collects:
        proof = f"verified {passed} test(s) pass under pytest"
    elif not pytest_available:
        # Do NOT misdiagnose a missing runner as a broken import path.
        proof = (
            "⚠ pytest is not installed here, so the written tests cannot be run or verified — "
            "`pip install pytest` (a normal Detective install includes it as a dependency)"
        )
    else:
        proof = "⚠ pytest could NOT collect the generated tests — check the import path"
    return f"pytest wiring: {fix}; {proof}"


_VERIFY_TIMEOUT_S = 120.0


def verify_timeout_s(remaining_s: float | None, cap_s: float = _VERIFY_TIMEOUT_S) -> float:
    """The pytest-verification subprocess timeout, clamped to the aggregate wall (issue #31, pure — pinned).

    The final proof-basis verification is ONE phase under converge's single aggregate deadline, not a
    fresh 120s grant. A run that finished mutation with milliseconds left on the wall used to spawn a
    full ``_VERIFY_TIMEOUT_S`` pytest and overrun the deadline by up to two minutes. So the subprocess
    timeout is the SMALLER of the fixed cap and whatever wall time remains:

    * ``remaining_s`` is None — no wall was declared (the standalone ``certify`` / ``verify-rewrite``
      callers) — use the full ``cap_s``, preserving pre-deadline behaviour.
    * ``remaining_s`` > 0 — clamp to ``min(cap_s, remaining_s)``: never more than the cap, and never
      more than the wall still allows.
    * ``remaining_s`` <= 0 — the wall is already exhausted; return ``0.0``, the signal to the caller to
      withhold the certificate rather than spawn past the deadline.

    Never returns negative (a negative timeout to ``subprocess.run`` raises); ``0.0`` is the floor."""
    if remaining_s is None:
        return cap_s
    if remaining_s <= 0:
        return 0.0
    return min(cap_s, remaining_s)


@dataclass(frozen=True)
class PytestVerification:
    """The typed outcome of running the proof suite under real pytest — the certificate's
    verification axis (issue #38). A single ``ok`` boolean collapsed five distinct outcomes into
    one "could not collect", so a suite that COLLECTED AND FAILED could still print ✓ COMPLETE.
    Each is now its own status a certificate can serialize and a gate can read, with the counts and
    paths that produced it.

    ``basis`` records WHAT was verified: ``"generated-only"`` (just the file Detective wrote) versus
    ``"target-complete"`` (the generated file plus the hand-written files that supplied target kills)
    — because generated-only verification must never be presented as proof of the larger basis.
    """

    status: str  # passed | tests_failed | collection_failed | runner_missing | timed_out | no_tests
    exit_code: int | None  # pytest's return code; None when it never ran (missing runner / timeout)
    collected: int
    passed: int
    failed: int
    errors: int
    paths: tuple[str, ...]
    basis: str
    # The runner's OWN node-ID basis (#58): each test the FINAL verification collected as
    # (node_id, content digest), captured by the `Wesker.verification_manifest` plugin IN the
    # verification subprocess — the complete proof suite (generated + hand-written) addressed as
    # pytest addresses it, under the consumer's own regime. Empty when the plugin could not emit
    # (older Wesker, a run that never collected). The receipt freezes THIS rather than a kill-
    # matrix-derived file set, so a rewrite that drops a line/arc-only owner is caught by identity.
    node_basis: tuple[tuple[str, str], ...] = ()

    @property
    def ok(self) -> bool:
        """Green: pytest ran the basis and every collected test passed (at least one ran).

        The ONLY status that admits a certificate. tests_failed / collection_failed name affirmative
        red; runner_missing / timed_out / no_tests are UNVERIFIED — absence of evidence is not a
        pass, so none of them is ``ok`` either."""
        return self.status == "passed"


def run_pytest_verification(
    project_root: str,
    test_path: str | Sequence[str],
    *,
    basis: str = "generated-only",
    deadline_s: float | None = None,
) -> PytestVerification:
    """Run the proof suite under real pytest and CLASSIFY the outcome (issue #38).

    Distinguishes — by pytest's own return code, the authoritative signal — a green run from a
    test failure (rc 1), a collection/import error (rc 2), no tests collected (rc 5), a missing
    runner, and a timeout. Counts are parsed from the summary for the report; the STATUS is the
    return code, not a substring, so "collected and failed" can never read as "could not collect".

    ``deadline_s`` is the aggregate-wall time REMAINING (issue #31): this verification is one phase
    under converge's single deadline, so its subprocess timeout is clamped to the wall via
    :func:`verify_timeout_s`, never a fresh 120s that would overrun it. None (the standalone callers)
    keeps the full cap. An already-exhausted wall (``<= 0``) withholds the certificate WITHOUT spawning
    — a fresh pytest there would run minutes past the deadline the caller already blew.
    """
    import re
    import subprocess
    import sys

    paths = [test_path] if isinstance(test_path, str) else list(test_path)
    if not paths:
        return PytestVerification("no_tests", None, 0, 0, 0, 0, (), basis)
    if not _pytest_available():
        return PytestVerification("runner_missing", None, 0, 0, 0, 0, tuple(paths), basis)
    timeout = verify_timeout_s(deadline_s)
    if timeout <= 0:
        # The aggregate wall was exhausted before verification could start; spawning here would
        # overrun the deadline. Unverified is not a pass — withhold, honestly, as a timeout.
        return PytestVerification("timed_out", None, 0, 0, 0, 0, tuple(paths), basis)
    import json
    import os
    import tempfile

    # #58: capture the runner's node-ID basis from THIS verification's real collection (the complete
    # proof suite under the consumer's own regime) via a subprocess plugin — the in-process manifest
    # ContextVar cannot cross a process boundary. Defensive: a missing/older Wesker writes nothing.
    _mfd, _manifest_path = tempfile.mkstemp(suffix=".json", prefix="wesker_manifest_")
    os.close(_mfd)
    _env = {**os.environ, "WESKER_MANIFEST_OUT": _manifest_path}

    def _read_node_basis() -> tuple[tuple[str, str], ...]:
        try:
            with open(_manifest_path, encoding="utf-8") as _fh:
                data = json.load(_fh)
            return tuple((str(n), str(d)) for n, d in data.get("node_basis", ()) if n)
        except (OSError, ValueError, TypeError):
            return ()
        finally:
            try:
                os.remove(_manifest_path)
            except OSError:
                pass

    try:
        # Run under the project's OWN regime — do NOT clear its addopts (#58). The addopts ARE the
        # regime a certificate claims: `--strict-markers`, `-W error`, a required `-p plugin`, all
        # decide whether the suite can even collect and run. `-o addopts=` was added only to stop
        # the target's `-q` from doubling with ours into `-qq` (which suppresses the "N passed"
        # summary this parse reads), but it also stripped every pass/fail-affecting option — so a
        # suite that FAILS its own regime read as `passed`, an unsound false certificate
        # (reproduced: `addopts = --strict-markers` + an unregistered marker returns rc 2 natively,
        # yet verification said `passed`). The real fix for the doubling is to add no `-q` of our
        # own, not to erase the regime: the STATUS comes from pytest's return code (see
        # `pytest_status`), and the count only distinguishes passed-from-empty at rc 0, where the
        # summary survives at the target's own verbosity. A target that sets `-qq` itself falls to
        # `no_tests` — a withheld certificate, the safe direction, never a false pass.
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "pytest",
                *paths,
                "-p",
                "Wesker.verification_manifest",  # #58: emit this collection's node-ID basis to JSON
                "-p",
                "no:cacheprovider",
            ],
            cwd=project_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout,
            env=_env,
        )
    except subprocess.TimeoutExpired:
        _read_node_basis()  # cleanup only; a timed-out run has no admissible basis
        return PytestVerification("timed_out", None, 0, 0, 0, 0, tuple(paths), basis)
    out = proc.stdout + "\n" + proc.stderr

    def _n(word: str) -> int:
        m = re.search(rf"(\d+) {word}", out)
        return int(m.group(1)) if m else 0

    passed, failed, errors = _n("passed"), _n("failed"), (_n("errors") or _n("error"))
    status = pytest_status(proc.returncode, passed)
    return PytestVerification(
        status,
        proc.returncode,
        passed + failed + errors,
        passed,
        failed,
        errors,
        tuple(paths),
        basis,
        node_basis=_read_node_basis(),
    )


def pytest_status(returncode: int, passed: int) -> str:
    """Map pytest's exit code to a typed verification status (issue #38, pure — Detective-pinned).

    The return code is the AUTHORITATIVE classifier, never a substring of stdout: parsing "error"
    out of the text collapsed a real test failure into "could not collect", which is the misreport
    that let a red suite print ✓ COMPLETE. pytest's codes: 0 all passed, 1 tests failed, 2
    collection/usage error, 5 no tests collected. rc 0 with zero collected is ``no_tests`` (a green
    run of an empty basis is not a pass); any unlisted code is treated as not-green (``tests_failed``)
    so an unknown failure never reads as admissible.
    """
    if returncode == 0:
        return "passed" if passed > 0 else "no_tests"
    if returncode == 1:
        return "tests_failed"
    if returncode == 2:
        return "collection_failed"
    if returncode == 5:
        return "no_tests"
    return "tests_failed"


def verify_under_pytest(project_root: str, test_path: str | Sequence[str]) -> tuple[bool, int]:
    """Run the test file(s) under REAL pytest (the consumer path, which Wesker's
    direct-call runner bypasses). Returns (collected_and_passed, count).

    ``test_path`` is one path or several: a suite Detective wrote is a single file,
    but the PRE-EXISTING suite that proves a decomposition can span several
    hand-written files (`decompose_apply._covering_test_files`).

    Compatibility shim over :func:`run_pytest_verification`: the ``(ok, passed)`` tuple is what
    ``_suite_green`` needs; every caller that must distinguish tests_failed from a collection error
    or a missing runner (issue #38) calls the typed function directly."""
    v = run_pytest_verification(project_root, test_path)
    return v.ok, v.passed


def wire_pytest(project_root: str, test_path: str) -> PytestWiring:
    """Make the generated suite runnable in the consumer and STATE what was done: declare the
    marker in pyproject, then verify the tests actually collect+pass under pytest."""
    from .regime import pytest_config

    conftest_wired = ensure_marker_registered(project_root)
    # #32: distinguish 'wrote it' / 'already declared' / 'no config here' explicitly — pytest_config
    # is None exactly when there is no config to declare into, which None-as-registered could not say.
    disposition = marker_disposition(conftest_wired, pytest_config(project_root) is not None)
    verification = run_pytest_verification(project_root, test_path, basis="generated-only")
    return PytestWiring(
        conftest_wired,
        verification.ok,
        verification.passed,
        _wiring_message(
            disposition, conftest_wired, verification.ok, verification.passed, _pytest_available()
        ),
        verification,
    )


def certify(
    file: str,
    function: str,
    project_root: str = ".",
    *,
    write_dir: str | None = None,
    call_site_inputs: list[dict] | None = None,
) -> CertifyResult:
    """Diagnose ``function`` and synthesize tests for its surviving mutants."""
    root = os.path.abspath(project_root)
    full = file if os.path.isabs(file) else os.path.join(root, file)
    with open(full, encoding="utf-8") as fh:
        tree = ast.parse(fh.read(), filename=full)

    qualname, node = _resolve(tree, function)
    # Both, as in `converge`: `_resolve` returns them together, so checking one leaves the
    # other `... | None` for every use below (`synthesize_test_module`, `decompose`).
    if qualname is None or node is None:
        raise LookupError(f"function {function!r} not found in {file}")

    result = profile(file, function, project_root)
    scope = scope_from_profiling(result)
    func_key = f"{os.path.relpath(full, root)}::{qualname}"
    at_ceiling = result.value_survived == 0

    source = ""
    if not at_ceiling:
        source = synthesize_test_module(func_key, node, result.value_survivor_records, call_site_inputs)

    # Entangled functions get a decomposition plan alongside the synthesized tests.
    plan = None
    if scope.regime == "B":
        plan = decompose(node, qualname, tuple(scope.surviving_categories))

    written = None
    if source and write_dir:
        # Resolve write_dir against the project root (not CWD) so tests land in
        # the consumer's tree where their imports resolve — matches converge.
        target = write_dir if os.path.isabs(write_dir) else os.path.join(root, write_dir)
        written = _write(source, target, func_key, root)
    # Wire the written suite so it runs under real pytest, and state how (see converge).
    wiring = wire_pytest(root, written) if written else None
    return CertifyResult(func_key, scope, result.value_survived, at_ceiling, source, written, plan, wiring)


def _sha10(text: str) -> str:
    """Ten hex characters of SHA-256 — the disambiguating half of a synth basename.

    Ten rather than eight: a birthday collision moves from roughly sixty-five thousand targets
    to roughly a million, and eight was close enough to a large monorepo to be worth the two
    extra characters. Not security-sensitive; `usedforsecurity=False` says so to the reader and
    to any FIPS-restricted build that would otherwise refuse the call.
    """
    return hashlib.sha256(text.encode("utf-8"), usedforsecurity=False).hexdigest()[:10]


def _readable_stem(func_key: str) -> str:
    """The human-facing half of a synth basename — lossy by design, never the identity.

    Flattens the path separators and punctuation a filename cannot carry. It is NOT injective
    and is not asked to be: `/ \\ . - space` all become `_`, so `a/b.py::c` and `a_b.py::c`
    reduce to one stem. Injectivity is the digest's job (:func:`synth_filename`); this exists
    only so a human can tell at a glance which target a file belongs to.
    """
    module, _, qualname = func_key.partition("::")
    # Strip `.py` from the MODULE half before flattening — doing it after joining leaves the
    # extension mid-string, where `removesuffix` is a no-op and `orphan.py::tier_price` becomes
    # `test_orphan_py_tier_price_synth.py`. A bare name (no `::`) is used as-is, which is what
    # a direct `_write(..., "reset")` caller passes.
    stem = f"{module.removesuffix('.py')}_{qualname}" if qualname else module.removesuffix(".py")
    for sep in ("/", "\\", ".", "-", " "):
        stem = stem.replace(sep, "_")
    return stem.strip("_")


def undigested_synth_filename(func_key: str) -> str:
    """The pre-digest basename this target used before #61 — for migration only.

    Kept so `_write` can retire a file THIS target wrote under the old scheme. Without it the
    old file keeps running beside the new one: pytest collects both, and the stale certificate
    content is scored as if current.
    """
    return f"test_{_readable_stem(func_key)}_synth.py"


def synth_filename(func_key: str) -> str:
    """The synth suite's basename for ``file.py::qualname`` — readable stem plus a key digest.

    It was derived from the qualname alone, so `alpha.py::load` and `beta.py::load` both
    claimed ``test_load_synth.py`` and the second converge overwrote the first's suite —
    measured: alpha went from `✓ COMPLETE 13/13` to `0.0% killed, 10 real gaps`, silently, with
    beta reporting success. Deriving it from the whole key fixed THAT collision and left a
    subtler one: the flattening is many-to-one, so `a/b.py::c`, `a_b.py::c`, `a-b.py::c` and
    `a b.py::c` still named one file (#61).

    The digest is over the EXACT func_key, so distinct targets get distinct names by
    construction rather than by hoping their punctuation differs. Ten hex characters — a
    birthday collision needs on the order of a million targets in one write dir, which is far
    past where a shared directory is the problem.

    IT IS NOT A PROOF, and it does not have to be. A digest collision would produce the same
    filename for two targets, and `write_disposition` then REFUSES rather than overwriting,
    because ownership is read from the header the file carries and never inferred from its
    name. Probabilistic naming plus a deterministic ownership check composes to "no silent
    loss" — which is the property that matters — where either alone does not.
    """
    return f"test_{_readable_stem(func_key)}_{_sha10(func_key)}_synth.py"


def _legacy_synth_path(write_dir: str, func_key: str) -> str | None:
    """The pre-issue-#21 location of this target's synth file (the parent of a
    ``.../detective`` write dir), or None when the write dir is not the moved
    default — a custom --write-dir carries no migration story."""
    norm = os.path.normpath(write_dir)
    if os.path.basename(norm) != "detective":
        return None
    # The UNDIGESTED name, because a file in the pre-#21 location was necessarily written
    # before #61 renamed anything. Building this from `synth_filename` would look for a name
    # that has never existed there and quietly leave the real stale file collecting.
    return os.path.join(os.path.dirname(norm), undigested_synth_filename(func_key))


_HEADER_PREFIX = "Auto-generated by Detective — warrant-classed tests for "


def generated_owner(path: str) -> str:
    """The func_key a generated file CLAIMS, or "" when the file is not ours (#61).

    `_owned_by` answered one bit — is this mine — which cannot tell a USER's file apart from
    ANOTHER TARGET's generated file. Both are "not mine", and they call for opposite responses:
    one means a human's work is sitting where we are about to write, the other means two targets
    normalised to the same filename and this is our own collision. A refusal that cannot say
    which sends the reader to the wrong investigation.

    Read from the header grammar `render_module` writes, never from the filename — the naming
    scheme is explicitly free to change, and a file's owner is a property of its contents.
    Unreadable or unparseable returns "": we cannot claim a file we cannot read, and the safe
    answer is the one that stops us touching it.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            tree = ast.parse(fh.read(), filename=path)
    except (OSError, SyntaxError):
        return ""
    doc = ast.get_docstring(tree)
    if not doc:
        return ""
    first = doc.strip().splitlines()[0]
    if not first.startswith(_HEADER_PREFIX) or not first.endswith("."):
        return ""
    return first[len(_HEADER_PREFIX) : -1]


def _owned_by(path: str, func_key: str) -> bool:
    """True when ``path`` is a Detective-generated file owned by ``func_key``.

    Derived from :func:`generated_owner` rather than re-reading the header: two readers of one
    grammar is the defect class this repo treats as structural, and it is how the same file
    could be judged ours by one call site and foreign by another.
    """
    return generated_owner(path) == func_key


class GeneratedSuiteCollision(RuntimeError):
    """A generated suite's destination is occupied by a file this target does not own (#61).

    Raised rather than silently resolved. The alternative — writing somewhere else — makes the
    collision invisible, and the alternative to THAT was what shipped: overwriting whatever was
    there, which for a user's own tests is data loss with no report of any kind.

    A dedicated type so a caller can catch it precisely; giving it a typed surface in the CLI,
    rather than the traceback it currently produces, is the same work #57 did for receipts and
    is not done here.
    """


def write_disposition(exists: bool, claimed_owner: str, func_key: str) -> str:
    """Whether a generated suite may replace what is at its destination (#61, pure — pinned).

    `_write` checked ownership before deleting the LEGACY sibling and then removed or
    overwrote the PRIMARY path with no check at all — while the comment two lines above it read
    "Ownership is checked by the header grammar, never assumed from the name; user files are
    untouchable." The guard existed; it was applied to the wrong path.

    That matters because `synth_filename` is NOT INJECTIVE. It flattens ``/ \\ . - space`` all to
    ``_``, so ``a/b.py::c``, ``a_b.py::c``, ``a-b.py::c`` and ``a b.py::c`` name one file. A
    collision therefore lands silently on whatever is already there, and the same normalisation
    can land on a HUMAN's ``test_a_b_c_synth.py``.

    Three answers, because the two refusals want different messages and different fixes:

    * ``write``           — nothing there, or the file already claims this target.
    * ``refuse_foreign``  — another TARGET's generated file. Our collision, our bug: the reader
      needs the other func_key, not a warning about their own tests.
    * ``refuse_unowned``  — no Detective header at all. Someone's own file, and the only
      response that is not data loss is to stop.

    Refusing rather than renaming is deliberate for this step. Picking a different name would
    make the collision invisible again — the second target would quietly write elsewhere and
    nobody would learn the normalisation is ambiguous. Disambiguating the NAME is the separate
    fix; this one makes the ambiguity impossible to lose.
    """
    if not exists or claimed_owner == func_key:
        return "write"
    return "refuse_unowned" if not claimed_owner else "refuse_foreign"


_CONTENT_DIGEST_PREFIX = "# detective-content-sha256: "


def _stamp_content_digest(source: str) -> str:
    """Prepend a body-content digest comment so a later HUMAN edit of this generated file is
    OBSERVABLE (#X5/G5). The digest covers ``source`` — the file WITHOUT this line — which solves the
    self-reference: the reader strips the first line and re-hashes the rest. A comment before the
    module docstring is inert (ast still finds the docstring, so ``generated_owner`` reads the header
    unchanged), and it travels WITH the file, so the intent signal survives a ``.detective`` wipe or
    a move — unlike a sidecar store.
    """
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    return f"{_CONTENT_DIGEST_PREFIX}{digest}\n{source}"


def _content_digest_status(path: str) -> tuple[bool, bool]:
    """``(has_recorded_digest, digest_matches)`` for the file — the I/O behind the edited signal.

    No digest line → ``(False, False)``: a file written before X5, or one whose digest line a human
    removed, carries no recorded fact and is never called edited. Otherwise strip the stamped first
    line, re-hash the body, and compare to the recorded digest.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            content = fh.read()
    except OSError:
        return False, False
    if not content.startswith(_CONTENT_DIGEST_PREFIX):
        return False, False
    line, _, body = content.partition("\n")
    recorded = line[len(_CONTENT_DIGEST_PREFIX) :].strip()
    return True, hashlib.sha256(body.encode("utf-8")).hexdigest() == recorded


def content_edited(has_digest: bool, digest_matches: bool) -> bool:
    """Has a human taken over a generated file since Detective wrote it? (#X5/G5 — pure, pinned).

    Edited ONLY when Detective recorded a digest AND the file no longer matches it. A MISSING record
    means the edit status was never measured — NOT edited: a generated file reads ``characterization``
    until a POSITIVE edit signal exists, and is never flipped to ``intent`` by the mere absence of a
    record. That is the §2.3 discipline — "we did not measure this" must not manufacture a verdict.
    """
    return has_digest and not digest_matches


def witness_origin(authorship: str, edited: bool) -> str:
    """Which half of the Sandwich a test's evidence is (§2.3, #D5 — pure, pinned).

    Set from a RECORDED authorship fact — the file's Detective header via :func:`generated_owner` —
    never a path glob (`tests/detective/` and `@pytest.mark.detective` are an AUTHORSHIP proxy, not
    an intent one, and break in both directions). Named codes, because "we did not measure this" and
    "we measured it and it is clean" must never render identically (§2.3):

      authorship  "generated"    Detective wrote this file (a synth header claims a func_key)
                  "hand_written"  a readable test file with NO Detective header — a human's
                  "unreadable"    the file could not be read/parsed — no recorded fact
      edited      True when a "generated" file's content no longer matches what Detective wrote
                  (a human took it over); irrelevant to the other authorships.

    Returns the witness origin:
      "characterization"  generated AND unedited — pins what the code DOES, may already be wrong (𝒢)
      "intent"            hand-written, OR generated-but-edited — a human's stated intent (ℋ)
      "unattributed"      unreadable — reported separately, NEVER counted as either half
    """
    if authorship == "unreadable":
        return "unattributed"
    if authorship == "hand_written":
        return "intent"
    return "intent" if edited else "characterization"


def witness_origin_of(path: str) -> str:
    """The witness origin of the test file at ``path`` (#D5 — accessor over the pinned
    :func:`witness_origin`; the accessor keeps the I/O, the decision holds no I/O).

    Authorship is the RECORDED fact the file carries: a Detective header (``generated_owner``) marks
    a generated suite, its absence on a readable file marks a human's, and a file that cannot be read
    or parsed yields no fact at all. ``edited`` is now OBSERVABLE (#X5): ``_write`` stamps a
    body-content digest into the file, so a human takeover flips a generated file's origin from
    ``characterization`` to ``intent`` when the current body no longer matches what Detective wrote.
    A file without a stamped digest (written before X5, or with the line removed) is not called
    edited — the absence of a record is not evidence of a change.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            ast.parse(fh.read(), filename=path)
    except (OSError, SyntaxError):
        return witness_origin("unreadable", False)
    edited = content_edited(*_content_digest_status(path))
    return witness_origin("generated" if generated_owner(path) else "hand_written", edited)


def witness_origin_of_nodeid(root: str, test_id: str) -> str:
    """The witness origin (ℋ/𝒢) of the test named by a pytest NODEID (#D5 accessor).

    Resolves the file segment — a live ``file.py::name`` (rootdir-relative) or a hand-rolled loader's
    ``legacy:/abs/file.py::name`` — against ``root``, then reads its recorded authorship via
    :func:`witness_origin_of`. The ONE place the nodeid→file resolution lives, so ``audit``'s origin
    census and the ``FunctionBasis`` admitted witnesses attribute the same file the same way.
    """
    rel = test_id.split("::", 1)[0]
    if rel.startswith("legacy:"):
        rel = rel[len("legacy:") :]
    return witness_origin_of(rel if os.path.isabs(rel) else os.path.join(os.path.abspath(root), rel))


def _write(source: str, write_dir: str, func_key: str, project_root: str | None = None) -> str:
    """Write synthesized source to ``write_dir/`` under :func:`synth_filename`; return the path,
    or "" when there was nothing to write.

    Empty source means we contribute no test — e.g. converge's minimize pass dropped every
    test it generated as redundant against a suite that already covers the target. Writing a
    0-byte file there would claim a product that does not exist, and leaving a stale one from
    an earlier pass of the SAME run would ship the pre-minimize content the pass just
    rejected. This path is Detective's own regeneratable product (§8), never user data, so
    clearing it is ours to do.

    ``project_root`` publishes the change to a live pytest session, and is the ONLY reason this
    function takes it. Every write here mutates the suite that the very next `profile()` will
    score, but a live session hands out the collection it took when it OPENED — so without this,
    a re-profile is answered from a snapshot that predates the file we just wrote, and converge
    grades the suite it had before it did its work. Measured: 18 mutants killed by tests on
    disk, reported as 2, with the user asked to supply inputs for the 14 already dead. This is
    the single choke point through which every generated test reaches disk, so telling the
    session HERE is what makes "the suite changed" impossible to forget at a call site.
    Omitted (or no live session) it is a no-op and discovery re-collects per call as before."""
    os.makedirs(write_dir, exist_ok=True)
    path = os.path.join(write_dir, synth_filename(func_key))
    # The default home moved from tests/ to tests/detective/ (issue #21). A
    # file THIS target wrote under the old default would keep running beside
    # the new one — stale certificate content pytest still collects — so the
    # legacy sibling is removed on the way past. Ownership is checked by the
    # header grammar, never assumed from the name; user files are untouchable.
    # Retire every path a PREVIOUS scheme would have used for this target. There are two
    # dimensions now: the write dir moved (#21) and the basename gained a key digest (#61), so
    # a suite written before either change keeps running beside the new one — pytest collects
    # both and scores stale certificate content as current. Only files whose header claims THIS
    # target are touched; a name match alone is never enough.
    for retired in (
        os.path.join(write_dir, undigested_synth_filename(func_key)),
        _legacy_synth_path(write_dir, func_key),
    ):
        if retired and retired != path and os.path.exists(retired) and _owned_by(retired, func_key):
            os.remove(retired)
            _publish_suite_change(project_root, retired)
    # The PRIMARY destination gets the same ownership check the legacy sibling above already
    # had (#61). It did not, and the comment three lines up promised it did — so a file this
    # target does not own was removed or overwritten without a word. `synth_filename` flattens
    # `/ \ . - space` all to `_`, which makes that reachable without any user error at all:
    # `a/b.py::c` and `a_b.py::c` name one file. Both branches below are guarded, because
    # DELETING someone's tests on an empty-source pass destroys as much as overwriting them.
    exists = os.path.exists(path)
    disposition = write_disposition(exists, generated_owner(path) if exists else "", func_key)
    if disposition == "refuse_foreign":
        raise GeneratedSuiteCollision(
            f"{path} is Detective-generated but owned by {generated_owner(path)!r}, "
            f"not {func_key!r} — two targets normalise to one filename; rename one target "
            f"or use --write-dir until the naming is disambiguated"
        )
    if disposition == "refuse_unowned":
        raise GeneratedSuiteCollision(
            f"{path} exists and carries no Detective ownership header — it is not ours to "
            f"replace. Move it aside or point --write-dir elsewhere"
        )
    if not source.strip():
        if os.path.exists(path):
            os.remove(path)
            _publish_suite_change(project_root, path)  # a DELETION changes the suite too
        return ""
    with open(path, "w", encoding="utf-8") as fh:
        # Stamp a body-content digest (#X5/G5) so a later human edit of this generated file is
        # observable — ``witness_origin_of`` re-hashes and flips its origin to ``intent``. The digest
        # covers ``source`` (the file minus the stamped line), so the round-trip is self-consistent.
        fh.write(_stamp_content_digest(source))
    _publish_suite_change(project_root, path)
    return path


def _publish_suite_change(project_root: str | None, path: str) -> None:
    """Tell a live pytest session that ``path``'s tests changed on disk.

    Best-effort by construction: an older Wesker has no such seam, and a refresh that fails
    must never fail the run that wrote the file. The cost of it not happening is a stale
    verdict, which is exactly what the caller then reports — so it is worth doing, and never
    worth raising over."""
    if not project_root:
        return
    try:
        from Wesker.ci import refresh_live_suite

        refresh_live_suite(project_root, path)
    except Exception:  # noqa: BLE001 — older Wesker, or a collection hiccup; degrade quietly
        pass
