"""The certify loop — the product's front door.

One pass of the workflow: diagnose a function (behavioral-scope map via Wesker),
and for each unspecified degree of freedom (surviving mutant) synthesize a
warrant-classed pytest test. Optionally write the synthesized module to disk.

Driving to the ceiling is the caller's loop: certify -> write -> re-run tests ->
certify again, until ``at_ceiling``.
"""

from __future__ import annotations

import ast
import os
from collections.abc import Sequence
from dataclasses import dataclass

from .decompose import DecompositionPlan, decompose
from .engine import _resolve, profile
from .scope import ScopeMap, scope_from_profiling
from .synthesis.writer import synthesize_test_module


@dataclass(frozen=True)
class CertifyResult:
    """Outcome of one certify pass."""

    function: str
    scope: ScopeMap
    survivors: int
    at_ceiling: bool
    test_source: str  # "" when at the ceiling or nothing is synthesizable
    written_path: str | None
    decomposition: DecompositionPlan | None = None  # set for entangled (regime-B) functions
    wiring: PytestWiring | None = None  # how the written suite was wired to run under pytest


# The marker a generated test carries, and the line that makes it legal under --strict-markers.
_MARKER_NAME = "detective"
_MARKER_SPEC = f'"{_MARKER_NAME}: test generated by Detective"'
_PYTEST_SECTION = "[tool.pytest.ini_options]"


def ensure_marker_registered(project_root: str) -> str | None:
    """Make ``@pytest.mark.detective`` legal — DECLARATIVELY, in ``pyproject.toml``.

    This used to write a root ``conftest.py``. That was a mistake with a long tail. A generated
    conftest.py and an existing ``tests/conftest.py`` both import as the module ``conftest`` (any
    tree whose ``tests/`` is not a package — which is most of them), and in a process that imports
    both, the second one raises ``import file mismatch``. Plain pytest tolerates it; Detective's
    OWN in-process live session does not, so it died, silently fell back to collect-only
    discovery, and every fixture-taking test vanished from the profile. Surviving DOF was then
    overstated on exactly the repos careful enough to use fixtures — and Detective did it to
    itself, in its own repo, for as long as the feature existed.

    A marker is configuration. Configuration belongs in the config file, where it is declarative,
    idempotent, greppable, and — the whole point — cannot become a second module named
    ``conftest``. Nothing this writes can collide with anything.

    The sys.path insert the old conftest also did is not replaced, and is not missed: a generated
    test now imports its target by the name the REST of the repo imports it by (see
    ``importable_module``), so it resolves however the repo's own suite already resolves. If that
    name does not resolve at all, the shadow guard refuses before we ever get here.

    Returns a one-line description of what changed, or None if nothing needed doing. Never
    rewrites an existing markers list beyond appending, and never touches a consumer's conftest.
    """
    path = os.path.join(project_root, "pyproject.toml")
    try:
        with open(path, encoding="utf-8") as fh:
            source = fh.read()
    except OSError:
        return None  # no pyproject: nothing to declare into, and not ours to create
    if f'"{_MARKER_NAME}:' in source or f"'{_MARKER_NAME}:" in source:
        return None  # already registered — idempotent
    if _PYTEST_SECTION in source:
        updated = source.replace(_PYTEST_SECTION, f"{_PYTEST_SECTION}\nmarkers = [{_MARKER_SPEC}]", 1)
        what = f"registered the `{_MARKER_NAME}` marker in {_PYTEST_SECTION}"
    else:
        updated = f"{source.rstrip()}\n\n{_PYTEST_SECTION}\nmarkers = [{_MARKER_SPEC}]\n"
        what = f"added {_PYTEST_SECTION} with the `{_MARKER_NAME}` marker"
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(updated)
    except OSError:
        return None
    return what


@dataclass(frozen=True)
class PytestWiring:
    """What Detective found and did so the generated suite runs in the consumer."""

    conftest_wired: str | None  # path, if Detective just created one
    collects: bool  # did the written suite collect+pass under real pytest?
    passed: int  # number of tests that passed under pytest
    message: str  # the stated, CLI-surfaced diagnosis + fix — read this


def _pytest_available() -> bool:
    """Whether pytest is importable in the interpreter that runs the generated tests
    (the same one ``verify_under_pytest`` shells out to)."""
    import importlib.util

    return importlib.util.find_spec("pytest") is not None


def _wiring_message(
    conftest_wired: str | None, collects: bool, passed: int, pytest_available: bool = True
) -> str:
    """State, in plain language, the wiring gap Detective found and how it fixed it.

    This is the line a first-time user reads to know the generated tests will
    actually run — the fix must be obvious, not implied.
    """
    if conftest_wired:
        fix = (
            f"{conftest_wired} — the generated tests carry `@pytest.mark.detective`, which "
            f"`--strict-markers` rejects unless it is declared. Declared in config, so nothing "
            f"new is importable and nothing can collide"
        )
    else:
        fix = "pytest config already declares the marker — nothing to change"
    if collects:
        proof = f"verified {passed} test(s) pass under pytest"
    elif not pytest_available:
        # Do NOT misdiagnose a missing runner as a broken import path.
        proof = (
            "⚠ pytest is not installed here, so the written tests cannot be run or verified — "
            "`pip install pytest` (a normal Detective install includes it as a dependency)"
        )
    else:
        proof = "⚠ pytest could NOT collect the generated tests — check the import path"
    return f"pytest wiring: {fix}; {proof}"


def verify_under_pytest(project_root: str, test_path: str | Sequence[str]) -> tuple[bool, int]:
    """Run the test file(s) under REAL pytest (the consumer path, which Wesker's
    direct-call runner bypasses). Returns (collected_and_passed, count).

    ``test_path`` is one path or several: a suite Detective wrote is a single file,
    but the PRE-EXISTING suite that proves a decomposition can span several
    hand-written files (`decompose_apply._covering_test_files`)."""
    import re
    import subprocess
    import sys

    paths = [test_path] if isinstance(test_path, str) else list(test_path)
    if not paths:
        return False, 0

    # ``-o addopts=`` neutralizes the CONSUMER's pyproject addopts: a project that
    # already sets ``-q`` would combine with ours into ``-qq`` (double-quiet), which
    # suppresses the "N passed" summary this parse depends on — reporting 0 passed
    # for a suite that in fact passes. Controlling our own output makes the verifier
    # robust to whatever addopts the target project carries.
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", *paths, "-o", "addopts=", "-q", "-p", "no:cacheprovider"],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    passed = 0
    m = re.search(r"(\d+) passed", proc.stdout)
    if m:
        passed = int(m.group(1))
    ok = proc.returncode == 0 and "error" not in proc.stdout.lower()
    return ok, passed


def wire_pytest(project_root: str, test_path: str) -> PytestWiring:
    """Make the generated suite runnable in the consumer and STATE what was done: declare the
    marker in pyproject, then verify the tests actually collect+pass under pytest."""
    conftest_wired = ensure_marker_registered(project_root)
    collects, passed = verify_under_pytest(project_root, test_path)
    return PytestWiring(
        conftest_wired,
        collects,
        passed,
        _wiring_message(conftest_wired, collects, passed, _pytest_available()),
    )


def certify(
    file: str,
    function: str,
    project_root: str = ".",
    *,
    write_dir: str | None = None,
    call_site_inputs: list[dict] | None = None,
) -> CertifyResult:
    """Diagnose ``function`` and synthesize tests for its surviving mutants."""
    root = os.path.abspath(project_root)
    full = file if os.path.isabs(file) else os.path.join(root, file)
    with open(full, encoding="utf-8") as fh:
        tree = ast.parse(fh.read(), filename=full)

    qualname, node = _resolve(tree, function)
    if qualname is None:
        raise LookupError(f"function {function!r} not found in {file}")

    result = profile(file, function, project_root)
    scope = scope_from_profiling(result)
    func_key = f"{os.path.relpath(full, root)}::{qualname}"
    at_ceiling = result.value_survived == 0

    source = ""
    if not at_ceiling:
        source = synthesize_test_module(func_key, node, result.value_survivor_records, call_site_inputs)

    # Entangled functions get a decomposition plan alongside the synthesized tests.
    plan = None
    if scope.regime == "B":
        plan = decompose(node, qualname, tuple(scope.surviving_categories))

    written = None
    if source and write_dir:
        # Resolve write_dir against the project root (not CWD) so tests land in
        # the consumer's tree where their imports resolve — matches converge.
        target = write_dir if os.path.isabs(write_dir) else os.path.join(root, write_dir)
        written = _write(source, target, qualname, root)
    # Wire the written suite so it runs under real pytest, and state how (see converge).
    wiring = wire_pytest(root, written) if written else None
    return CertifyResult(func_key, scope, result.value_survived, at_ceiling, source, written, plan, wiring)


def _write(source: str, write_dir: str, qualname: str, project_root: str | None = None) -> str:
    """Write synthesized source to ``write_dir/test_<qualname>_synth.py``; return the path,
    or "" when there was nothing to write.

    Empty source means we contribute no test — e.g. converge's minimize pass dropped every
    test it generated as redundant against a suite that already covers the target. Writing a
    0-byte file there would claim a product that does not exist, and leaving a stale one from
    an earlier pass of the SAME run would ship the pre-minimize content the pass just
    rejected. This path is Detective's own regeneratable product (§8), never user data, so
    clearing it is ours to do.

    ``project_root`` publishes the change to a live pytest session, and is the ONLY reason this
    function takes it. Every write here mutates the suite that the very next `profile()` will
    score, but a live session hands out the collection it took when it OPENED — so without this,
    a re-profile is answered from a snapshot that predates the file we just wrote, and converge
    grades the suite it had before it did its work. Measured: 18 mutants killed by tests on
    disk, reported as 2, with the user asked to supply inputs for the 14 already dead. This is
    the single choke point through which every generated test reaches disk, so telling the
    session HERE is what makes "the suite changed" impossible to forget at a call site.
    Omitted (or no live session) it is a no-op and discovery re-collects per call as before."""
    os.makedirs(write_dir, exist_ok=True)
    safe = qualname.replace(".", "_")
    path = os.path.join(write_dir, f"test_{safe}_synth.py")
    if not source.strip():
        if os.path.exists(path):
            os.remove(path)
            _publish_suite_change(project_root, path)  # a DELETION changes the suite too
        return ""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(source)
    _publish_suite_change(project_root, path)
    return path


def _publish_suite_change(project_root: str | None, path: str) -> None:
    """Tell a live pytest session that ``path``'s tests changed on disk.

    Best-effort by construction: an older Wesker has no such seam, and a refresh that fails
    must never fail the run that wrote the file. The cost of it not happening is a stale
    verdict, which is exactly what the caller then reports — so it is worth doing, and never
    worth raising over."""
    if not project_root:
        return
    try:
        from Wesker.ci import refresh_live_suite

        refresh_live_suite(project_root, path)
    except Exception:  # noqa: BLE001 — older Wesker, or a collection hiccup; degrade quietly
        pass
