import Mathlib
open Function

/-- The map `Fin 3 → Fin 3` sending `0 ↦ a`, `1 ↦ b`, `2 ↦ c`, viewed as an element
of the full transformation monoid `Function.End (Fin 3)`. -/
private def m3 (a b c : Fin 3) : Function.End (Fin 3) := ![a, b, c]

/-- Every element of `Function.End (Fin 3)` is of the form `m3 a b c`. -/
private theorem m3_exists (f : Function.End (Fin 3)) : ∃ a b c, f = m3 a b c :=
  ⟨f 0, f 1, f 2, by funext i; fin_cases i <;> rfl⟩

/-- A submonoid of `Function.End (Fin 3)` containing the 3-cycle `(0 1 2)`, the
transposition `(0 1)` and the rank-2 idempotent collapsing `2` onto `1` is everything. -/
private theorem T3_aux (S : Submonoid (Function.End (Fin 3)))
    (ha : m3 1 2 0 ∈ S) (hb : m3 1 0 2 ∈ S) (hc : m3 0 1 1 ∈ S) : S = ⊤ := by
  have m012 : m3 0 1 2 ∈ S := by
    have h : m3 0 1 2 = 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact one_mem S
  have m120 : m3 1 2 0 ∈ S := ha
  have m102 : m3 1 0 2 ∈ S := hb
  have m011 : m3 0 1 1 ∈ S := hc
  have m201 : m3 2 0 1 ∈ S := by
    have h : m3 2 0 1 = m3 1 2 0 * m3 1 2 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m120
  have m021 : m3 0 2 1 ∈ S := by
    have h : m3 0 2 1 = m3 1 0 2 * m3 1 2 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m120
  have m110 : m3 1 1 0 ∈ S := by
    have h : m3 1 1 0 = m3 0 1 1 * m3 1 2 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hc m120
  have m210 : m3 2 1 0 ∈ S := by
    have h : m3 2 1 0 = m3 1 2 0 * m3 1 0 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m102
  have m101 : m3 1 0 1 ∈ S := by
    have h : m3 1 0 1 = m3 0 1 1 * m3 1 0 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hc m102
  have m122 : m3 1 2 2 ∈ S := by
    have h : m3 1 2 2 = m3 1 2 0 * m3 0 1 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m011
  have m100 : m3 1 0 0 ∈ S := by
    have h : m3 1 0 0 = m3 1 0 2 * m3 0 1 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m011
  have m221 : m3 2 2 1 ∈ S := by
    have h : m3 2 2 1 = m3 1 2 0 * m3 1 1 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m110
  have m001 : m3 0 0 1 ∈ S := by
    have h : m3 0 0 1 = m3 1 0 2 * m3 1 1 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m110
  have m212 : m3 2 1 2 ∈ S := by
    have h : m3 2 1 2 = m3 1 2 0 * m3 1 0 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m101
  have m010 : m3 0 1 0 ∈ S := by
    have h : m3 0 1 0 = m3 1 0 2 * m3 1 0 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m101
  have m200 : m3 2 0 0 ∈ S := by
    have h : m3 2 0 0 = m3 1 2 0 * m3 1 2 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m122
  have m022 : m3 0 2 2 ∈ S := by
    have h : m3 0 2 2 = m3 1 0 2 * m3 1 2 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m122
  have m111 : m3 1 1 1 ∈ S := by
    have h : m3 1 1 1 = m3 0 1 1 * m3 1 2 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hc m122
  have m211 : m3 2 1 1 ∈ S := by
    have h : m3 2 1 1 = m3 1 2 0 * m3 1 0 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m100
  have m002 : m3 0 0 2 ∈ S := by
    have h : m3 0 0 2 = m3 1 2 0 * m3 2 2 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m221
  have m220 : m3 2 2 0 ∈ S := by
    have h : m3 2 2 0 = m3 1 0 2 * m3 2 2 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m221
  have m112 : m3 1 1 2 ∈ S := by
    have h : m3 1 1 2 = m3 1 2 0 * m3 0 0 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m001
  have m020 : m3 0 2 0 ∈ S := by
    have h : m3 0 2 0 = m3 1 2 0 * m3 2 1 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m212
  have m202 : m3 2 0 2 ∈ S := by
    have h : m3 2 0 2 = m3 1 0 2 * m3 2 1 2 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m212
  have m121 : m3 1 2 1 ∈ S := by
    have h : m3 1 2 1 = m3 1 2 0 * m3 0 1 0 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m010
  have m222 : m3 2 2 2 ∈ S := by
    have h : m3 2 2 2 = m3 1 2 0 * m3 1 1 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem ha m111
  have m000 : m3 0 0 0 ∈ S := by
    have h : m3 0 0 0 = m3 1 0 2 * m3 1 1 1 := by funext i; fin_cases i <;> rfl
    rw [h]; exact mul_mem hb m111
  refine le_antisymm le_top fun f _ => ?_
  obtain ⟨x, y, z, rfl⟩ := m3_exists f
  fin_cases x <;> fin_cases y <;> fin_cases z <;> assumption

/-- The full transformation monoid on three points is generated by the cyclic shift
`x ↦ x + 1`, the transposition of `0` and `1`, and the rank-2 map sending `2` to `1`. -/
theorem T3_generated_rank3 :
    Submonoid.closure
      ({(fun x => x + 1 : Function.End (Fin 3)),
        (fun x => if x = 0 then 1 else if x = 1 then 0 else 2 : Function.End (Fin 3)),
        (fun x => if x = 2 then 1 else x : Function.End (Fin 3))} :
        Set (Function.End (Fin 3))) = ⊤ := by
  refine T3_aux _ (Submonoid.subset_closure ?_) (Submonoid.subset_closure ?_)
    (Submonoid.subset_closure ?_)
  · exact Or.inl (by funext i; fin_cases i <;> rfl)
  · exact Or.inr (Or.inl (by funext i; fin_cases i <;> rfl))
  · exact Or.inr (Or.inr (by funext i; fin_cases i <;> rfl))
