import Mathlib
open Function

/-- The submonoid generated by a finite set is countable: every element is a finite product
of generators, so the closure is contained in the range of `List.prod` over lists of
generators, and `List P` is countable. -/
theorem Submonoid.closure_finset_countable {M : Type*} [Monoid M] (P : Finset M) :
    (Submonoid.closure (↑P : Set M) : Set M).Countable := by
  have hsub : (Submonoid.closure (↑P : Set M) : Set M) ⊆
      Set.range (fun l : List P => (l.map Subtype.val).prod) := by
    intro x hx
    obtain ⟨l, hl, rfl⟩ := Submonoid.exists_list_of_mem_closure hx
    refine ⟨l.attach.map (fun y => ⟨y.1, hl y.1 y.2⟩), ?_⟩
    simp
  exact Set.Countable.mono hsub (Set.countable_range _)

/-- Cantor: for an infinite type `R`, the full transformation monoid `Function.End R = (R → R)`
is uncountable, since `ℵ₀ ≤ #R < 2 ^ #R ≤ #R ^ #R = #(R → R)`. -/
theorem Function.End.not_countable (R : Type*) [Infinite R] : ¬ Countable (Function.End R) := by
  intro h
  have h1 : Cardinal.mk (Function.End R) ≤ Cardinal.aleph0 := Cardinal.mk_le_aleph0
  have h2 : Cardinal.aleph0 ≤ Cardinal.mk R := Cardinal.aleph0_le_mk R
  have h3 : Cardinal.mk R < 2 ^ Cardinal.mk R := Cardinal.cantor _
  have h2' : (2 : Cardinal) ≤ Cardinal.mk R :=
    le_trans (by exact_mod_cast (Cardinal.natCast_lt_aleph0 (n := 2)).le) h2
  have h4 : (2 : Cardinal) ^ Cardinal.mk R ≤ Cardinal.mk (Function.End R) := by
    have he : Cardinal.mk (Function.End R) = Cardinal.mk R ^ Cardinal.mk R := by
      rw [show (Function.End R) = (R → R) from rfl, Cardinal.mk_arrow]
      simp
    rw [he]
    exact Cardinal.power_le_power_right h2'
  exact absurd (h2.trans_lt (h3.trans_le (h4.trans h1))) (lt_irrefl _)

/-- On an infinite type `R`, no finite subset of the full transformation monoid `Function.End R`
generates it: the generated submonoid is countable while `Function.End R` is uncountable. -/
theorem pi_incomplete_infinite
    (R : Type) [Infinite R] (P : Finset (Function.End R)) :
    Submonoid.closure (↑P : Set (Function.End R)) ≠ ⊤ := by
  intro htop
  have hc : (Set.univ : Set (Function.End R)).Countable := by
    have := Submonoid.closure_finset_countable P
    rwa [htop, Submonoid.coe_top] at this
  exact Function.End.not_countable R (Set.countable_univ_iff.mp hc)
