import Mathlib
open Function

/-- The monoid of all self-maps of `Fin 2` is generated by the successor map `x ↦ x + 1`
together with the constant map `x ↦ 0`. -/
theorem T2_generated :
    Submonoid.closure
      ({(fun x => x + 1 : Function.End (Fin 2)),
        (fun _ => 0 : Function.End (Fin 2))} : Set (Function.End (Fin 2))) = ⊤ := by
  set s : Function.End (Fin 2) := (fun x => x + 1) with hs_def
  set c : Function.End (Fin 2) := (fun _ => 0) with hc_def
  have hs : s ∈ Submonoid.closure ({s, c} : Set (Function.End (Fin 2))) :=
    Submonoid.subset_closure (by simp)
  have hc : c ∈ Submonoid.closure ({s, c} : Set (Function.End (Fin 2))) :=
    Submonoid.subset_closure (by simp)
  have hone : (fun _ => (1 : Fin 2)) = s * c := by
    funext x
    rfl
  refine eq_top_iff.mpr fun f _ => ?_
  have hcases : ∀ g : Fin 2 → Fin 2, g = (fun x => x) ∨ g = (fun x => x + 1) ∨
      g = (fun _ => 0) ∨ g = (fun _ => 1) := by decide
  rcases hcases f with h | h | h | h
  · have : f = 1 := h
    rw [this]
    exact one_mem _
  · rw [show f = s from h]
    exact hs
  · rw [show f = c from h]
    exact hc
  · rw [show f = s * c from h.trans hone]
    exact mul_mem hs hc
